# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anadirpersonal_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class AnadirPersonal_Ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(999, 600)
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("background-color: rgb(210, 210, 210);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.aceptcancel = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.aceptcancel.setGeometry(QtCore.QRect(580, 400, 193, 28))
        self.aceptcancel.setStyleSheet("background-color: rgb(140, 140, 140);")
        self.aceptcancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.aceptcancel.setObjectName("aceptcancel")
        self.anadirperso = QtWidgets.QLabel(self.centralwidget)
        self.anadirperso.setGeometry(QtCore.QRect(110, 40, 231, 61))
        self.anadirperso.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.anadirperso.setObjectName("anadirperso")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(470, 120, 411, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkCC = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkCC.setObjectName("checkCC")
        self.gridLayout.addWidget(self.checkCC, 0, 0, 1, 1)
        self.checkOPL = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkOPL.setObjectName("checkOPL")
        self.gridLayout.addWidget(self.checkOPL, 0, 1, 1, 1)
        self.checkDIM = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkDIM.setObjectName("checkDIM")
        self.gridLayout.addWidget(self.checkDIM, 0, 2, 1, 1)
        self.checkTECL = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkTECL.setObjectName("checkTECL")
        self.gridLayout.addWidget(self.checkTECL, 0, 3, 1, 1)
        self.checkRIG = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkRIG.setObjectName("checkRIG")
        self.gridLayout.addWidget(self.checkRIG, 0, 4, 1, 1)
        self.tarifaCC = QtWidgets.QLineEdit(self.layoutWidget)
        self.tarifaCC.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(188, 188, 188);")
        self.tarifaCC.setText("")
        self.tarifaCC.setObjectName("tarifaCC")
        self.gridLayout.addWidget(self.tarifaCC, 1, 0, 1, 1)
        self.tarifaOPL = QtWidgets.QLineEdit(self.layoutWidget)
        self.tarifaOPL.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(188, 188, 188);")
        self.tarifaOPL.setText("")
        self.tarifaOPL.setObjectName("tarifaOPL")
        self.gridLayout.addWidget(self.tarifaOPL, 1, 1, 1, 1)
        self.tarifaDIM = QtWidgets.QLineEdit(self.layoutWidget)
        self.tarifaDIM.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(188, 188, 188);")
        self.tarifaDIM.setText("")
        self.tarifaDIM.setObjectName("tarifaDIM")
        self.gridLayout.addWidget(self.tarifaDIM, 1, 2, 1, 1)
        self.tarifaTECL = QtWidgets.QLineEdit(self.layoutWidget)
        self.tarifaTECL.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(188, 188, 188);")
        self.tarifaTECL.setText("")
        self.tarifaTECL.setObjectName("tarifaTECL")
        self.gridLayout.addWidget(self.tarifaTECL, 1, 3, 1, 1)
        self.tarifaRIG = QtWidgets.QLineEdit(self.layoutWidget)
        self.tarifaRIG.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(188, 188, 188);")
        self.tarifaRIG.setText("")
        self.tarifaRIG.setObjectName("tarifaRIG")
        self.gridLayout.addWidget(self.tarifaRIG, 1, 4, 1, 1)
        self.checkREGI = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkREGI.setObjectName("checkREGI")
        self.gridLayout.addWidget(self.checkREGI, 2, 0, 1, 1)
        self.checkOPS = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkOPS.setObjectName("checkOPS")
        self.gridLayout.addWidget(self.checkOPS, 2, 1, 1, 1)
        self.checkRF = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkRF.setObjectName("checkRF")
        self.gridLayout.addWidget(self.checkRF, 2, 2, 1, 1)
        self.checkTECS = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkTECS.setObjectName("checkTECS")
        self.gridLayout.addWidget(self.checkTECS, 2, 3, 1, 1)
        self.checkDECO = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkDECO.setObjectName("checkDECO")
        self.gridLayout.addWidget(self.checkDECO, 2, 4, 1, 1)
        self.tarifaREGI = QtWidgets.QLineEdit(self.layoutWidget)
        self.tarifaREGI.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(188, 188, 188);")
        self.tarifaREGI.setText("")
        self.tarifaREGI.setObjectName("tarifaREGI")
        self.gridLayout.addWidget(self.tarifaREGI, 3, 0, 1, 1)
        self.tarifaOPS = QtWidgets.QLineEdit(self.layoutWidget)
        self.tarifaOPS.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(188, 188, 188);")
        self.tarifaOPS.setText("")
        self.tarifaOPS.setObjectName("tarifaOPS")
        self.gridLayout.addWidget(self.tarifaOPS, 3, 1, 1, 1)
        self.tarifaRF = QtWidgets.QLineEdit(self.layoutWidget)
        self.tarifaRF.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(188, 188, 188);")
        self.tarifaRF.setText("")
        self.tarifaRF.setObjectName("tarifaRF")
        self.gridLayout.addWidget(self.tarifaRF, 3, 2, 1, 1)
        self.tarifaTECS = QtWidgets.QLineEdit(self.layoutWidget)
        self.tarifaTECS.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(188, 188, 188);")
        self.tarifaTECS.setText("")
        self.tarifaTECS.setObjectName("tarifaTECS")
        self.gridLayout.addWidget(self.tarifaTECS, 3, 3, 1, 1)
        self.tarifaDECO = QtWidgets.QLineEdit(self.layoutWidget)
        self.tarifaDECO.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(188, 188, 188);")
        self.tarifaDECO.setText("")
        self.tarifaDECO.setObjectName("tarifaDECO")
        self.gridLayout.addWidget(self.tarifaDECO, 3, 4, 1, 1)
        self.checkCONT = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkCONT.setObjectName("checkCONT")
        self.gridLayout.addWidget(self.checkCONT, 4, 0, 1, 1)
        self.checkOPV = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkOPV.setObjectName("checkOPV")
        self.gridLayout.addWidget(self.checkOPV, 4, 1, 1, 1)
        self.checkLED = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkLED.setObjectName("checkLED")
        self.gridLayout.addWidget(self.checkLED, 4, 2, 1, 1)
        self.checkTECV = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkTECV.setObjectName("checkTECV")
        self.gridLayout.addWidget(self.checkTECV, 4, 3, 1, 1)
        self.tarifaCONT = QtWidgets.QLineEdit(self.layoutWidget)
        self.tarifaCONT.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(188, 188, 188);")
        self.tarifaCONT.setText("")
        self.tarifaCONT.setObjectName("tarifaCONT")
        self.gridLayout.addWidget(self.tarifaCONT, 5, 0, 1, 1)
        self.tarifaOPV = QtWidgets.QLineEdit(self.layoutWidget)
        self.tarifaOPV.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(188, 188, 188);")
        self.tarifaOPV.setText("")
        self.tarifaOPV.setObjectName("tarifaOPV")
        self.gridLayout.addWidget(self.tarifaOPV, 5, 1, 1, 1)
        self.tarifaLED = QtWidgets.QLineEdit(self.layoutWidget)
        self.tarifaLED.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(188, 188, 188);")
        self.tarifaLED.setText("")
        self.tarifaLED.setObjectName("tarifaLED")
        self.gridLayout.addWidget(self.tarifaLED, 5, 2, 1, 1)
        self.tarifaTECV = QtWidgets.QLineEdit(self.layoutWidget)
        self.tarifaTECV.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(188, 188, 188);")
        self.tarifaTECV.setText("")
        self.tarifaTECV.setObjectName("tarifaTECV")
        self.gridLayout.addWidget(self.tarifaTECV, 5, 3, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(112, 125, 310, 305))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nombre = QtWidgets.QLabel(self.layoutWidget1)
        self.nombre.setObjectName("nombre")
        self.horizontalLayout_2.addWidget(self.nombre)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.entryNOMBRE = QtWidgets.QLineEdit(self.layoutWidget1)
        self.entryNOMBRE.setMinimumSize(QtCore.QSize(200, 0))
        self.entryNOMBRE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entryNOMBRE.setText("")
        self.entryNOMBRE.setObjectName("entryNOMBRE")
        self.horizontalLayout_2.addWidget(self.entryNOMBRE)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.apellidos = QtWidgets.QLabel(self.layoutWidget1)
        self.apellidos.setObjectName("apellidos")
        self.horizontalLayout_3.addWidget(self.apellidos)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.entryAPELL = QtWidgets.QLineEdit(self.layoutWidget1)
        self.entryAPELL.setMinimumSize(QtCore.QSize(200, 0))
        self.entryAPELL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entryAPELL.setObjectName("entryAPELL")
        self.horizontalLayout_3.addWidget(self.entryAPELL)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dni = QtWidgets.QLabel(self.layoutWidget1)
        self.dni.setObjectName("dni")
        self.horizontalLayout_4.addWidget(self.dni)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.entryDNI = QtWidgets.QLineEdit(self.layoutWidget1)
        self.entryDNI.setMinimumSize(QtCore.QSize(200, 0))
        self.entryDNI.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entryDNI.setObjectName("entryDNI")
        self.horizontalLayout_4.addWidget(self.entryDNI)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.telefono = QtWidgets.QLabel(self.layoutWidget1)
        self.telefono.setObjectName("telefono")
        self.horizontalLayout_5.addWidget(self.telefono)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.entryTFN = QtWidgets.QLineEdit(self.layoutWidget1)
        self.entryTFN.setMinimumSize(QtCore.QSize(200, 0))
        self.entryTFN.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entryTFN.setObjectName("entryTFN")
        self.horizontalLayout_5.addWidget(self.entryTFN)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.email = QtWidgets.QLabel(self.layoutWidget1)
        self.email.setObjectName("email")
        self.horizontalLayout_6.addWidget(self.email)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.entryEMAIL = QtWidgets.QLineEdit(self.layoutWidget1)
        self.entryEMAIL.setMinimumSize(QtCore.QSize(200, 0))
        self.entryEMAIL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entryEMAIL.setObjectName("entryEMAIL")
        self.horizontalLayout_6.addWidget(self.entryEMAIL)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.direccion = QtWidgets.QLabel(self.layoutWidget1)
        self.direccion.setObjectName("direccion")
        self.horizontalLayout_7.addWidget(self.direccion)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.entryDIRECCION = QtWidgets.QLineEdit(self.layoutWidget1)
        self.entryDIRECCION.setMinimumSize(QtCore.QSize(200, 0))
        self.entryDIRECCION.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entryDIRECCION.setText("")
        self.entryDIRECCION.setObjectName("entryDIRECCION")
        self.horizontalLayout_7.addWidget(self.entryDIRECCION)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.cp = QtWidgets.QLabel(self.layoutWidget1)
        self.cp.setObjectName("cp")
        self.horizontalLayout_8.addWidget(self.cp)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.entryCP = QtWidgets.QLineEdit(self.layoutWidget1)
        self.entryCP.setMinimumSize(QtCore.QSize(200, 0))
        self.entryCP.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entryCP.setText("")
        self.entryCP.setObjectName("entryCP")
        self.horizontalLayout_8.addWidget(self.entryCP)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ciudad = QtWidgets.QLabel(self.layoutWidget1)
        self.ciudad.setObjectName("ciudad")
        self.horizontalLayout_9.addWidget(self.ciudad)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.entryCIUDAD = QtWidgets.QLineEdit(self.layoutWidget1)
        self.entryCIUDAD.setMinimumSize(QtCore.QSize(200, 0))
        self.entryCIUDAD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entryCIUDAD.setText("")
        self.entryCIUDAD.setObjectName("entryCIUDAD")
        self.horizontalLayout_9.addWidget(self.entryCIUDAD)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.iban = QtWidgets.QLabel(self.layoutWidget1)
        self.iban.setObjectName("iban")
        self.horizontalLayout_10.addWidget(self.iban)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.entryIBAN = QtWidgets.QLineEdit(self.layoutWidget1)
        self.entryIBAN.setMinimumSize(QtCore.QSize(200, 0))
        self.entryIBAN.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entryIBAN.setObjectName("entryIBAN")
        self.horizontalLayout_10.addWidget(self.entryIBAN)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.autonomo = QtWidgets.QLabel(self.layoutWidget1)
        self.autonomo.setStyleSheet("")
        self.autonomo.setObjectName("autonomo")
        self.horizontalLayout_11.addWidget(self.autonomo)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioSI = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioSI.setObjectName("radioSI")
        self.horizontalLayout.addWidget(self.radioSI)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.radioNO = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioNO.setObjectName("radioNO")
        self.horizontalLayout.addWidget(self.radioNO)
        self.horizontalLayout_11.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(110, 440, 311, 89))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.notas_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.notas_2.setObjectName("notas_2")
        self.verticalLayout_2.addWidget(self.notas_2)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem11)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        self.textNOTAS = QtWidgets.QTextEdit(self.layoutWidget2)
        self.textNOTAS.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textNOTAS.setObjectName("textNOTAS")
        self.horizontalLayout_12.addWidget(self.textNOTAS)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.entryNOMBRE, self.entryAPELL)
        MainWindow.setTabOrder(self.entryAPELL, self.entryDNI)
        MainWindow.setTabOrder(self.entryDNI, self.entryTFN)
        MainWindow.setTabOrder(self.entryTFN, self.entryEMAIL)
        MainWindow.setTabOrder(self.entryEMAIL, self.entryDIRECCION)
        MainWindow.setTabOrder(self.entryDIRECCION, self.entryCP)
        MainWindow.setTabOrder(self.entryCP, self.entryCIUDAD)
        MainWindow.setTabOrder(self.entryCIUDAD, self.entryIBAN)
        MainWindow.setTabOrder(self.entryIBAN, self.radioSI)
        MainWindow.setTabOrder(self.radioSI, self.radioNO)
        MainWindow.setTabOrder(self.radioNO, self.checkCC)
        MainWindow.setTabOrder(self.checkCC, self.checkOPL)
        MainWindow.setTabOrder(self.checkOPL, self.checkDIM)
        MainWindow.setTabOrder(self.checkDIM, self.checkTECL)
        MainWindow.setTabOrder(self.checkTECL, self.checkRIG)
        MainWindow.setTabOrder(self.checkRIG, self.checkREGI)
        MainWindow.setTabOrder(self.checkREGI, self.checkOPS)
        MainWindow.setTabOrder(self.checkOPS, self.checkRF)
        MainWindow.setTabOrder(self.checkRF, self.checkTECS)
        MainWindow.setTabOrder(self.checkTECS, self.checkDECO)
        MainWindow.setTabOrder(self.checkDECO, self.checkCONT)
        MainWindow.setTabOrder(self.checkCONT, self.checkOPV)
        MainWindow.setTabOrder(self.checkOPV, self.checkLED)
        MainWindow.setTabOrder(self.checkLED, self.checkTECV)
        MainWindow.setTabOrder(self.checkTECV, self.tarifaCC)
        MainWindow.setTabOrder(self.tarifaCC, self.tarifaOPL)
        MainWindow.setTabOrder(self.tarifaOPL, self.tarifaDIM)
        MainWindow.setTabOrder(self.tarifaDIM, self.tarifaTECL)
        MainWindow.setTabOrder(self.tarifaTECL, self.tarifaRIG)
        MainWindow.setTabOrder(self.tarifaRIG, self.tarifaREGI)
        MainWindow.setTabOrder(self.tarifaREGI, self.tarifaOPS)
        MainWindow.setTabOrder(self.tarifaOPS, self.tarifaRF)
        MainWindow.setTabOrder(self.tarifaRF, self.tarifaTECS)
        MainWindow.setTabOrder(self.tarifaTECS, self.tarifaDECO)
        MainWindow.setTabOrder(self.tarifaDECO, self.tarifaCONT)
        MainWindow.setTabOrder(self.tarifaCONT, self.tarifaOPV)
        MainWindow.setTabOrder(self.tarifaOPV, self.tarifaLED)
        MainWindow.setTabOrder(self.tarifaLED, self.tarifaTECV)
        MainWindow.setTabOrder(self.tarifaTECV, self.textNOTAS)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.anadirperso.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">AÑADIR PERSONAL</p></body></html>"))
        self.checkCC.setText(_translate("MainWindow", "CC"))
        self.checkOPL.setText(_translate("MainWindow", "OPL"))
        self.checkDIM.setText(_translate("MainWindow", "DIM"))
        self.checkTECL.setText(_translate("MainWindow", "TECL"))
        self.checkRIG.setText(_translate("MainWindow", "RIGGING"))
        self.checkREGI.setText(_translate("MainWindow", "REGI"))
        self.checkOPS.setText(_translate("MainWindow", "OPS"))
        self.checkRF.setText(_translate("MainWindow", "RF"))
        self.checkTECS.setText(_translate("MainWindow", "TECS"))
        self.checkDECO.setText(_translate("MainWindow", "DECO"))
        self.checkCONT.setText(_translate("MainWindow", "CONT"))
        self.checkOPV.setText(_translate("MainWindow", "OPV"))
        self.checkLED.setText(_translate("MainWindow", "LED"))
        self.checkTECV.setText(_translate("MainWindow", "TECV"))
        self.nombre.setText(_translate("MainWindow", "Nombre"))
        self.apellidos.setText(_translate("MainWindow", "Apellidos"))
        self.dni.setText(_translate("MainWindow", "DNI"))
        self.telefono.setText(_translate("MainWindow", "Teléfono"))
        self.email.setText(_translate("MainWindow", "Email"))
        self.direccion.setText(_translate("MainWindow", "Dirección"))
        self.cp.setText(_translate("MainWindow", "C.P."))
        self.ciudad.setText(_translate("MainWindow", "Ciudad"))
        self.iban.setText(_translate("MainWindow", "IBAN"))
        self.autonomo.setText(_translate("MainWindow", "Autónomo"))
        self.radioSI.setText(_translate("MainWindow", "Sí"))
        self.radioNO.setText(_translate("MainWindow", "No"))
        self.notas_2.setText(_translate("MainWindow", "Notas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = AnadirPersonal_Ui()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

