# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anadirproveedor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class AnadirProveedor_Ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 600)
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.aceptcancel = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.aceptcancel.setGeometry(QtCore.QRect(780, 390, 193, 28))
        self.aceptcancel.setStyleSheet("background-color: rgb(140, 140, 140);")
        self.aceptcancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.aceptcancel.setObjectName("aceptcancel")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(620, 150, 519, 166))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.servicios = QtWidgets.QLabel(self.layoutWidget)
        self.servicios.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.servicios.setObjectName("servicios")
        self.verticalLayout_9.addWidget(self.servicios)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.check_trailer = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_trailer.setObjectName("check_trailer")
        self.verticalLayout_2.addWidget(self.check_trailer)
        self.check_camion = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_camion.setObjectName("check_camion")
        self.verticalLayout_2.addWidget(self.check_camion)
        self.check_furgo = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_furgo.setObjectName("check_furgo")
        self.verticalLayout_2.addWidget(self.check_furgo)
        self.check_runner = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_runner.setObjectName("check_runner")
        self.verticalLayout_2.addWidget(self.check_runner)
        self.check_c_d = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_c_d.setObjectName("check_c_d")
        self.verticalLayout_2.addWidget(self.check_c_d)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.check_rigging = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_rigging.setObjectName("check_rigging")
        self.verticalLayout_7.addWidget(self.check_rigging)
        self.check_deco = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_deco.setObjectName("check_deco")
        self.verticalLayout_7.addWidget(self.check_deco)
        self.check_generadores = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_generadores.setObjectName("check_generadores")
        self.verticalLayout_7.addWidget(self.check_generadores)
        self.check_tradu = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_tradu.setObjectName("check_tradu")
        self.verticalLayout_7.addWidget(self.check_tradu)
        self.check_catering = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_catering.setObjectName("check_catering")
        self.verticalLayout_7.addWidget(self.check_catering)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.check_iluminacion = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_iluminacion.setObjectName("check_iluminacion")
        self.verticalLayout_8.addWidget(self.check_iluminacion)
        self.check_sonido = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_sonido.setObjectName("check_sonido")
        self.verticalLayout_8.addWidget(self.check_sonido)
        self.check_video = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_video.setObjectName("check_video")
        self.verticalLayout_8.addWidget(self.check_video)
        self.check_mobiliario = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_mobiliario.setObjectName("check_mobiliario")
        self.verticalLayout_8.addWidget(self.check_mobiliario)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.check_otros = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_otros.setObjectName("check_otros")
        self.horizontalLayout_2.addWidget(self.check_otros)
        self.entry_otros = QtWidgets.QLineEdit(self.layoutWidget)
        self.entry_otros.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_otros.setClearButtonEnabled(False)
        self.entry_otros.setObjectName("entry_otros")
        self.horizontalLayout_2.addWidget(self.entry_otros)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.anadir_proveedor = QtWidgets.QLabel(self.centralwidget)
        self.anadir_proveedor.setGeometry(QtCore.QRect(90, 40, 389, 21))
        self.anadir_proveedor.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.anadir_proveedor.setObjectName("anadir_proveedor")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(90, 80, 391, 471))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.entry_localidad = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_localidad.sizePolicy().hasHeightForWidth())
        self.entry_localidad.setSizePolicy(sizePolicy)
        self.entry_localidad.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_localidad.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_localidad.setText("")
        self.entry_localidad.setObjectName("entry_localidad")
        self.gridLayout.addWidget(self.entry_localidad, 2, 2, 1, 1)
        self.direccion = QtWidgets.QLabel(self.widget)
        self.direccion.setMinimumSize(QtCore.QSize(100, 0))
        self.direccion.setObjectName("direccion")
        self.gridLayout.addWidget(self.direccion, 3, 0, 1, 2)
        self.entry_cif = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_cif.sizePolicy().hasHeightForWidth())
        self.entry_cif.setSizePolicy(sizePolicy)
        self.entry_cif.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_cif.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_cif.setObjectName("entry_cif")
        self.gridLayout.addWidget(self.entry_cif, 4, 2, 1, 1)
        self.entryTFN = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entryTFN.sizePolicy().hasHeightForWidth())
        self.entryTFN.setSizePolicy(sizePolicy)
        self.entryTFN.setMinimumSize(QtCore.QSize(180, 0))
        self.entryTFN.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entryTFN.setObjectName("entryTFN")
        self.gridLayout.addWidget(self.entryTFN, 5, 2, 1, 1)
        self.email = QtWidgets.QLabel(self.widget)
        self.email.setMinimumSize(QtCore.QSize(100, 0))
        self.email.setObjectName("email")
        self.gridLayout.addWidget(self.email, 6, 0, 1, 2)
        self.telefono = QtWidgets.QLabel(self.widget)
        self.telefono.setMinimumSize(QtCore.QSize(100, 0))
        self.telefono.setObjectName("telefono")
        self.gridLayout.addWidget(self.telefono, 5, 0, 1, 2)
        self.entry_email = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_email.sizePolicy().hasHeightForWidth())
        self.entry_email.setSizePolicy(sizePolicy)
        self.entry_email.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_email.setObjectName("entry_email")
        self.gridLayout.addWidget(self.entry_email, 6, 2, 1, 1)
        self.entry_direccion = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_direccion.sizePolicy().hasHeightForWidth())
        self.entry_direccion.setSizePolicy(sizePolicy)
        self.entry_direccion.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_direccion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_direccion.setObjectName("entry_direccion")
        self.gridLayout.addWidget(self.entry_direccion, 3, 2, 1, 1)
        self.email_2 = QtWidgets.QLabel(self.widget)
        self.email_2.setMinimumSize(QtCore.QSize(100, 0))
        self.email_2.setObjectName("email_2")
        self.gridLayout.addWidget(self.email_2, 7, 0, 1, 1)
        self.entry_web = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_web.sizePolicy().hasHeightForWidth())
        self.entry_web.setSizePolicy(sizePolicy)
        self.entry_web.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_web.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_web.setObjectName("entry_web")
        self.gridLayout.addWidget(self.entry_web, 7, 2, 1, 1)
        self.contacto = QtWidgets.QLabel(self.widget)
        self.contacto.setMinimumSize(QtCore.QSize(100, 0))
        self.contacto.setObjectName("contacto")
        self.gridLayout.addWidget(self.contacto, 8, 0, 1, 2)
        self.cif = QtWidgets.QLabel(self.widget)
        self.cif.setMinimumSize(QtCore.QSize(100, 0))
        self.cif.setObjectName("cif")
        self.gridLayout.addWidget(self.cif, 4, 0, 1, 2)
        self.empresa = QtWidgets.QLabel(self.widget)
        self.empresa.setMinimumSize(QtCore.QSize(100, 0))
        self.empresa.setObjectName("empresa")
        self.gridLayout.addWidget(self.empresa, 0, 0, 1, 2)
        self.provincia = QtWidgets.QLabel(self.widget)
        self.provincia.setMinimumSize(QtCore.QSize(100, 0))
        self.provincia.setObjectName("provincia")
        self.gridLayout.addWidget(self.provincia, 1, 0, 1, 2)
        self.entry_empresa = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_empresa.sizePolicy().hasHeightForWidth())
        self.entry_empresa.setSizePolicy(sizePolicy)
        self.entry_empresa.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_empresa.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_empresa.setObjectName("entry_empresa")
        self.gridLayout.addWidget(self.entry_empresa, 0, 2, 1, 1)
        self.entry_provincia = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_provincia.sizePolicy().hasHeightForWidth())
        self.entry_provincia.setSizePolicy(sizePolicy)
        self.entry_provincia.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_provincia.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_provincia.setObjectName("entry_provincia")
        self.gridLayout.addWidget(self.entry_provincia, 1, 2, 1, 1)
        self.provincia_2 = QtWidgets.QLabel(self.widget)
        self.provincia_2.setMinimumSize(QtCore.QSize(100, 0))
        self.provincia_2.setObjectName("provincia_2")
        self.gridLayout.addWidget(self.provincia_2, 2, 0, 1, 2)
        self.textNOTAS = QtWidgets.QTextEdit(self.widget)
        self.textNOTAS.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textNOTAS.setObjectName("textNOTAS")
        self.gridLayout.addWidget(self.textNOTAS, 11, 1, 1, 2)
        self.email_contacto = QtWidgets.QLabel(self.widget)
        self.email_contacto.setMinimumSize(QtCore.QSize(100, 0))
        self.email_contacto.setObjectName("email_contacto")
        self.gridLayout.addWidget(self.email_contacto, 10, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.notas = QtWidgets.QLabel(self.widget)
        self.notas.setMinimumSize(QtCore.QSize(100, 0))
        self.notas.setObjectName("notas")
        self.verticalLayout.addWidget(self.notas)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 11, 0, 1, 1)
        self.tfn_contacto = QtWidgets.QLabel(self.widget)
        self.tfn_contacto.setMinimumSize(QtCore.QSize(100, 0))
        self.tfn_contacto.setObjectName("tfn_contacto")
        self.gridLayout.addWidget(self.tfn_contacto, 9, 0, 1, 2)
        self.entry_tfn_contacto = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_tfn_contacto.sizePolicy().hasHeightForWidth())
        self.entry_tfn_contacto.setSizePolicy(sizePolicy)
        self.entry_tfn_contacto.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_tfn_contacto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_tfn_contacto.setObjectName("entry_tfn_contacto")
        self.gridLayout.addWidget(self.entry_tfn_contacto, 9, 2, 1, 1)
        self.entry_email_contacto = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_email_contacto.sizePolicy().hasHeightForWidth())
        self.entry_email_contacto.setSizePolicy(sizePolicy)
        self.entry_email_contacto.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_email_contacto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_email_contacto.setObjectName("entry_email_contacto")
        self.gridLayout.addWidget(self.entry_email_contacto, 10, 2, 1, 1)
        self.entry_contacto = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_contacto.sizePolicy().hasHeightForWidth())
        self.entry_contacto.setSizePolicy(sizePolicy)
        self.entry_contacto.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_contacto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_contacto.setObjectName("entry_contacto")
        self.gridLayout.addWidget(self.entry_contacto, 8, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.aceptcancel.rejected.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.entry_empresa, self.entry_provincia)
        MainWindow.setTabOrder(self.entry_provincia, self.entry_localidad)
        MainWindow.setTabOrder(self.entry_localidad, self.entry_direccion)
        MainWindow.setTabOrder(self.entry_direccion, self.entry_cif)
        MainWindow.setTabOrder(self.entry_cif, self.entryTFN)
        MainWindow.setTabOrder(self.entryTFN, self.entry_email)
        MainWindow.setTabOrder(self.entry_email, self.entry_web)
        MainWindow.setTabOrder(self.entry_web, self.entry_contacto)
        MainWindow.setTabOrder(self.entry_contacto, self.entry_tfn_contacto)
        MainWindow.setTabOrder(self.entry_tfn_contacto, self.entry_email_contacto)
        MainWindow.setTabOrder(self.entry_email_contacto, self.textNOTAS)
        MainWindow.setTabOrder(self.textNOTAS, self.check_trailer)
        MainWindow.setTabOrder(self.check_trailer, self.check_camion)
        MainWindow.setTabOrder(self.check_camion, self.check_furgo)
        MainWindow.setTabOrder(self.check_furgo, self.check_runner)
        MainWindow.setTabOrder(self.check_runner, self.check_c_d)
        MainWindow.setTabOrder(self.check_c_d, self.check_rigging)
        MainWindow.setTabOrder(self.check_rigging, self.check_deco)
        MainWindow.setTabOrder(self.check_deco, self.check_generadores)
        MainWindow.setTabOrder(self.check_generadores, self.check_tradu)
        MainWindow.setTabOrder(self.check_tradu, self.check_catering)
        MainWindow.setTabOrder(self.check_catering, self.check_iluminacion)
        MainWindow.setTabOrder(self.check_iluminacion, self.check_sonido)
        MainWindow.setTabOrder(self.check_sonido, self.check_video)
        MainWindow.setTabOrder(self.check_video, self.check_mobiliario)
        MainWindow.setTabOrder(self.check_mobiliario, self.check_otros)
        MainWindow.setTabOrder(self.check_otros, self.entry_otros)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.servicios.setText(_translate("MainWindow", "Servicios"))
        self.check_trailer.setText(_translate("MainWindow", "Transporte Trailer"))
        self.check_camion.setText(_translate("MainWindow", "Transporte Camión"))
        self.check_furgo.setText(_translate("MainWindow", "Transporte Furgoneta"))
        self.check_runner.setText(_translate("MainWindow", "Runner"))
        self.check_c_d.setText(_translate("MainWindow", "Carga/Descarga"))
        self.check_rigging.setText(_translate("MainWindow", "Rigging"))
        self.check_deco.setText(_translate("MainWindow", "Deco"))
        self.check_generadores.setText(_translate("MainWindow", "Generadores"))
        self.check_tradu.setText(_translate("MainWindow", "Cabinas Traducción"))
        self.check_catering.setText(_translate("MainWindow", "Catering"))
        self.check_iluminacion.setText(_translate("MainWindow", "Iluminación"))
        self.check_sonido.setText(_translate("MainWindow", "Sonido"))
        self.check_video.setText(_translate("MainWindow", "Video"))
        self.check_mobiliario.setText(_translate("MainWindow", "Mobiliario"))
        self.check_otros.setText(_translate("MainWindow", "Otros"))
        self.anadir_proveedor.setText(_translate("MainWindow", "Añadir Proveedor\n"
""))
        self.direccion.setText(_translate("MainWindow", "Dirección"))
        self.email.setText(_translate("MainWindow", "Email"))
        self.telefono.setText(_translate("MainWindow", "Teléfono"))
        self.email_2.setText(_translate("MainWindow", "Web"))
        self.contacto.setText(_translate("MainWindow", "Contacto"))
        self.cif.setText(_translate("MainWindow", "CIF"))
        self.empresa.setText(_translate("MainWindow", "Empresa"))
        self.provincia.setText(_translate("MainWindow", "Provincia"))
        self.provincia_2.setText(_translate("MainWindow", "Localidad"))
        self.email_contacto.setText(_translate("MainWindow", "Email de contacto"))
        self.notas.setText(_translate("MainWindow", "Notas"))
        self.tfn_contacto.setText(_translate("MainWindow", "Teléfono de contacto"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = AnadirProveedor_Ui()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

