# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anadirproveedor_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class AnadirProveedor_Ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1201, 753)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelSubtitle1 = QtWidgets.QLabel(Form)
        self.labelSubtitle1.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.labelSubtitle1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSubtitle1.setObjectName("labelSubtitle1")
        self.gridLayout_2.addWidget(self.labelSubtitle1, 3, 1, 1, 1)
        self.labelSubtitle2 = QtWidgets.QLabel(Form)
        self.labelSubtitle2.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.labelSubtitle2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSubtitle2.setObjectName("labelSubtitle2")
        self.gridLayout_2.addWidget(self.labelSubtitle2, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem, 6, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 8, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 5, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem4, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 5, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.telefono = QtWidgets.QLabel(Form)
        self.telefono.setMinimumSize(QtCore.QSize(150, 0))
        self.telefono.setObjectName("telefono")
        self.gridLayout.addWidget(self.telefono, 6, 0, 1, 2)
        self.email_2 = QtWidgets.QLabel(Form)
        self.email_2.setMinimumSize(QtCore.QSize(150, 0))
        self.email_2.setObjectName("email_2")
        self.gridLayout.addWidget(self.email_2, 8, 0, 1, 1)
        self.empresa = QtWidgets.QLabel(Form)
        self.empresa.setMinimumSize(QtCore.QSize(150, 0))
        self.empresa.setObjectName("empresa")
        self.gridLayout.addWidget(self.empresa, 1, 0, 1, 2)
        self.entry_email = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_email.sizePolicy().hasHeightForWidth())
        self.entry_email.setSizePolicy(sizePolicy)
        self.entry_email.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_email.setObjectName("entry_email")
        self.gridLayout.addWidget(self.entry_email, 7, 2, 1, 1)
        self.entry_cif = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_cif.sizePolicy().hasHeightForWidth())
        self.entry_cif.setSizePolicy(sizePolicy)
        self.entry_cif.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_cif.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_cif.setObjectName("entry_cif")
        self.gridLayout.addWidget(self.entry_cif, 5, 2, 1, 1)
        self.email = QtWidgets.QLabel(Form)
        self.email.setMinimumSize(QtCore.QSize(150, 0))
        self.email.setObjectName("email")
        self.gridLayout.addWidget(self.email, 7, 0, 1, 2)
        self.cif = QtWidgets.QLabel(Form)
        self.cif.setMinimumSize(QtCore.QSize(150, 0))
        self.cif.setObjectName("cif")
        self.gridLayout.addWidget(self.cif, 5, 0, 1, 2)
        self.provincia = QtWidgets.QLabel(Form)
        self.provincia.setMinimumSize(QtCore.QSize(150, 0))
        self.provincia.setObjectName("provincia")
        self.gridLayout.addWidget(self.provincia, 2, 0, 1, 2)
        self.entry_empresa = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_empresa.sizePolicy().hasHeightForWidth())
        self.entry_empresa.setSizePolicy(sizePolicy)
        self.entry_empresa.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_empresa.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_empresa.setObjectName("entry_empresa")
        self.gridLayout.addWidget(self.entry_empresa, 1, 2, 1, 1)
        self.direccion = QtWidgets.QLabel(Form)
        self.direccion.setMinimumSize(QtCore.QSize(150, 0))
        self.direccion.setObjectName("direccion")
        self.gridLayout.addWidget(self.direccion, 4, 0, 1, 2)
        self.entry_provincia = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_provincia.sizePolicy().hasHeightForWidth())
        self.entry_provincia.setSizePolicy(sizePolicy)
        self.entry_provincia.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_provincia.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_provincia.setObjectName("entry_provincia")
        self.gridLayout.addWidget(self.entry_provincia, 2, 2, 1, 1)
        self.provincia_2 = QtWidgets.QLabel(Form)
        self.provincia_2.setMinimumSize(QtCore.QSize(150, 0))
        self.provincia_2.setObjectName("provincia_2")
        self.gridLayout.addWidget(self.provincia_2, 3, 0, 1, 2)
        self.entry_web = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_web.sizePolicy().hasHeightForWidth())
        self.entry_web.setSizePolicy(sizePolicy)
        self.entry_web.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_web.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_web.setObjectName("entry_web")
        self.gridLayout.addWidget(self.entry_web, 8, 2, 1, 1)
        self.entryTFN = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entryTFN.sizePolicy().hasHeightForWidth())
        self.entryTFN.setSizePolicy(sizePolicy)
        self.entryTFN.setMinimumSize(QtCore.QSize(180, 0))
        self.entryTFN.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entryTFN.setObjectName("entryTFN")
        self.gridLayout.addWidget(self.entryTFN, 6, 2, 1, 1)
        self.entry_localidad = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_localidad.sizePolicy().hasHeightForWidth())
        self.entry_localidad.setSizePolicy(sizePolicy)
        self.entry_localidad.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_localidad.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_localidad.setText("")
        self.entry_localidad.setObjectName("entry_localidad")
        self.gridLayout.addWidget(self.entry_localidad, 3, 2, 1, 1)
        self.entry_direccion = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_direccion.sizePolicy().hasHeightForWidth())
        self.entry_direccion.setSizePolicy(sizePolicy)
        self.entry_direccion.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_direccion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_direccion.setObjectName("entry_direccion")
        self.gridLayout.addWidget(self.entry_direccion, 4, 2, 1, 1)
        self.contacto = QtWidgets.QLabel(Form)
        self.contacto.setMinimumSize(QtCore.QSize(150, 0))
        self.contacto.setObjectName("contacto")
        self.gridLayout.addWidget(self.contacto, 9, 0, 1, 2)
        self.tfn_contacto = QtWidgets.QLabel(Form)
        self.tfn_contacto.setMinimumSize(QtCore.QSize(150, 0))
        self.tfn_contacto.setObjectName("tfn_contacto")
        self.gridLayout.addWidget(self.tfn_contacto, 10, 0, 1, 2)
        self.entry_contacto = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_contacto.sizePolicy().hasHeightForWidth())
        self.entry_contacto.setSizePolicy(sizePolicy)
        self.entry_contacto.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_contacto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_contacto.setObjectName("entry_contacto")
        self.gridLayout.addWidget(self.entry_contacto, 9, 2, 1, 1)
        self.textNOTAS = QtWidgets.QTextEdit(Form)
        self.textNOTAS.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textNOTAS.setObjectName("textNOTAS")
        self.gridLayout.addWidget(self.textNOTAS, 12, 1, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.notas = QtWidgets.QLabel(Form)
        self.notas.setMinimumSize(QtCore.QSize(150, 0))
        self.notas.setObjectName("notas")
        self.verticalLayout.addWidget(self.notas)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.gridLayout.addLayout(self.verticalLayout, 12, 0, 1, 1)
        self.email_contacto = QtWidgets.QLabel(Form)
        self.email_contacto.setMinimumSize(QtCore.QSize(150, 0))
        self.email_contacto.setObjectName("email_contacto")
        self.gridLayout.addWidget(self.email_contacto, 11, 0, 1, 2)
        self.entry_tfn_contacto = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_tfn_contacto.sizePolicy().hasHeightForWidth())
        self.entry_tfn_contacto.setSizePolicy(sizePolicy)
        self.entry_tfn_contacto.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_tfn_contacto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_tfn_contacto.setObjectName("entry_tfn_contacto")
        self.gridLayout.addWidget(self.entry_tfn_contacto, 10, 2, 1, 1)
        self.entry_email_contacto = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_email_contacto.sizePolicy().hasHeightForWidth())
        self.entry_email_contacto.setSizePolicy(sizePolicy)
        self.entry_email_contacto.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_email_contacto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_email_contacto.setObjectName("entry_email_contacto")
        self.gridLayout.addWidget(self.entry_email_contacto, 11, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 3, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 5, 1, 3, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.buttonAceptar = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAceptar.sizePolicy().hasHeightForWidth())
        self.buttonAceptar.setSizePolicy(sizePolicy)
        self.buttonAceptar.setMinimumSize(QtCore.QSize(93, 28))
        self.buttonAceptar.setObjectName("buttonAceptar")
        self.horizontalLayout.addWidget(self.buttonAceptar)
        self.buttonCancelar = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCancelar.sizePolicy().hasHeightForWidth())
        self.buttonCancelar.setSizePolicy(sizePolicy)
        self.buttonCancelar.setMinimumSize(QtCore.QSize(93, 28))
        self.buttonCancelar.setObjectName("buttonCancelar")
        self.horizontalLayout.addWidget(self.buttonCancelar)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.gridLayout_2.addLayout(self.horizontalLayout, 7, 2, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.check_trailer = QtWidgets.QCheckBox(Form)
        self.check_trailer.setObjectName("check_trailer")
        self.verticalLayout_2.addWidget(self.check_trailer)
        self.check_camion = QtWidgets.QCheckBox(Form)
        self.check_camion.setObjectName("check_camion")
        self.verticalLayout_2.addWidget(self.check_camion)
        self.check_furgo = QtWidgets.QCheckBox(Form)
        self.check_furgo.setObjectName("check_furgo")
        self.verticalLayout_2.addWidget(self.check_furgo)
        self.check_runner = QtWidgets.QCheckBox(Form)
        self.check_runner.setObjectName("check_runner")
        self.verticalLayout_2.addWidget(self.check_runner)
        self.check_c_d = QtWidgets.QCheckBox(Form)
        self.check_c_d.setObjectName("check_c_d")
        self.verticalLayout_2.addWidget(self.check_c_d)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.check_rigging = QtWidgets.QCheckBox(Form)
        self.check_rigging.setObjectName("check_rigging")
        self.verticalLayout_7.addWidget(self.check_rigging)
        self.check_deco = QtWidgets.QCheckBox(Form)
        self.check_deco.setObjectName("check_deco")
        self.verticalLayout_7.addWidget(self.check_deco)
        self.check_generadores = QtWidgets.QCheckBox(Form)
        self.check_generadores.setObjectName("check_generadores")
        self.verticalLayout_7.addWidget(self.check_generadores)
        self.check_tradu = QtWidgets.QCheckBox(Form)
        self.check_tradu.setObjectName("check_tradu")
        self.verticalLayout_7.addWidget(self.check_tradu)
        self.check_catering = QtWidgets.QCheckBox(Form)
        self.check_catering.setObjectName("check_catering")
        self.verticalLayout_7.addWidget(self.check_catering)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.check_iluminacion = QtWidgets.QCheckBox(Form)
        self.check_iluminacion.setObjectName("check_iluminacion")
        self.verticalLayout_8.addWidget(self.check_iluminacion)
        self.check_sonido = QtWidgets.QCheckBox(Form)
        self.check_sonido.setObjectName("check_sonido")
        self.verticalLayout_8.addWidget(self.check_sonido)
        self.check_video = QtWidgets.QCheckBox(Form)
        self.check_video.setObjectName("check_video")
        self.verticalLayout_8.addWidget(self.check_video)
        self.check_mobiliario = QtWidgets.QCheckBox(Form)
        self.check_mobiliario.setObjectName("check_mobiliario")
        self.verticalLayout_8.addWidget(self.check_mobiliario)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.check_otros = QtWidgets.QCheckBox(Form)
        self.check_otros.setObjectName("check_otros")
        self.horizontalLayout_2.addWidget(self.check_otros)
        self.entry_otros = QtWidgets.QLineEdit(Form)
        self.entry_otros.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_otros.setClearButtonEnabled(False)
        self.entry_otros.setObjectName("entry_otros")
        self.horizontalLayout_2.addWidget(self.entry_otros)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 5, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem10, 4, 2, 1, 1)
        self.labelTitle = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle.sizePolicy().hasHeightForWidth())
        self.labelTitle.setSizePolicy(sizePolicy)
        self.labelTitle.setMinimumSize(QtCore.QSize(200, 0))
        self.labelTitle.setMaximumSize(QtCore.QSize(16777215, 28))
        self.labelTitle.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.labelTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.gridLayout_2.addWidget(self.labelTitle, 1, 1, 1, 2)

        self.retranslateUi(Form)
        self.buttonCancelar.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelSubtitle1.setText(_translate("Form", "Datos"))
        self.labelSubtitle2.setText(_translate("Form", "Servicios"))
        self.telefono.setText(_translate("Form", "Teléfono"))
        self.email_2.setText(_translate("Form", "Web"))
        self.empresa.setText(_translate("Form", "Empresa"))
        self.email.setText(_translate("Form", "Email"))
        self.cif.setText(_translate("Form", "CIF"))
        self.provincia.setText(_translate("Form", "Provincia"))
        self.direccion.setText(_translate("Form", "Dirección"))
        self.provincia_2.setText(_translate("Form", "Localidad"))
        self.contacto.setText(_translate("Form", "Contacto"))
        self.tfn_contacto.setText(_translate("Form", "Teléfono de contacto"))
        self.notas.setText(_translate("Form", "Notas"))
        self.email_contacto.setText(_translate("Form", "Email de contacto"))
        self.buttonAceptar.setText(_translate("Form", "Aceptar"))
        self.buttonCancelar.setText(_translate("Form", "Cancelar"))
        self.check_trailer.setText(_translate("Form", "Transporte Trailer"))
        self.check_camion.setText(_translate("Form", "Transporte Camión"))
        self.check_furgo.setText(_translate("Form", "Transporte Furgoneta"))
        self.check_runner.setText(_translate("Form", "Runner"))
        self.check_c_d.setText(_translate("Form", "Carga/Descarga"))
        self.check_rigging.setText(_translate("Form", "Rigging"))
        self.check_deco.setText(_translate("Form", "Deco"))
        self.check_generadores.setText(_translate("Form", "Generadores"))
        self.check_tradu.setText(_translate("Form", "Cabinas Traducción"))
        self.check_catering.setText(_translate("Form", "Catering"))
        self.check_iluminacion.setText(_translate("Form", "Iluminación"))
        self.check_sonido.setText(_translate("Form", "Sonido"))
        self.check_video.setText(_translate("Form", "Video"))
        self.check_mobiliario.setText(_translate("Form", "Mobiliario"))
        self.check_otros.setText(_translate("Form", "Otros"))
        self.labelTitle.setText(_translate("Form", "Añadir Proveedor\n"
""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = AnadirProveedor_Ui()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

