# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anadirproveedor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class AnadirProveedor_Ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 563)
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.aceptcancel = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.aceptcancel.setGeometry(QtCore.QRect(590, 310, 193, 28))
        self.aceptcancel.setStyleSheet("background-color: rgb(140, 140, 140);")
        self.aceptcancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.aceptcancel.setObjectName("aceptcancel")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 20, 391, 461))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.anadir_proveedor = QtWidgets.QLabel(self.layoutWidget)
        self.anadir_proveedor.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.anadir_proveedor.setObjectName("anadir_proveedor")
        self.verticalLayout_6.addWidget(self.anadir_proveedor)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.id = QtWidgets.QLabel(self.layoutWidget)
        self.id.setObjectName("id")
        self.verticalLayout_4.addWidget(self.id)
        self.empresa = QtWidgets.QLabel(self.layoutWidget)
        self.empresa.setObjectName("empresa")
        self.verticalLayout_4.addWidget(self.empresa)
        self.ubicacion = QtWidgets.QLabel(self.layoutWidget)
        self.ubicacion.setObjectName("ubicacion")
        self.verticalLayout_4.addWidget(self.ubicacion)
        self.cif = QtWidgets.QLabel(self.layoutWidget)
        self.cif.setObjectName("cif")
        self.verticalLayout_4.addWidget(self.cif)
        self.telefono = QtWidgets.QLabel(self.layoutWidget)
        self.telefono.setObjectName("telefono")
        self.verticalLayout_4.addWidget(self.telefono)
        self.email = QtWidgets.QLabel(self.layoutWidget)
        self.email.setObjectName("email")
        self.verticalLayout_4.addWidget(self.email)
        self.contacto = QtWidgets.QLabel(self.layoutWidget)
        self.contacto.setObjectName("contacto")
        self.verticalLayout_4.addWidget(self.contacto)
        self.tfn_contacto = QtWidgets.QLabel(self.layoutWidget)
        self.tfn_contacto.setObjectName("tfn_contacto")
        self.verticalLayout_4.addWidget(self.tfn_contacto)
        self.email_contacto = QtWidgets.QLabel(self.layoutWidget)
        self.email_contacto.setObjectName("email_contacto")
        self.verticalLayout_4.addWidget(self.email_contacto)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.entry_id = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_id.sizePolicy().hasHeightForWidth())
        self.entry_id.setSizePolicy(sizePolicy)
        self.entry_id.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_id.setObjectName("entry_id")
        self.verticalLayout_3.addWidget(self.entry_id)
        self.entry_empresa = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_empresa.sizePolicy().hasHeightForWidth())
        self.entry_empresa.setSizePolicy(sizePolicy)
        self.entry_empresa.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_empresa.setObjectName("entry_empresa")
        self.verticalLayout_3.addWidget(self.entry_empresa)
        self.entry_ubicacion = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_ubicacion.sizePolicy().hasHeightForWidth())
        self.entry_ubicacion.setSizePolicy(sizePolicy)
        self.entry_ubicacion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_ubicacion.setObjectName("entry_ubicacion")
        self.verticalLayout_3.addWidget(self.entry_ubicacion)
        self.entry_cif = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_cif.sizePolicy().hasHeightForWidth())
        self.entry_cif.setSizePolicy(sizePolicy)
        self.entry_cif.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_cif.setObjectName("entry_cif")
        self.verticalLayout_3.addWidget(self.entry_cif)
        self.entryTFN = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entryTFN.sizePolicy().hasHeightForWidth())
        self.entryTFN.setSizePolicy(sizePolicy)
        self.entryTFN.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entryTFN.setObjectName("entryTFN")
        self.verticalLayout_3.addWidget(self.entryTFN)
        self.entry_email = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_email.sizePolicy().hasHeightForWidth())
        self.entry_email.setSizePolicy(sizePolicy)
        self.entry_email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_email.setObjectName("entry_email")
        self.verticalLayout_3.addWidget(self.entry_email)
        self.entry_contacto = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_contacto.sizePolicy().hasHeightForWidth())
        self.entry_contacto.setSizePolicy(sizePolicy)
        self.entry_contacto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_contacto.setObjectName("entry_contacto")
        self.verticalLayout_3.addWidget(self.entry_contacto)
        self.entry_tfn_contacto = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_tfn_contacto.sizePolicy().hasHeightForWidth())
        self.entry_tfn_contacto.setSizePolicy(sizePolicy)
        self.entry_tfn_contacto.setMinimumSize(QtCore.QSize(122, 0))
        self.entry_tfn_contacto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_tfn_contacto.setObjectName("entry_tfn_contacto")
        self.verticalLayout_3.addWidget(self.entry_tfn_contacto)
        self.entry_email_contacto = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_email_contacto.sizePolicy().hasHeightForWidth())
        self.entry_email_contacto.setSizePolicy(sizePolicy)
        self.entry_email_contacto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_email_contacto.setObjectName("entry_email_contacto")
        self.verticalLayout_3.addWidget(self.entry_email_contacto)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.notas = QtWidgets.QLabel(self.layoutWidget)
        self.notas.setObjectName("notas")
        self.verticalLayout.addWidget(self.notas)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.textNOTAS = QtWidgets.QTextEdit(self.layoutWidget)
        self.textNOTAS.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textNOTAS.setObjectName("textNOTAS")
        self.horizontalLayout_11.addWidget(self.textNOTAS)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(450, 90, 519, 166))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.servicios = QtWidgets.QLabel(self.layoutWidget1)
        self.servicios.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.servicios.setObjectName("servicios")
        self.verticalLayout_9.addWidget(self.servicios)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.check_trailer = QtWidgets.QCheckBox(self.layoutWidget1)
        self.check_trailer.setObjectName("check_trailer")
        self.verticalLayout_2.addWidget(self.check_trailer)
        self.check_camion = QtWidgets.QCheckBox(self.layoutWidget1)
        self.check_camion.setObjectName("check_camion")
        self.verticalLayout_2.addWidget(self.check_camion)
        self.check_furgo = QtWidgets.QCheckBox(self.layoutWidget1)
        self.check_furgo.setObjectName("check_furgo")
        self.verticalLayout_2.addWidget(self.check_furgo)
        self.check_runner = QtWidgets.QCheckBox(self.layoutWidget1)
        self.check_runner.setObjectName("check_runner")
        self.verticalLayout_2.addWidget(self.check_runner)
        self.check_c_d = QtWidgets.QCheckBox(self.layoutWidget1)
        self.check_c_d.setObjectName("check_c_d")
        self.verticalLayout_2.addWidget(self.check_c_d)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.check_rigging = QtWidgets.QCheckBox(self.layoutWidget1)
        self.check_rigging.setObjectName("check_rigging")
        self.verticalLayout_7.addWidget(self.check_rigging)
        self.check_deco = QtWidgets.QCheckBox(self.layoutWidget1)
        self.check_deco.setObjectName("check_deco")
        self.verticalLayout_7.addWidget(self.check_deco)
        self.check_generadores = QtWidgets.QCheckBox(self.layoutWidget1)
        self.check_generadores.setObjectName("check_generadores")
        self.verticalLayout_7.addWidget(self.check_generadores)
        self.check_tradu = QtWidgets.QCheckBox(self.layoutWidget1)
        self.check_tradu.setObjectName("check_tradu")
        self.verticalLayout_7.addWidget(self.check_tradu)
        self.check_catering = QtWidgets.QCheckBox(self.layoutWidget1)
        self.check_catering.setObjectName("check_catering")
        self.verticalLayout_7.addWidget(self.check_catering)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.check_iluminacion = QtWidgets.QCheckBox(self.layoutWidget1)
        self.check_iluminacion.setObjectName("check_iluminacion")
        self.verticalLayout_8.addWidget(self.check_iluminacion)
        self.check_sonido = QtWidgets.QCheckBox(self.layoutWidget1)
        self.check_sonido.setObjectName("check_sonido")
        self.verticalLayout_8.addWidget(self.check_sonido)
        self.check_video = QtWidgets.QCheckBox(self.layoutWidget1)
        self.check_video.setObjectName("check_video")
        self.verticalLayout_8.addWidget(self.check_video)
        self.check_mobiliario = QtWidgets.QCheckBox(self.layoutWidget1)
        self.check_mobiliario.setObjectName("check_mobiliario")
        self.verticalLayout_8.addWidget(self.check_mobiliario)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.check_otros = QtWidgets.QCheckBox(self.layoutWidget1)
        self.check_otros.setObjectName("check_otros")
        self.horizontalLayout_2.addWidget(self.check_otros)
        self.entry_otros = QtWidgets.QLineEdit(self.layoutWidget1)
        self.entry_otros.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_otros.setObjectName("entry_otros")
        self.horizontalLayout_2.addWidget(self.entry_otros)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.aceptcancel.rejected.connect(MainWindow.close)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.anadir_proveedor.setText(_translate("MainWindow", "Añadir Proveedor\n"
""))
        self.id.setText(_translate("MainWindow", "ID"))
        self.empresa.setText(_translate("MainWindow", "Empresa"))
        self.ubicacion.setText(_translate("MainWindow", "Ubicación"))
        self.cif.setText(_translate("MainWindow", "CIF"))
        self.telefono.setText(_translate("MainWindow", "Teléfono"))
        self.email.setText(_translate("MainWindow", "Email"))
        self.contacto.setText(_translate("MainWindow", "Contacto"))
        self.tfn_contacto.setText(_translate("MainWindow", "Teléfono de contacto"))
        self.email_contacto.setText(_translate("MainWindow", "Email de contacto"))
        self.notas.setText(_translate("MainWindow", "Notas"))
        self.servicios.setText(_translate("MainWindow", "Servicios"))
        self.check_trailer.setText(_translate("MainWindow", "Transporte Trailer"))
        self.check_camion.setText(_translate("MainWindow", "Transporte Camión"))
        self.check_furgo.setText(_translate("MainWindow", "Transporte Furgoneta"))
        self.check_runner.setText(_translate("MainWindow", "Runner"))
        self.check_c_d.setText(_translate("MainWindow", "Carga/Descarga"))
        self.check_rigging.setText(_translate("MainWindow", "Rigging"))
        self.check_deco.setText(_translate("MainWindow", "Deco"))
        self.check_generadores.setText(_translate("MainWindow", "Generadores"))
        self.check_tradu.setText(_translate("MainWindow", "Cabinas Traducción"))
        self.check_catering.setText(_translate("MainWindow", "Catering"))
        self.check_iluminacion.setText(_translate("MainWindow", "Iluminación"))
        self.check_sonido.setText(_translate("MainWindow", "Sonido"))
        self.check_video.setText(_translate("MainWindow", "Video"))
        self.check_mobiliario.setText(_translate("MainWindow", "Mobiliario"))
        self.check_otros.setText(_translate("MainWindow", "Otros"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = AnadirProveedor_Ui()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

