# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientes_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Clientes_Ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1316, 753)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle.sizePolicy().hasHeightForWidth())
        self.labelTitle.setSizePolicy(sizePolicy)
        self.labelTitle.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableClientes = QtWidgets.QTableWidget(Form)
        self.tableClientes.setObjectName("tableClientes")
        self.tableClientes.setColumnCount(14)
        self.tableClientes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(13, item)
        self.horizontalLayout_2.addWidget(self.tableClientes)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.inputNombre = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNombre.sizePolicy().hasHeightForWidth())
        self.inputNombre.setSizePolicy(sizePolicy)
        self.inputNombre.setMinimumSize(QtCore.QSize(190, 0))
        self.inputNombre.setObjectName("inputNombre")
        self.gridLayout.addWidget(self.inputNombre, 0, 2, 1, 1)
        self.inputPais = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputPais.sizePolicy().hasHeightForWidth())
        self.inputPais.setSizePolicy(sizePolicy)
        self.inputPais.setMinimumSize(QtCore.QSize(190, 0))
        self.inputPais.setObjectName("inputPais")
        self.gridLayout.addWidget(self.inputPais, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 3, 1, 1)
        self.inputWeb = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputWeb.sizePolicy().hasHeightForWidth())
        self.inputWeb.setSizePolicy(sizePolicy)
        self.inputWeb.setMinimumSize(QtCore.QSize(190, 0))
        self.inputWeb.setObjectName("inputWeb")
        self.gridLayout.addWidget(self.inputWeb, 2, 5, 1, 1)
        self.labelLocalidad = QtWidgets.QLabel(Form)
        self.labelLocalidad.setObjectName("labelLocalidad")
        self.gridLayout.addWidget(self.labelLocalidad, 3, 0, 1, 1)
        self.inputLocalidad = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputLocalidad.sizePolicy().hasHeightForWidth())
        self.inputLocalidad.setSizePolicy(sizePolicy)
        self.inputLocalidad.setMinimumSize(QtCore.QSize(190, 0))
        self.inputLocalidad.setObjectName("inputLocalidad")
        self.gridLayout.addWidget(self.inputLocalidad, 3, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 3, 1, 1)
        self.labelContacto = QtWidgets.QLabel(Form)
        self.labelContacto.setObjectName("labelContacto")
        self.gridLayout.addWidget(self.labelContacto, 3, 4, 1, 1)
        self.labelEmail = QtWidgets.QLabel(Form)
        self.labelEmail.setObjectName("labelEmail")
        self.gridLayout.addWidget(self.labelEmail, 1, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 12, 2, 1, 1)
        self.labelNombre = QtWidgets.QLabel(Form)
        self.labelNombre.setObjectName("labelNombre")
        self.gridLayout.addWidget(self.labelNombre, 0, 0, 1, 2)
        self.labelTelefono = QtWidgets.QLabel(Form)
        self.labelTelefono.setObjectName("labelTelefono")
        self.gridLayout.addWidget(self.labelTelefono, 0, 4, 1, 1)
        self.inputTelefono = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputTelefono.sizePolicy().hasHeightForWidth())
        self.inputTelefono.setSizePolicy(sizePolicy)
        self.inputTelefono.setMinimumSize(QtCore.QSize(190, 0))
        self.inputTelefono.setObjectName("inputTelefono")
        self.gridLayout.addWidget(self.inputTelefono, 0, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 3, 1, 1)
        self.labelPais = QtWidgets.QLabel(Form)
        self.labelPais.setObjectName("labelPais")
        self.gridLayout.addWidget(self.labelPais, 1, 0, 1, 2)
        self.inputEmail = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputEmail.sizePolicy().hasHeightForWidth())
        self.inputEmail.setSizePolicy(sizePolicy)
        self.inputEmail.setMinimumSize(QtCore.QSize(190, 0))
        self.inputEmail.setObjectName("inputEmail")
        self.gridLayout.addWidget(self.inputEmail, 1, 5, 1, 1)
        self.labelProvincia = QtWidgets.QLabel(Form)
        self.labelProvincia.setObjectName("labelProvincia")
        self.gridLayout.addWidget(self.labelProvincia, 2, 0, 1, 2)
        self.inputProvincia = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputProvincia.sizePolicy().hasHeightForWidth())
        self.inputProvincia.setSizePolicy(sizePolicy)
        self.inputProvincia.setMinimumSize(QtCore.QSize(190, 0))
        self.inputProvincia.setObjectName("inputProvincia")
        self.gridLayout.addWidget(self.inputProvincia, 2, 2, 1, 1)
        self.labelWeb = QtWidgets.QLabel(Form)
        self.labelWeb.setObjectName("labelWeb")
        self.gridLayout.addWidget(self.labelWeb, 2, 4, 1, 1)
        self.inputContacto = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputContacto.sizePolicy().hasHeightForWidth())
        self.inputContacto.setSizePolicy(sizePolicy)
        self.inputContacto.setMinimumSize(QtCore.QSize(190, 0))
        self.inputContacto.setObjectName("inputContacto")
        self.gridLayout.addWidget(self.inputContacto, 3, 5, 1, 1)
        self.labelTfnCont = QtWidgets.QLabel(Form)
        self.labelTfnCont.setObjectName("labelTfnCont")
        self.gridLayout.addWidget(self.labelTfnCont, 4, 4, 1, 1)
        self.inputTfnCont = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputTfnCont.sizePolicy().hasHeightForWidth())
        self.inputTfnCont.setSizePolicy(sizePolicy)
        self.inputTfnCont.setMinimumSize(QtCore.QSize(190, 0))
        self.inputTfnCont.setObjectName("inputTfnCont")
        self.gridLayout.addWidget(self.inputTfnCont, 4, 5, 1, 1)
        self.inputDireccion = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputDireccion.sizePolicy().hasHeightForWidth())
        self.inputDireccion.setSizePolicy(sizePolicy)
        self.inputDireccion.setMinimumSize(QtCore.QSize(190, 0))
        self.inputDireccion.setObjectName("inputDireccion")
        self.gridLayout.addWidget(self.inputDireccion, 4, 2, 1, 1)
        self.labelCif = QtWidgets.QLabel(Form)
        self.labelCif.setObjectName("labelCif")
        self.gridLayout.addWidget(self.labelCif, 5, 0, 1, 1)
        self.inputCif = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputCif.sizePolicy().hasHeightForWidth())
        self.inputCif.setSizePolicy(sizePolicy)
        self.inputCif.setMinimumSize(QtCore.QSize(190, 0))
        self.inputCif.setObjectName("inputCif")
        self.gridLayout.addWidget(self.inputCif, 5, 2, 1, 1)
        self.labelNotas = QtWidgets.QLabel(Form)
        self.labelNotas.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelNotas.setObjectName("labelNotas")
        self.gridLayout.addWidget(self.labelNotas, 6, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 4, 3, 1, 1)
        self.labelEmailCont = QtWidgets.QLabel(Form)
        self.labelEmailCont.setObjectName("labelEmailCont")
        self.gridLayout.addWidget(self.labelEmailCont, 5, 4, 1, 1)
        self.labelDireccion = QtWidgets.QLabel(Form)
        self.labelDireccion.setObjectName("labelDireccion")
        self.gridLayout.addWidget(self.labelDireccion, 4, 0, 1, 1)
        self.inputNotas = QtWidgets.QPlainTextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNotas.sizePolicy().hasHeightForWidth())
        self.inputNotas.setSizePolicy(sizePolicy)
        self.inputNotas.setPlainText("")
        self.inputNotas.setObjectName("inputNotas")
        self.gridLayout.addWidget(self.inputNotas, 6, 2, 2, 4)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem8, 8, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout.addLayout(self.horizontalLayout, 9, 2, 1, 1)
        self.inputEmailCont = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputEmailCont.sizePolicy().hasHeightForWidth())
        self.inputEmailCont.setSizePolicy(sizePolicy)
        self.inputEmailCont.setMinimumSize(QtCore.QSize(190, 0))
        self.inputEmailCont.setObjectName("inputEmailCont")
        self.gridLayout.addWidget(self.inputEmailCont, 5, 5, 1, 1)
        self.buttonAnadir = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAnadir.sizePolicy().hasHeightForWidth())
        self.buttonAnadir.setSizePolicy(sizePolicy)
        self.buttonAnadir.setMinimumSize(QtCore.QSize(100, 35))
        self.buttonAnadir.setObjectName("buttonAnadir")
        self.gridLayout.addWidget(self.buttonAnadir, 10, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonGuardar = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonGuardar.sizePolicy().hasHeightForWidth())
        self.buttonGuardar.setSizePolicy(sizePolicy)
        self.buttonGuardar.setMinimumSize(QtCore.QSize(100, 35))
        self.buttonGuardar.setObjectName("buttonGuardar")
        self.horizontalLayout_3.addWidget(self.buttonGuardar)
        self.buttonEliminar = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonEliminar.sizePolicy().hasHeightForWidth())
        self.buttonEliminar.setSizePolicy(sizePolicy)
        self.buttonEliminar.setMinimumSize(QtCore.QSize(100, 35))
        self.buttonEliminar.setObjectName("buttonEliminar")
        self.horizontalLayout_3.addWidget(self.buttonEliminar)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.inputNombre, self.inputPais)
        Form.setTabOrder(self.inputPais, self.inputProvincia)
        Form.setTabOrder(self.inputProvincia, self.inputLocalidad)
        Form.setTabOrder(self.inputLocalidad, self.inputDireccion)
        Form.setTabOrder(self.inputDireccion, self.inputCif)
        Form.setTabOrder(self.inputCif, self.inputTelefono)
        Form.setTabOrder(self.inputTelefono, self.inputEmail)
        Form.setTabOrder(self.inputEmail, self.inputWeb)
        Form.setTabOrder(self.inputWeb, self.inputContacto)
        Form.setTabOrder(self.inputContacto, self.inputTfnCont)
        Form.setTabOrder(self.inputTfnCont, self.inputEmailCont)
        Form.setTabOrder(self.inputEmailCont, self.inputNotas)
        Form.setTabOrder(self.inputNotas, self.buttonAnadir)
        Form.setTabOrder(self.buttonAnadir, self.buttonGuardar)
        Form.setTabOrder(self.buttonGuardar, self.buttonEliminar)
        Form.setTabOrder(self.buttonEliminar, self.tableClientes)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Clientes"))
        self.labelTitle.setText(_translate("Form", "Clientes"))
        item = self.tableClientes.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Id Cliente"))
        item = self.tableClientes.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nombre"))
        item = self.tableClientes.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Pais"))
        item = self.tableClientes.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Provincia"))
        item = self.tableClientes.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Localidad"))
        item = self.tableClientes.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Dirección"))
        item = self.tableClientes.horizontalHeaderItem(6)
        item.setText(_translate("Form", "CIF"))
        item = self.tableClientes.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Teléfono"))
        item = self.tableClientes.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Email"))
        item = self.tableClientes.horizontalHeaderItem(9)
        item.setText(_translate("Form", "Web"))
        item = self.tableClientes.horizontalHeaderItem(10)
        item.setText(_translate("Form", "Contacto"))
        item = self.tableClientes.horizontalHeaderItem(11)
        item.setText(_translate("Form", "Tfn Contacto"))
        item = self.tableClientes.horizontalHeaderItem(12)
        item.setText(_translate("Form", "Email Contacto"))
        item = self.tableClientes.horizontalHeaderItem(13)
        item.setText(_translate("Form", "Notas"))
        self.labelLocalidad.setText(_translate("Form", "Localidad"))
        self.labelContacto.setText(_translate("Form", "Contacto"))
        self.labelEmail.setText(_translate("Form", "Email"))
        self.labelNombre.setText(_translate("Form", "Nombre"))
        self.labelTelefono.setText(_translate("Form", "Teléfono"))
        self.labelPais.setText(_translate("Form", "País"))
        self.labelProvincia.setText(_translate("Form", "Provincia"))
        self.labelWeb.setText(_translate("Form", "Web"))
        self.labelTfnCont.setText(_translate("Form", "Teléfono de contacto"))
        self.labelCif.setText(_translate("Form", "CIF"))
        self.labelNotas.setText(_translate("Form", "Notas"))
        self.labelEmailCont.setText(_translate("Form", "Email de contacto"))
        self.labelDireccion.setText(_translate("Form", "Dirección"))
        self.buttonAnadir.setText(_translate("Form", "Añadir"))
        self.buttonGuardar.setText(_translate("Form", "Guardar cambios"))
        self.buttonEliminar.setText(_translate("Form", "Eliminar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Clientes_Ui()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

