# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'consultaproveedor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class ConsultaProveedor_Ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1851, 900)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1471, 761))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_consulta = QtWidgets.QLabel(self.layoutWidget)
        self.label_consulta.setStyleSheet("\n"
"font: 75 20pt \"MS Shell Dlg 2\";")
        self.label_consulta.setObjectName("label_consulta")
        self.horizontalLayout_2.addWidget(self.label_consulta)
        spacerItem = QtWidgets.QSpacerItem(508, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(1500, 90, 271, 616))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.label_filtrar = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_filtrar.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_filtrar.setObjectName("label_filtrar")
        self.verticalLayout_5.addWidget(self.label_filtrar)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.check_all = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.check_all.setObjectName("check_all")
        self.gridLayout.addWidget(self.check_all, 8, 0, 1, 1)
        self.check_traduccion = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.check_traduccion.setObjectName("check_traduccion")
        self.gridLayout.addWidget(self.check_traduccion, 3, 1, 1, 1)
        self.check_sonido = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.check_sonido.setObjectName("check_sonido")
        self.gridLayout.addWidget(self.check_sonido, 1, 1, 1, 1)
        self.check_deco = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.check_deco.setObjectName("check_deco")
        self.gridLayout.addWidget(self.check_deco, 4, 0, 1, 1)
        self.check_catering = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.check_catering.setObjectName("check_catering")
        self.gridLayout.addWidget(self.check_catering, 4, 1, 1, 1)
        self.check_iluminacion = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.check_iluminacion.setObjectName("check_iluminacion")
        self.gridLayout.addWidget(self.check_iluminacion, 0, 1, 1, 1)
        self.check_video = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.check_video.setObjectName("check_video")
        self.gridLayout.addWidget(self.check_video, 2, 1, 1, 1)
        self.check_generadores = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.check_generadores.setObjectName("check_generadores")
        self.gridLayout.addWidget(self.check_generadores, 5, 0, 1, 1)
        self.check_mobiliario = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.check_mobiliario.setObjectName("check_mobiliario")
        self.gridLayout.addWidget(self.check_mobiliario, 5, 1, 1, 1)
        self.check_cd = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.check_cd.setObjectName("check_cd")
        self.gridLayout.addWidget(self.check_cd, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout.addLayout(self.horizontalLayout, 9, 1, 1, 1)
        self.check_transportes = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.check_transportes.setObjectName("check_transportes")
        self.gridLayout.addWidget(self.check_transportes, 0, 0, 1, 1)
        self.check_runner = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.check_runner.setObjectName("check_runner")
        self.gridLayout.addWidget(self.check_runner, 1, 0, 1, 1)
        self.check_rigging = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.check_rigging.setObjectName("check_rigging")
        self.gridLayout.addWidget(self.check_rigging, 3, 0, 1, 1)
        self.check_otros = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.check_otros.setObjectName("check_otros")
        self.gridLayout.addWidget(self.check_otros, 7, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 7, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 228, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_Add = QtWidgets.QPushButton(self.layoutWidget_2)
        self.button_Add.setObjectName("button_Add")
        self.horizontalLayout_4.addWidget(self.button_Add)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button_Edit = QtWidgets.QPushButton(self.layoutWidget_2)
        self.button_Edit.setObjectName("button_Edit")
        self.horizontalLayout_5.addWidget(self.button_Edit)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.button_Borrar = QtWidgets.QPushButton(self.layoutWidget_2)
        self.button_Borrar.setObjectName("button_Borrar")
        self.horizontalLayout_8.addWidget(self.button_Borrar)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.button_Close = QtWidgets.QPushButton(self.layoutWidget_2)
        self.button_Close.setObjectName("button_Close")
        self.horizontalLayout_6.addWidget(self.button_Close)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)

        self.retranslateUi(Dialog)
        self.check_otros.toggled['bool'].connect(self.lineEdit.setEnabled)
        self.check_all.clicked.connect(self.check_transportes.click)
        self.check_all.clicked.connect(self.check_runner.click)
        self.check_all.clicked.connect(self.check_cd.click)
        self.check_all.clicked.connect(self.check_rigging.click)
        self.check_all.clicked.connect(self.check_deco.click)
        self.check_all.clicked.connect(self.check_generadores.click)
        self.check_all.clicked.connect(self.check_otros.click)
        self.button_Close.clicked.connect(Dialog.close)
        self.check_all.clicked.connect(self.check_iluminacion.click)
        self.check_all.clicked.connect(self.check_sonido.click)
        self.check_all.clicked.connect(self.check_video.click)
        self.check_all.clicked.connect(self.check_traduccion.click)
        self.check_all.clicked.connect(self.check_catering.click)
        self.check_all.clicked.connect(self.check_mobiliario.click)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_consulta.setText(_translate("Dialog", "CONSULTA DE PROVEEDORES"))
        self.label_filtrar.setText(_translate("Dialog", "Filtrar"))
        self.check_all.setText(_translate("Dialog", "Select All"))
        self.check_traduccion.setText(_translate("Dialog", "Traducción"))
        self.check_sonido.setText(_translate("Dialog", "Sonido"))
        self.check_deco.setText(_translate("Dialog", "Deco"))
        self.check_catering.setText(_translate("Dialog", "Catering"))
        self.check_iluminacion.setText(_translate("Dialog", "Iluminación"))
        self.check_video.setText(_translate("Dialog", "Video"))
        self.check_generadores.setText(_translate("Dialog", "Generadores"))
        self.check_mobiliario.setText(_translate("Dialog", "Mobiliario"))
        self.check_cd.setText(_translate("Dialog", "C/D"))
        self.check_transportes.setText(_translate("Dialog", "Transportes"))
        self.check_runner.setText(_translate("Dialog", "Runner"))
        self.check_rigging.setText(_translate("Dialog", "Rigging"))
        self.check_otros.setText(_translate("Dialog", "Otros"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Servicio"))
        self.button_Add.setText(_translate("Dialog", "Añadir"))
        self.button_Edit.setText(_translate("Dialog", "Editar"))
        self.button_Borrar.setText(_translate("Dialog", "Borrar"))
        self.button_Close.setText(_translate("Dialog", "Cerrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = ConsultaProveedor_Ui()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

