# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crearevento_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class CrearEvento_Ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1234, 855)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1221, 841))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.pag_datos = QtWidgets.QWidget()
        self.pag_datos.setObjectName("pag_datos")
        self.datos = QtWidgets.QLabel(self.pag_datos)
        self.datos.setGeometry(QtCore.QRect(570, 90, 71, 16))
        self.datos.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.datos.setObjectName("datos")
        self.crear_evento = QtWidgets.QLabel(self.pag_datos)
        self.crear_evento.setGeometry(QtCore.QRect(520, 30, 161, 51))
        self.crear_evento.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.crear_evento.setObjectName("crear_evento")
        self.layoutWidget = QtWidgets.QWidget(self.pag_datos)
        self.layoutWidget.setGeometry(QtCore.QRect(520, 600, 195, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.buttonDatosNext = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDatosNext.sizePolicy().hasHeightForWidth())
        self.buttonDatosNext.setSizePolicy(sizePolicy)
        self.buttonDatosNext.setObjectName("buttonDatosNext")
        self.horizontalLayout_4.addWidget(self.buttonDatosNext)
        self.layoutWidget1 = QtWidgets.QWidget(self.pag_datos)
        self.layoutWidget1.setGeometry(QtCore.QRect(300, 140, 611, 432))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_4 = QtWidgets.QSplitter(self.layoutWidget1)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.notas = QtWidgets.QLabel(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notas.sizePolicy().hasHeightForWidth())
        self.notas.setSizePolicy(sizePolicy)
        self.notas.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.notas.setObjectName("notas")
        self.gridLayout.addWidget(self.splitter_4, 8, 0, 1, 1)
        self.combo_manager = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_manager.sizePolicy().hasHeightForWidth())
        self.combo_manager.setSizePolicy(sizePolicy)
        self.combo_manager.setObjectName("combo_manager")
        self.gridLayout.addWidget(self.combo_manager, 4, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 1)
        self.tfn_onsite = QtWidgets.QLabel(self.layoutWidget1)
        self.tfn_onsite.setObjectName("tfn_onsite")
        self.gridLayout.addWidget(self.tfn_onsite, 6, 0, 1, 1)
        self.entry_tfn_onsite = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_tfn_onsite.sizePolicy().hasHeightForWidth())
        self.entry_tfn_onsite.setSizePolicy(sizePolicy)
        self.entry_tfn_onsite.setObjectName("entry_tfn_onsite")
        self.gridLayout.addWidget(self.entry_tfn_onsite, 6, 2, 1, 1)
        self.email_onsite = QtWidgets.QLabel(self.layoutWidget1)
        self.email_onsite.setObjectName("email_onsite")
        self.gridLayout.addWidget(self.email_onsite, 7, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 7, 1, 1, 1)
        self.entry_email_onsite = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_email_onsite.sizePolicy().hasHeightForWidth())
        self.entry_email_onsite.setSizePolicy(sizePolicy)
        self.entry_email_onsite.setText("")
        self.entry_email_onsite.setObjectName("entry_email_onsite")
        self.gridLayout.addWidget(self.entry_email_onsite, 7, 2, 1, 1)
        self.entry_notas = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_notas.sizePolicy().hasHeightForWidth())
        self.entry_notas.setSizePolicy(sizePolicy)
        self.entry_notas.setObjectName("entry_notas")
        self.gridLayout.addWidget(self.entry_notas, 8, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 6, 1, 1, 1)
        self.cliente = QtWidgets.QLabel(self.layoutWidget1)
        self.cliente.setObjectName("cliente")
        self.gridLayout.addWidget(self.cliente, 2, 0, 1, 1)
        self.onsite = QtWidgets.QLabel(self.layoutWidget1)
        self.onsite.setObjectName("onsite")
        self.gridLayout.addWidget(self.onsite, 5, 0, 1, 1)
        self.entry_nombre = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_nombre.sizePolicy().hasHeightForWidth())
        self.entry_nombre.setSizePolicy(sizePolicy)
        self.entry_nombre.setText("")
        self.entry_nombre.setObjectName("entry_nombre")
        self.gridLayout.addWidget(self.entry_nombre, 1, 2, 1, 1)
        self.entry_cliente = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_cliente.sizePolicy().hasHeightForWidth())
        self.entry_cliente.setSizePolicy(sizePolicy)
        self.entry_cliente.setObjectName("entry_cliente")
        self.gridLayout.addWidget(self.entry_cliente, 2, 2, 1, 1)
        self.recinto = QtWidgets.QLabel(self.layoutWidget1)
        self.recinto.setObjectName("recinto")
        self.gridLayout.addWidget(self.recinto, 3, 0, 1, 1)
        self.manager = QtWidgets.QLabel(self.layoutWidget1)
        self.manager.setObjectName("manager")
        self.gridLayout.addWidget(self.manager, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 4, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_2.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 3, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 3, 2, 1, 1)
        self.entry_onsite = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_onsite.sizePolicy().hasHeightForWidth())
        self.entry_onsite.setSizePolicy(sizePolicy)
        self.entry_onsite.setText("")
        self.entry_onsite.setObjectName("entry_onsite")
        self.gridLayout.addWidget(self.entry_onsite, 5, 2, 1, 1)
        self.id = QtWidgets.QLabel(self.layoutWidget1)
        self.id.setObjectName("id")
        self.gridLayout.addWidget(self.id, 0, 0, 1, 1)
        self.nombre = QtWidgets.QLabel(self.layoutWidget1)
        self.nombre.setObjectName("nombre")
        self.gridLayout.addWidget(self.nombre, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 1, 1, 1)
        self.entry_id = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_id.sizePolicy().hasHeightForWidth())
        self.entry_id.setSizePolicy(sizePolicy)
        self.entry_id.setObjectName("entry_id")
        self.gridLayout.addWidget(self.entry_id, 0, 2, 1, 1)
        self.splitter_5 = QtWidgets.QSplitter(self.pag_datos)
        self.splitter_5.setGeometry(QtCore.QRect(920, 230, 41, 21))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.splitter_6 = QtWidgets.QSplitter(self.pag_datos)
        self.splitter_6.setGeometry(QtCore.QRect(920, 227, 31, 51))
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.buttonAddRecinto = QtWidgets.QPushButton(self.splitter_6)
        self.buttonAddRecinto.setObjectName("buttonAddRecinto")
        self.buttonAddManager = QtWidgets.QPushButton(self.splitter_6)
        self.buttonAddManager.setObjectName("buttonAddManager")
        self.tabWidget.addTab(self.pag_datos, "")
        self.pag_fechas = QtWidgets.QWidget()
        self.pag_fechas.setObjectName("pag_fechas")
        self.fechas_table = QtWidgets.QTableWidget(self.pag_fechas)
        self.fechas_table.setEnabled(True)
        self.fechas_table.setGeometry(QtCore.QRect(750, 100, 421, 441))
        self.fechas_table.setObjectName("fechas_table")
        self.fechas_table.setColumnCount(4)
        self.fechas_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fechas_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fechas_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fechas_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fechas_table.setHorizontalHeaderItem(3, item)
        self.label = QtWidgets.QLabel(self.pag_fechas)
        self.label.setGeometry(QtCore.QRect(10, 60, 181, 16))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.calendar = QtWidgets.QCalendarWidget(self.pag_fechas)
        self.calendar.setGeometry(QtCore.QRect(40, 100, 551, 441))
        self.calendar.setObjectName("calendar")
        self.frame = QtWidgets.QFrame(self.pag_fechas)
        self.frame.setGeometry(QtCore.QRect(610, 220, 120, 121))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.splitter_3 = QtWidgets.QSplitter(self.frame)
        self.splitter_3.setGeometry(QtCore.QRect(10, 10, 98, 101))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        self.label_2.setObjectName("label_2")
        self.time = QtWidgets.QTimeEdit(self.splitter_2)
        self.time.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.labelTarea = QtWidgets.QLabel(self.splitter)
        self.labelTarea.setObjectName("labelTarea")
        self.combo_tarea = QtWidgets.QComboBox(self.splitter)
        self.combo_tarea.setObjectName("combo_tarea")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.widget = QtWidgets.QWidget(self.pag_fechas)
        self.widget.setGeometry(QtCore.QRect(620, 440, 101, 100))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonAddDate = QtWidgets.QPushButton(self.widget)
        self.buttonAddDate.setEnabled(False)
        self.buttonAddDate.setObjectName("buttonAddDate")
        self.verticalLayout.addWidget(self.buttonAddDate)
        self.buttonDelDate = QtWidgets.QPushButton(self.widget)
        self.buttonDelDate.setEnabled(False)
        self.buttonDelDate.setObjectName("buttonDelDate")
        self.verticalLayout.addWidget(self.buttonDelDate)
        self.buttonFechaNext = QtWidgets.QPushButton(self.widget)
        self.buttonFechaNext.setObjectName("buttonFechaNext")
        self.verticalLayout.addWidget(self.buttonFechaNext)
        self.tabWidget.addTab(self.pag_fechas, "")
        self.pag_personal = QtWidgets.QWidget()
        self.pag_personal.setObjectName("pag_personal")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pag_personal)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.personal = QtWidgets.QLabel(self.pag_personal)
        self.personal.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.personal.setObjectName("personal")
        self.horizontalLayout_25.addWidget(self.personal)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem7)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.nombre_personal = QtWidgets.QLabel(self.pag_personal)
        self.nombre_personal.setObjectName("nombre_personal")
        self.horizontalLayout_24.addWidget(self.nombre_personal)
        self.entry_nombre_personal = QtWidgets.QLineEdit(self.pag_personal)
        self.entry_nombre_personal.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_nombre_personal.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.entry_nombre_personal.setObjectName("entry_nombre_personal")
        self.horizontalLayout_24.addWidget(self.entry_nombre_personal)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_24)
        self.buttonBuscarPers = QtWidgets.QPushButton(self.pag_personal)
        self.buttonBuscarPers.setObjectName("buttonBuscarPers")
        self.horizontalLayout_25.addWidget(self.buttonBuscarPers)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem8)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.filtrar_cargos = QtWidgets.QLabel(self.pag_personal)
        self.filtrar_cargos.setObjectName("filtrar_cargos")
        self.horizontalLayout_19.addWidget(self.filtrar_cargos)
        self.combo_filtrar_cargos = QtWidgets.QComboBox(self.pag_personal)
        self.combo_filtrar_cargos.setMinimumSize(QtCore.QSize(145, 0))
        self.combo_filtrar_cargos.setObjectName("combo_filtrar_cargos")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.horizontalLayout_19.addWidget(self.combo_filtrar_cargos)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_19)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.dia_personal = QtWidgets.QLabel(self.pag_personal)
        self.dia_personal.setObjectName("dia_personal")
        self.horizontalLayout_10.addWidget(self.dia_personal)
        self.combo_dia_personal = QtWidgets.QComboBox(self.pag_personal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_dia_personal.sizePolicy().hasHeightForWidth())
        self.combo_dia_personal.setSizePolicy(sizePolicy)
        self.combo_dia_personal.setMinimumSize(QtCore.QSize(145, 0))
        self.combo_dia_personal.setObjectName("combo_dia_personal")
        self.horizontalLayout_10.addWidget(self.combo_dia_personal)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_25)
        self.personal_table = QtWidgets.QTableWidget(self.pag_personal)
        self.personal_table.setObjectName("personal_table")
        self.personal_table.setColumnCount(0)
        self.personal_table.setRowCount(0)
        self.personal_table.horizontalHeader().setDefaultSectionSize(184)
        self.verticalLayout_3.addWidget(self.personal_table)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_add_personal = QtWidgets.QPushButton(self.pag_personal)
        self.button_add_personal.setObjectName("button_add_personal")
        self.horizontalLayout_3.addWidget(self.button_add_personal)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.button_remove_personal = QtWidgets.QPushButton(self.pag_personal)
        self.button_remove_personal.setObjectName("button_remove_personal")
        self.horizontalLayout_3.addWidget(self.button_remove_personal)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.personal_added = QtWidgets.QTableWidget(self.pag_personal)
        self.personal_added.setObjectName("personal_added")
        self.personal_added.setColumnCount(0)
        self.personal_added.setRowCount(0)
        self.personal_added.horizontalHeader().setDefaultSectionSize(158)
        self.personal_added.horizontalHeader().setMinimumSectionSize(1)
        self.verticalLayout_5.addWidget(self.personal_added)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.buttonPersonalNext = QtWidgets.QPushButton(self.pag_personal)
        self.buttonPersonalNext.setObjectName("buttonPersonalNext")
        self.horizontalLayout_5.addWidget(self.buttonPersonalNext)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        self.tabWidget.addTab(self.pag_personal, "")
        self.pag_proveedores = QtWidgets.QWidget()
        self.pag_proveedores.setObjectName("pag_proveedores")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.pag_proveedores)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.proveedores = QtWidgets.QLabel(self.pag_proveedores)
        self.proveedores.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.proveedores.setObjectName("proveedores")
        self.horizontalLayout_26.addWidget(self.proveedores)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem12)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.nombre_prov = QtWidgets.QLabel(self.pag_proveedores)
        self.nombre_prov.setObjectName("nombre_prov")
        self.horizontalLayout_27.addWidget(self.nombre_prov)
        self.entry_nombre_prov = QtWidgets.QLineEdit(self.pag_proveedores)
        self.entry_nombre_prov.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_nombre_prov.setObjectName("entry_nombre_prov")
        self.horizontalLayout_27.addWidget(self.entry_nombre_prov)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_27)
        self.buttonBuscarProv = QtWidgets.QPushButton(self.pag_proveedores)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBuscarProv.sizePolicy().hasHeightForWidth())
        self.buttonBuscarProv.setSizePolicy(sizePolicy)
        self.buttonBuscarProv.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonBuscarProv.setObjectName("buttonBuscarProv")
        self.horizontalLayout_26.addWidget(self.buttonBuscarProv)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem13)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.filtrar_serv = QtWidgets.QLabel(self.pag_proveedores)
        self.filtrar_serv.setObjectName("filtrar_serv")
        self.horizontalLayout_21.addWidget(self.filtrar_serv)
        self.combo_filtrar_serv = QtWidgets.QComboBox(self.pag_proveedores)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_filtrar_serv.sizePolicy().hasHeightForWidth())
        self.combo_filtrar_serv.setSizePolicy(sizePolicy)
        self.combo_filtrar_serv.setMinimumSize(QtCore.QSize(145, 0))
        self.combo_filtrar_serv.setObjectName("combo_filtrar_serv")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.horizontalLayout_21.addWidget(self.combo_filtrar_serv)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_21)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem14)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.dia_prov = QtWidgets.QLabel(self.pag_proveedores)
        self.dia_prov.setObjectName("dia_prov")
        self.horizontalLayout_18.addWidget(self.dia_prov)
        self.combo_dia_prov = QtWidgets.QComboBox(self.pag_proveedores)
        self.combo_dia_prov.setMinimumSize(QtCore.QSize(145, 0))
        self.combo_dia_prov.setObjectName("combo_dia_prov")
        self.horizontalLayout_18.addWidget(self.combo_dia_prov)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_18)
        self.verticalLayout_7.addLayout(self.horizontalLayout_26)
        self.prov_table = QtWidgets.QTableWidget(self.pag_proveedores)
        self.prov_table.setObjectName("prov_table")
        self.prov_table.setColumnCount(0)
        self.prov_table.setRowCount(0)
        self.verticalLayout_7.addWidget(self.prov_table)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.button_add_prov = QtWidgets.QPushButton(self.pag_proveedores)
        self.button_add_prov.setObjectName("button_add_prov")
        self.horizontalLayout_6.addWidget(self.button_add_prov)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.button_remove_prov = QtWidgets.QPushButton(self.pag_proveedores)
        self.button_remove_prov.setObjectName("button_remove_prov")
        self.horizontalLayout_6.addWidget(self.button_remove_prov)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.prov_added = QtWidgets.QTableWidget(self.pag_proveedores)
        self.prov_added.setObjectName("prov_added")
        self.prov_added.setColumnCount(0)
        self.prov_added.setRowCount(0)
        self.verticalLayout_6.addWidget(self.prov_added)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.buttonProvOk = QtWidgets.QPushButton(self.pag_proveedores)
        self.buttonProvOk.setObjectName("buttonProvOk")
        self.horizontalLayout_7.addWidget(self.buttonProvOk)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem16)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.pag_proveedores, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonProvOk.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.entry_id, self.entry_nombre)
        Dialog.setTabOrder(self.entry_nombre, self.entry_cliente)
        Dialog.setTabOrder(self.entry_cliente, self.comboBox_2)
        Dialog.setTabOrder(self.comboBox_2, self.comboBox)
        Dialog.setTabOrder(self.comboBox, self.combo_manager)
        Dialog.setTabOrder(self.combo_manager, self.entry_onsite)
        Dialog.setTabOrder(self.entry_onsite, self.entry_tfn_onsite)
        Dialog.setTabOrder(self.entry_tfn_onsite, self.entry_email_onsite)
        Dialog.setTabOrder(self.entry_email_onsite, self.entry_notas)
        Dialog.setTabOrder(self.entry_notas, self.buttonAddRecinto)
        Dialog.setTabOrder(self.buttonAddRecinto, self.buttonAddManager)
        Dialog.setTabOrder(self.buttonAddManager, self.calendar)
        Dialog.setTabOrder(self.calendar, self.time)
        Dialog.setTabOrder(self.time, self.combo_tarea)
        Dialog.setTabOrder(self.combo_tarea, self.buttonAddDate)
        Dialog.setTabOrder(self.buttonAddDate, self.buttonDelDate)
        Dialog.setTabOrder(self.buttonDelDate, self.entry_nombre_personal)
        Dialog.setTabOrder(self.entry_nombre_personal, self.combo_filtrar_cargos)
        Dialog.setTabOrder(self.combo_filtrar_cargos, self.button_add_personal)
        Dialog.setTabOrder(self.button_add_personal, self.button_remove_personal)
        Dialog.setTabOrder(self.button_remove_personal, self.personal_added)
        Dialog.setTabOrder(self.personal_added, self.buttonPersonalNext)
        Dialog.setTabOrder(self.buttonPersonalNext, self.entry_nombre_prov)
        Dialog.setTabOrder(self.entry_nombre_prov, self.combo_filtrar_serv)
        Dialog.setTabOrder(self.combo_filtrar_serv, self.combo_dia_prov)
        Dialog.setTabOrder(self.combo_dia_prov, self.button_add_prov)
        Dialog.setTabOrder(self.button_add_prov, self.button_remove_prov)
        Dialog.setTabOrder(self.button_remove_prov, self.buttonProvOk)
        Dialog.setTabOrder(self.buttonProvOk, self.personal_table)
        Dialog.setTabOrder(self.personal_table, self.prov_added)
        Dialog.setTabOrder(self.prov_added, self.prov_table)
        Dialog.setTabOrder(self.prov_table, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.fechas_table)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.datos.setText(_translate("Dialog", "DATOS"))
        self.crear_evento.setText(_translate("Dialog", "Crear Evento"))
        self.buttonDatosNext.setText(_translate("Dialog", "Siguiente"))
        self.notas.setText(_translate("Dialog", "NOTAS"))
        self.tfn_onsite.setText(_translate("Dialog", "TELEFONO ON-SITE"))
        self.email_onsite.setText(_translate("Dialog", "EMAIL ON-SITE"))
        self.cliente.setText(_translate("Dialog", "CLIENTE"))
        self.onsite.setText(_translate("Dialog", "CONTACTO ON-SITE"))
        self.recinto.setText(_translate("Dialog", "RECINTO"))
        self.manager.setText(_translate("Dialog", "PROJECT MANAGER"))
        self.id.setText(_translate("Dialog", "ID EVENTO"))
        self.nombre.setText(_translate("Dialog", "NOMBRE"))
        self.buttonAddRecinto.setText(_translate("Dialog", "+"))
        self.buttonAddManager.setText(_translate("Dialog", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pag_datos), _translate("Dialog", "Datos del evento"))
        item = self.fechas_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Fecha"))
        item = self.fechas_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Hora"))
        item = self.fechas_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Tarea"))
        item = self.fechas_table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Id Fecha"))
        self.label.setText(_translate("Dialog", "FECHAS DEL EVENTO"))
        self.label_2.setText(_translate("Dialog", "Hora prevista"))
        self.time.setDisplayFormat(_translate("Dialog", "HH:mm"))
        self.labelTarea.setText(_translate("Dialog", "Tarea"))
        self.combo_tarea.setItemText(0, _translate("Dialog", "Carga"))
        self.combo_tarea.setItemText(1, _translate("Dialog", "Montaje"))
        self.combo_tarea.setItemText(2, _translate("Dialog", "Pruebas"))
        self.combo_tarea.setItemText(3, _translate("Dialog", "Evento"))
        self.combo_tarea.setItemText(4, _translate("Dialog", "Desmontaje"))
        self.combo_tarea.setItemText(5, _translate("Dialog", "Descarga"))
        self.combo_tarea.setItemText(6, _translate("Dialog", "Produccion"))
        self.combo_tarea.setItemText(7, _translate("Dialog", "Viaje"))
        self.combo_tarea.setItemText(8, _translate("Dialog", "Almacén"))
        self.buttonAddDate.setText(_translate("Dialog", "Añadir fecha"))
        self.buttonDelDate.setText(_translate("Dialog", "Eliminar fecha"))
        self.buttonFechaNext.setText(_translate("Dialog", "Siguiente"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pag_fechas), _translate("Dialog", "Fechas del evento"))
        self.personal.setText(_translate("Dialog", "PERSONAL"))
        self.nombre_personal.setText(_translate("Dialog", "Nombre"))
        self.buttonBuscarPers.setText(_translate("Dialog", "Buscar"))
        self.filtrar_cargos.setText(_translate("Dialog", "Filtrar Cargos"))
        self.combo_filtrar_cargos.setItemText(0, _translate("Dialog", "All"))
        self.combo_filtrar_cargos.setItemText(1, _translate("Dialog", "Crew Chief"))
        self.combo_filtrar_cargos.setItemText(2, _translate("Dialog", "Operador de Luces"))
        self.combo_filtrar_cargos.setItemText(3, _translate("Dialog", "Dimmers"))
        self.combo_filtrar_cargos.setItemText(4, _translate("Dialog", "Técnico de Luces"))
        self.combo_filtrar_cargos.setItemText(5, _translate("Dialog", "Operador de Sonido"))
        self.combo_filtrar_cargos.setItemText(6, _translate("Dialog", "RF"))
        self.combo_filtrar_cargos.setItemText(7, _translate("Dialog", "Técnico de Sonido"))
        self.combo_filtrar_cargos.setItemText(8, _translate("Dialog", "Operador de Video"))
        self.combo_filtrar_cargos.setItemText(9, _translate("Dialog", "Led"))
        self.combo_filtrar_cargos.setItemText(10, _translate("Dialog", "Técnico de Video"))
        self.combo_filtrar_cargos.setItemText(11, _translate("Dialog", "Rigger"))
        self.combo_filtrar_cargos.setItemText(12, _translate("Dialog", "Regidor"))
        self.combo_filtrar_cargos.setItemText(13, _translate("Dialog", "Contenidos"))
        self.combo_filtrar_cargos.setItemText(14, _translate("Dialog", "Deco"))
        self.dia_personal.setText(_translate("Dialog", "Día"))
        self.button_add_personal.setText(_translate("Dialog", "Añadir"))
        self.button_remove_personal.setText(_translate("Dialog", "Quitar"))
        self.buttonPersonalNext.setText(_translate("Dialog", "Siguente"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pag_personal), _translate("Dialog", "Personal"))
        self.proveedores.setText(_translate("Dialog", "PROVEEDORES"))
        self.nombre_prov.setText(_translate("Dialog", "Nombre"))
        self.buttonBuscarProv.setText(_translate("Dialog", "Buscar"))
        self.filtrar_serv.setText(_translate("Dialog", "Filtrar Servicio"))
        self.combo_filtrar_serv.setItemText(0, _translate("Dialog", "All"))
        self.combo_filtrar_serv.setItemText(1, _translate("Dialog", "Trailer"))
        self.combo_filtrar_serv.setItemText(2, _translate("Dialog", "Camión"))
        self.combo_filtrar_serv.setItemText(3, _translate("Dialog", "Furgoneta"))
        self.combo_filtrar_serv.setItemText(4, _translate("Dialog", "Runner"))
        self.combo_filtrar_serv.setItemText(5, _translate("Dialog", "Carga/Descarga"))
        self.combo_filtrar_serv.setItemText(6, _translate("Dialog", "Rigging"))
        self.combo_filtrar_serv.setItemText(7, _translate("Dialog", "Deco"))
        self.combo_filtrar_serv.setItemText(8, _translate("Dialog", "Generadores"))
        self.combo_filtrar_serv.setItemText(9, _translate("Dialog", "Traducción"))
        self.combo_filtrar_serv.setItemText(10, _translate("Dialog", "Catering"))
        self.combo_filtrar_serv.setItemText(11, _translate("Dialog", "Iluminación"))
        self.combo_filtrar_serv.setItemText(12, _translate("Dialog", "Sonido"))
        self.combo_filtrar_serv.setItemText(13, _translate("Dialog", "Video"))
        self.combo_filtrar_serv.setItemText(14, _translate("Dialog", "Mobiliario"))
        self.combo_filtrar_serv.setItemText(15, _translate("Dialog", "Otros"))
        self.dia_prov.setText(_translate("Dialog", "Día"))
        self.button_add_prov.setText(_translate("Dialog", "Añadir"))
        self.button_remove_prov.setText(_translate("Dialog", "Quitar"))
        self.buttonProvOk.setText(_translate("Dialog", "OK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pag_proveedores), _translate("Dialog", "Proveedores"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = CrearEvento_Ui()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

