# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crearevento_widget_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class CrearEvento_Ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1239, 837)
        Form.setStyleSheet("")
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(120, 30))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(40, 40))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.pag_datos = QtWidgets.QWidget()
        self.pag_datos.setObjectName("pag_datos")
        self.gridLayout = QtWidgets.QGridLayout(self.pag_datos)
        self.gridLayout.setContentsMargins(11, 11, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.combo_manager = QtWidgets.QComboBox(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_manager.sizePolicy().hasHeightForWidth())
        self.combo_manager.setSizePolicy(sizePolicy)
        self.combo_manager.setObjectName("combo_manager")
        self.gridLayout.addWidget(self.combo_manager, 8, 4, 1, 1)
        self.nombre = QtWidgets.QLabel(self.pag_datos)
        self.nombre.setObjectName("nombre")
        self.gridLayout.addWidget(self.nombre, 5, 1, 1, 1)
        self.tfn_onsite = QtWidgets.QLabel(self.pag_datos)
        self.tfn_onsite.setObjectName("tfn_onsite")
        self.gridLayout.addWidget(self.tfn_onsite, 10, 1, 1, 1)
        self.entry_cliente = QtWidgets.QLineEdit(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_cliente.sizePolicy().hasHeightForWidth())
        self.entry_cliente.setSizePolicy(sizePolicy)
        self.entry_cliente.setObjectName("entry_cliente")
        self.gridLayout.addWidget(self.entry_cliente, 6, 4, 1, 1)
        self.manager = QtWidgets.QLabel(self.pag_datos)
        self.manager.setObjectName("manager")
        self.gridLayout.addWidget(self.manager, 8, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 15, 3, 1, 1)
        self.entry_email_onsite = QtWidgets.QLineEdit(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_email_onsite.sizePolicy().hasHeightForWidth())
        self.entry_email_onsite.setSizePolicy(sizePolicy)
        self.entry_email_onsite.setText("")
        self.entry_email_onsite.setObjectName("entry_email_onsite")
        self.gridLayout.addWidget(self.entry_email_onsite, 11, 4, 1, 1)
        self.notas = QtWidgets.QLabel(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notas.sizePolicy().hasHeightForWidth())
        self.notas.setSizePolicy(sizePolicy)
        self.notas.setStyleSheet("")
        self.notas.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.notas.setObjectName("notas")
        self.gridLayout.addWidget(self.notas, 12, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMinimumSize(QtCore.QSize(180, 0))
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 7, 2, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 7, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 13, 4, 1, 1)
        self.email_onsite = QtWidgets.QLabel(self.pag_datos)
        self.email_onsite.setObjectName("email_onsite")
        self.gridLayout.addWidget(self.email_onsite, 11, 1, 1, 1)
        self.labelTitle2 = QtWidgets.QLabel(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle2.sizePolicy().hasHeightForWidth())
        self.labelTitle2.setSizePolicy(sizePolicy)
        self.labelTitle2.setMinimumSize(QtCore.QSize(180, 0))
        self.labelTitle2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelTitle2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle2.setObjectName("labelTitle2")
        self.gridLayout.addWidget(self.labelTitle2, 2, 3, 1, 1)
        self.recinto = QtWidgets.QLabel(self.pag_datos)
        self.recinto.setObjectName("recinto")
        self.gridLayout.addWidget(self.recinto, 7, 1, 1, 1)
        self.entry_onsite = QtWidgets.QLineEdit(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_onsite.sizePolicy().hasHeightForWidth())
        self.entry_onsite.setSizePolicy(sizePolicy)
        self.entry_onsite.setText("")
        self.entry_onsite.setObjectName("entry_onsite")
        self.gridLayout.addWidget(self.entry_onsite, 9, 4, 1, 1)
        self.entry_notas = QtWidgets.QPlainTextEdit(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_notas.sizePolicy().hasHeightForWidth())
        self.entry_notas.setSizePolicy(sizePolicy)
        self.entry_notas.setMaximumSize(QtCore.QSize(16777215, 200))
        self.entry_notas.setObjectName("entry_notas")
        self.gridLayout.addWidget(self.entry_notas, 12, 4, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.buttonDatosNext = QtWidgets.QPushButton(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDatosNext.sizePolicy().hasHeightForWidth())
        self.buttonDatosNext.setSizePolicy(sizePolicy)
        self.buttonDatosNext.setMinimumSize(QtCore.QSize(148, 30))
        self.buttonDatosNext.setObjectName("buttonDatosNext")
        self.horizontalLayout_4.addWidget(self.buttonDatosNext)
        self.gridLayout.addLayout(self.horizontalLayout_4, 14, 3, 1, 1)
        self.onsite = QtWidgets.QLabel(self.pag_datos)
        self.onsite.setObjectName("onsite")
        self.gridLayout.addWidget(self.onsite, 9, 1, 1, 1)
        self.entry_tfn_onsite = QtWidgets.QLineEdit(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_tfn_onsite.sizePolicy().hasHeightForWidth())
        self.entry_tfn_onsite.setSizePolicy(sizePolicy)
        self.entry_tfn_onsite.setObjectName("entry_tfn_onsite")
        self.gridLayout.addWidget(self.entry_tfn_onsite, 10, 4, 1, 1)
        self.id = QtWidgets.QLabel(self.pag_datos)
        self.id.setObjectName("id")
        self.gridLayout.addWidget(self.id, 4, 1, 1, 1)
        self.entry_nombre = QtWidgets.QLineEdit(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_nombre.sizePolicy().hasHeightForWidth())
        self.entry_nombre.setSizePolicy(sizePolicy)
        self.entry_nombre.setText("")
        self.entry_nombre.setObjectName("entry_nombre")
        self.gridLayout.addWidget(self.entry_nombre, 5, 4, 1, 1)
        self.buttonAddManager = QtWidgets.QPushButton(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAddManager.sizePolicy().hasHeightForWidth())
        self.buttonAddManager.setSizePolicy(sizePolicy)
        self.buttonAddManager.setMinimumSize(QtCore.QSize(35, 35))
        self.buttonAddManager.setMaximumSize(QtCore.QSize(30, 30))
        self.buttonAddManager.setObjectName("buttonAddManager")
        self.gridLayout.addWidget(self.buttonAddManager, 8, 5, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 7, 4, 1, 1)
        self.entry_id = QtWidgets.QLineEdit(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_id.sizePolicy().hasHeightForWidth())
        self.entry_id.setSizePolicy(sizePolicy)
        self.entry_id.setObjectName("entry_id")
        self.gridLayout.addWidget(self.entry_id, 4, 4, 1, 1)
        self.cliente = QtWidgets.QLabel(self.pag_datos)
        self.cliente.setObjectName("cliente")
        self.gridLayout.addWidget(self.cliente, 6, 1, 1, 1)
        self.buttonAddRecinto = QtWidgets.QPushButton(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAddRecinto.sizePolicy().hasHeightForWidth())
        self.buttonAddRecinto.setSizePolicy(sizePolicy)
        self.buttonAddRecinto.setMinimumSize(QtCore.QSize(35, 35))
        self.buttonAddRecinto.setMaximumSize(QtCore.QSize(30, 30))
        self.buttonAddRecinto.setObjectName("buttonAddRecinto")
        self.gridLayout.addWidget(self.buttonAddRecinto, 7, 5, 1, 1)
        self.labelTitle = QtWidgets.QLabel(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle.sizePolicy().hasHeightForWidth())
        self.labelTitle.setSizePolicy(sizePolicy)
        self.labelTitle.setMinimumSize(QtCore.QSize(180, 0))
        self.labelTitle.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.gridLayout.addWidget(self.labelTitle, 1, 3, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 0, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 3, 3, 1, 1)
        self.tabWidget.addTab(self.pag_datos, "")
        self.pag_fechas = QtWidgets.QWidget()
        self.pag_fechas.setObjectName("pag_fechas")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.pag_fechas)
        self.gridLayout_5.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelHora = QtWidgets.QLabel(self.pag_fechas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHora.sizePolicy().hasHeightForWidth())
        self.labelHora.setSizePolicy(sizePolicy)
        self.labelHora.setMinimumSize(QtCore.QSize(120, 30))
        self.labelHora.setObjectName("labelHora")
        self.verticalLayout.addWidget(self.labelHora)
        self.time = QtWidgets.QTimeEdit(self.pag_fechas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time.sizePolicy().hasHeightForWidth())
        self.time.setSizePolicy(sizePolicy)
        self.time.setMinimumSize(QtCore.QSize(120, 30))
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.verticalLayout.addWidget(self.time)
        self.labelTarea = QtWidgets.QLabel(self.pag_fechas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTarea.sizePolicy().hasHeightForWidth())
        self.labelTarea.setSizePolicy(sizePolicy)
        self.labelTarea.setObjectName("labelTarea")
        self.verticalLayout.addWidget(self.labelTarea)
        self.combo_tarea = QtWidgets.QComboBox(self.pag_fechas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_tarea.sizePolicy().hasHeightForWidth())
        self.combo_tarea.setSizePolicy(sizePolicy)
        self.combo_tarea.setMinimumSize(QtCore.QSize(120, 30))
        self.combo_tarea.setObjectName("combo_tarea")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.verticalLayout.addWidget(self.combo_tarea)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.buttonAddDate = QtWidgets.QPushButton(self.pag_fechas)
        self.buttonAddDate.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAddDate.sizePolicy().hasHeightForWidth())
        self.buttonAddDate.setSizePolicy(sizePolicy)
        self.buttonAddDate.setMinimumSize(QtCore.QSize(125, 30))
        self.buttonAddDate.setObjectName("buttonAddDate")
        self.verticalLayout.addWidget(self.buttonAddDate)
        self.buttonModificar = QtWidgets.QPushButton(self.pag_fechas)
        self.buttonModificar.setObjectName("buttonModificar")
        self.verticalLayout.addWidget(self.buttonModificar)
        self.buttonDelDate = QtWidgets.QPushButton(self.pag_fechas)
        self.buttonDelDate.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDelDate.sizePolicy().hasHeightForWidth())
        self.buttonDelDate.setSizePolicy(sizePolicy)
        self.buttonDelDate.setMinimumSize(QtCore.QSize(125, 30))
        self.buttonDelDate.setObjectName("buttonDelDate")
        self.verticalLayout.addWidget(self.buttonDelDate)
        self.buttonFechaNext = QtWidgets.QPushButton(self.pag_fechas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonFechaNext.sizePolicy().hasHeightForWidth())
        self.buttonFechaNext.setSizePolicy(sizePolicy)
        self.buttonFechaNext.setMinimumSize(QtCore.QSize(125, 30))
        self.buttonFechaNext.setObjectName("buttonFechaNext")
        self.verticalLayout.addWidget(self.buttonFechaNext)
        self.gridLayout_5.addLayout(self.verticalLayout, 2, 2, 1, 1)
        self.fechas_table = QtWidgets.QTableWidget(self.pag_fechas)
        self.fechas_table.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.fechas_table.sizePolicy().hasHeightForWidth())
        self.fechas_table.setSizePolicy(sizePolicy)
        self.fechas_table.setMinimumSize(QtCore.QSize(500, 424))
        self.fechas_table.setSizeIncrement(QtCore.QSize(1, 1))
        self.fechas_table.setBaseSize(QtCore.QSize(0, 0))
        self.fechas_table.setStyleSheet("")
        self.fechas_table.setObjectName("fechas_table")
        self.fechas_table.setColumnCount(4)
        self.fechas_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fechas_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fechas_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fechas_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fechas_table.setHorizontalHeaderItem(3, item)
        self.gridLayout_5.addWidget(self.fechas_table, 2, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_5.addItem(spacerItem7, 1, 2, 1, 1)
        self.labelTitle3 = QtWidgets.QLabel(self.pag_fechas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle3.sizePolicy().hasHeightForWidth())
        self.labelTitle3.setSizePolicy(sizePolicy)
        self.labelTitle3.setStyleSheet("")
        self.labelTitle3.setObjectName("labelTitle3")
        self.gridLayout_5.addWidget(self.labelTitle3, 0, 0, 1, 1)
        self.calendar = QtWidgets.QCalendarWidget(self.pag_fechas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.calendar.sizePolicy().hasHeightForWidth())
        self.calendar.setSizePolicy(sizePolicy)
        self.calendar.setMinimumSize(QtCore.QSize(500, 400))
        self.calendar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.calendar.setSizeIncrement(QtCore.QSize(1, 1))
        self.calendar.setBaseSize(QtCore.QSize(1, 1))
        self.calendar.setStyleSheet("")
        self.calendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendar.setNavigationBarVisible(True)
        self.calendar.setObjectName("calendar")
        self.gridLayout_5.addWidget(self.calendar, 2, 0, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem8, 3, 2, 1, 1)
        self.tabWidget.addTab(self.pag_fechas, "")
        self.pag_personal = QtWidgets.QWidget()
        self.pag_personal.setObjectName("pag_personal")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pag_personal)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.labelTitle4 = QtWidgets.QLabel(self.pag_personal)
        self.labelTitle4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelTitle4.setObjectName("labelTitle4")
        self.horizontalLayout_25.addWidget(self.labelTitle4)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem9)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.nombre_personal = QtWidgets.QLabel(self.pag_personal)
        self.nombre_personal.setObjectName("nombre_personal")
        self.horizontalLayout_24.addWidget(self.nombre_personal)
        self.entry_nombre_personal = QtWidgets.QLineEdit(self.pag_personal)
        self.entry_nombre_personal.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_nombre_personal.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.entry_nombre_personal.setObjectName("entry_nombre_personal")
        self.horizontalLayout_24.addWidget(self.entry_nombre_personal)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_24)
        self.buttonBuscarPers = QtWidgets.QPushButton(self.pag_personal)
        self.buttonBuscarPers.setMinimumSize(QtCore.QSize(65, 30))
        self.buttonBuscarPers.setObjectName("buttonBuscarPers")
        self.horizontalLayout_25.addWidget(self.buttonBuscarPers)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem10)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.filtrar_cargos = QtWidgets.QLabel(self.pag_personal)
        self.filtrar_cargos.setObjectName("filtrar_cargos")
        self.horizontalLayout_19.addWidget(self.filtrar_cargos)
        self.combo_filtrar_cargos = QtWidgets.QComboBox(self.pag_personal)
        self.combo_filtrar_cargos.setMinimumSize(QtCore.QSize(145, 0))
        self.combo_filtrar_cargos.setObjectName("combo_filtrar_cargos")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.horizontalLayout_19.addWidget(self.combo_filtrar_cargos)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_19)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.dia_personal = QtWidgets.QLabel(self.pag_personal)
        self.dia_personal.setObjectName("dia_personal")
        self.horizontalLayout_10.addWidget(self.dia_personal)
        self.combo_dia_personal = QtWidgets.QComboBox(self.pag_personal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_dia_personal.sizePolicy().hasHeightForWidth())
        self.combo_dia_personal.setSizePolicy(sizePolicy)
        self.combo_dia_personal.setMinimumSize(QtCore.QSize(145, 0))
        self.combo_dia_personal.setObjectName("combo_dia_personal")
        self.horizontalLayout_10.addWidget(self.combo_dia_personal)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_25)
        self.personal_table = QtWidgets.QTableWidget(self.pag_personal)
        self.personal_table.setObjectName("personal_table")
        self.personal_table.setColumnCount(0)
        self.personal_table.setRowCount(0)
        self.personal_table.horizontalHeader().setDefaultSectionSize(184)
        self.verticalLayout_3.addWidget(self.personal_table)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_add_personal = QtWidgets.QPushButton(self.pag_personal)
        self.button_add_personal.setMinimumSize(QtCore.QSize(65, 30))
        self.button_add_personal.setObjectName("button_add_personal")
        self.horizontalLayout_3.addWidget(self.button_add_personal)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.button_remove_personal = QtWidgets.QPushButton(self.pag_personal)
        self.button_remove_personal.setMinimumSize(QtCore.QSize(65, 30))
        self.button_remove_personal.setObjectName("button_remove_personal")
        self.horizontalLayout_3.addWidget(self.button_remove_personal)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.personal_added = QtWidgets.QTableWidget(self.pag_personal)
        self.personal_added.setObjectName("personal_added")
        self.personal_added.setColumnCount(0)
        self.personal_added.setRowCount(0)
        self.personal_added.horizontalHeader().setDefaultSectionSize(158)
        self.personal_added.horizontalHeader().setMinimumSectionSize(1)
        self.verticalLayout_5.addWidget(self.personal_added)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.buttonPersonalNext = QtWidgets.QPushButton(self.pag_personal)
        self.buttonPersonalNext.setMinimumSize(QtCore.QSize(65, 30))
        self.buttonPersonalNext.setObjectName("buttonPersonalNext")
        self.horizontalLayout_5.addWidget(self.buttonPersonalNext)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        self.tabWidget.addTab(self.pag_personal, "")
        self.pag_proveedores = QtWidgets.QWidget()
        self.pag_proveedores.setObjectName("pag_proveedores")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.pag_proveedores)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.labelTitle5 = QtWidgets.QLabel(self.pag_proveedores)
        self.labelTitle5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelTitle5.setObjectName("labelTitle5")
        self.horizontalLayout_26.addWidget(self.labelTitle5)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem14)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.nombre_prov = QtWidgets.QLabel(self.pag_proveedores)
        self.nombre_prov.setObjectName("nombre_prov")
        self.horizontalLayout_27.addWidget(self.nombre_prov)
        self.entry_nombre_prov = QtWidgets.QLineEdit(self.pag_proveedores)
        self.entry_nombre_prov.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_nombre_prov.setObjectName("entry_nombre_prov")
        self.horizontalLayout_27.addWidget(self.entry_nombre_prov)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_27)
        self.buttonBuscarProv = QtWidgets.QPushButton(self.pag_proveedores)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBuscarProv.sizePolicy().hasHeightForWidth())
        self.buttonBuscarProv.setSizePolicy(sizePolicy)
        self.buttonBuscarProv.setMinimumSize(QtCore.QSize(65, 30))
        self.buttonBuscarProv.setObjectName("buttonBuscarProv")
        self.horizontalLayout_26.addWidget(self.buttonBuscarProv)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem15)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.filtrar_serv = QtWidgets.QLabel(self.pag_proveedores)
        self.filtrar_serv.setObjectName("filtrar_serv")
        self.horizontalLayout_21.addWidget(self.filtrar_serv)
        self.combo_filtrar_serv = QtWidgets.QComboBox(self.pag_proveedores)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_filtrar_serv.sizePolicy().hasHeightForWidth())
        self.combo_filtrar_serv.setSizePolicy(sizePolicy)
        self.combo_filtrar_serv.setMinimumSize(QtCore.QSize(145, 0))
        self.combo_filtrar_serv.setObjectName("combo_filtrar_serv")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.horizontalLayout_21.addWidget(self.combo_filtrar_serv)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_21)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem16)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.dia_prov = QtWidgets.QLabel(self.pag_proveedores)
        self.dia_prov.setObjectName("dia_prov")
        self.horizontalLayout_18.addWidget(self.dia_prov)
        self.combo_dia_prov = QtWidgets.QComboBox(self.pag_proveedores)
        self.combo_dia_prov.setMinimumSize(QtCore.QSize(145, 0))
        self.combo_dia_prov.setObjectName("combo_dia_prov")
        self.horizontalLayout_18.addWidget(self.combo_dia_prov)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_18)
        self.verticalLayout_7.addLayout(self.horizontalLayout_26)
        self.prov_table = QtWidgets.QTableWidget(self.pag_proveedores)
        self.prov_table.setObjectName("prov_table")
        self.prov_table.setColumnCount(0)
        self.prov_table.setRowCount(0)
        self.verticalLayout_7.addWidget(self.prov_table)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.button_add_prov = QtWidgets.QPushButton(self.pag_proveedores)
        self.button_add_prov.setMinimumSize(QtCore.QSize(65, 30))
        self.button_add_prov.setObjectName("button_add_prov")
        self.horizontalLayout_6.addWidget(self.button_add_prov)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.button_remove_prov = QtWidgets.QPushButton(self.pag_proveedores)
        self.button_remove_prov.setMinimumSize(QtCore.QSize(65, 30))
        self.button_remove_prov.setObjectName("button_remove_prov")
        self.horizontalLayout_6.addWidget(self.button_remove_prov)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.prov_added = QtWidgets.QTableWidget(self.pag_proveedores)
        self.prov_added.setObjectName("prov_added")
        self.prov_added.setColumnCount(0)
        self.prov_added.setRowCount(0)
        self.verticalLayout_6.addWidget(self.prov_added)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.buttonProvOk = QtWidgets.QPushButton(self.pag_proveedores)
        self.buttonProvOk.setMinimumSize(QtCore.QSize(65, 30))
        self.buttonProvOk.setObjectName("buttonProvOk")
        self.horizontalLayout_7.addWidget(self.buttonProvOk)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem18)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.pag_proveedores, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.entry_id, self.entry_nombre)
        Form.setTabOrder(self.entry_nombre, self.entry_cliente)
        Form.setTabOrder(self.entry_cliente, self.comboBox_2)
        Form.setTabOrder(self.comboBox_2, self.comboBox)
        Form.setTabOrder(self.comboBox, self.combo_manager)
        Form.setTabOrder(self.combo_manager, self.entry_onsite)
        Form.setTabOrder(self.entry_onsite, self.entry_tfn_onsite)
        Form.setTabOrder(self.entry_tfn_onsite, self.entry_email_onsite)
        Form.setTabOrder(self.entry_email_onsite, self.entry_notas)
        Form.setTabOrder(self.entry_notas, self.buttonAddRecinto)
        Form.setTabOrder(self.buttonAddRecinto, self.buttonAddManager)
        Form.setTabOrder(self.buttonAddManager, self.buttonDatosNext)
        Form.setTabOrder(self.buttonDatosNext, self.time)
        Form.setTabOrder(self.time, self.combo_tarea)
        Form.setTabOrder(self.combo_tarea, self.calendar)
        Form.setTabOrder(self.calendar, self.buttonAddDate)
        Form.setTabOrder(self.buttonAddDate, self.buttonDelDate)
        Form.setTabOrder(self.buttonDelDate, self.buttonFechaNext)
        Form.setTabOrder(self.buttonFechaNext, self.fechas_table)
        Form.setTabOrder(self.fechas_table, self.entry_nombre_personal)
        Form.setTabOrder(self.entry_nombre_personal, self.buttonBuscarPers)
        Form.setTabOrder(self.buttonBuscarPers, self.combo_filtrar_cargos)
        Form.setTabOrder(self.combo_filtrar_cargos, self.combo_dia_personal)
        Form.setTabOrder(self.combo_dia_personal, self.personal_table)
        Form.setTabOrder(self.personal_table, self.button_add_personal)
        Form.setTabOrder(self.button_add_personal, self.button_remove_personal)
        Form.setTabOrder(self.button_remove_personal, self.personal_added)
        Form.setTabOrder(self.personal_added, self.buttonPersonalNext)
        Form.setTabOrder(self.buttonPersonalNext, self.entry_nombre_prov)
        Form.setTabOrder(self.entry_nombre_prov, self.buttonBuscarProv)
        Form.setTabOrder(self.buttonBuscarProv, self.combo_filtrar_serv)
        Form.setTabOrder(self.combo_filtrar_serv, self.combo_dia_prov)
        Form.setTabOrder(self.combo_dia_prov, self.tabWidget)
        Form.setTabOrder(self.tabWidget, self.prov_table)
        Form.setTabOrder(self.prov_table, self.button_add_prov)
        Form.setTabOrder(self.button_add_prov, self.button_remove_prov)
        Form.setTabOrder(self.button_remove_prov, self.prov_added)
        Form.setTabOrder(self.prov_added, self.buttonProvOk)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.nombre.setText(_translate("Form", "Nombre"))
        self.tfn_onsite.setText(_translate("Form", "Teléfono On Site"))
        self.manager.setText(_translate("Form", "Project Manager"))
        self.notas.setText(_translate("Form", "Notas"))
        self.email_onsite.setText(_translate("Form", "Email On Site"))
        self.labelTitle2.setText(_translate("Form", "DATOS"))
        self.recinto.setText(_translate("Form", "Recinto"))
        self.buttonDatosNext.setText(_translate("Form", "Siguiente"))
        self.onsite.setText(_translate("Form", "Contacto On Site"))
        self.id.setText(_translate("Form", "ID Evento"))
        self.buttonAddManager.setText(_translate("Form", "+"))
        self.cliente.setText(_translate("Form", "Cliente"))
        self.buttonAddRecinto.setText(_translate("Form", "+"))
        self.labelTitle.setText(_translate("Form", "Crear Evento"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pag_datos), _translate("Form", "Datos del evento"))
        self.labelHora.setText(_translate("Form", "Hora prevista"))
        self.time.setDisplayFormat(_translate("Form", "HH:mm"))
        self.labelTarea.setText(_translate("Form", "Tarea"))
        self.combo_tarea.setItemText(0, _translate("Form", ""))
        self.combo_tarea.setItemText(1, _translate("Form", "Carga"))
        self.combo_tarea.setItemText(2, _translate("Form", "Montaje"))
        self.combo_tarea.setItemText(3, _translate("Form", "Pruebas"))
        self.combo_tarea.setItemText(4, _translate("Form", "Evento"))
        self.combo_tarea.setItemText(5, _translate("Form", "Desmontaje"))
        self.combo_tarea.setItemText(6, _translate("Form", "Descarga"))
        self.combo_tarea.setItemText(7, _translate("Form", "Produccion"))
        self.combo_tarea.setItemText(8, _translate("Form", "Viaje"))
        self.combo_tarea.setItemText(9, _translate("Form", "Almacén"))
        self.buttonAddDate.setText(_translate("Form", "Añadir fecha"))
        self.buttonModificar.setToolTip(_translate("Form", "Selecciona parametros y fila y pulse aquí"))
        self.buttonModificar.setText(_translate("Form", "Modificar fecha"))
        self.buttonDelDate.setText(_translate("Form", "Eliminar fecha"))
        self.buttonFechaNext.setText(_translate("Form", "OK"))
        item = self.fechas_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Fecha"))
        item = self.fechas_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Hora"))
        item = self.fechas_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Tarea"))
        item = self.fechas_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Id Fecha"))
        self.labelTitle3.setText(_translate("Form", "Fechas del Evento"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pag_fechas), _translate("Form", "Fechas del evento"))
        self.labelTitle4.setText(_translate("Form", "PERSONAL"))
        self.nombre_personal.setText(_translate("Form", "Nombre"))
        self.buttonBuscarPers.setText(_translate("Form", "Buscar"))
        self.filtrar_cargos.setText(_translate("Form", "Filtrar Cargos"))
        self.combo_filtrar_cargos.setItemText(0, _translate("Form", "All"))
        self.combo_filtrar_cargos.setItemText(1, _translate("Form", "Crew Chief"))
        self.combo_filtrar_cargos.setItemText(2, _translate("Form", "Operador de Luces"))
        self.combo_filtrar_cargos.setItemText(3, _translate("Form", "Dimmers"))
        self.combo_filtrar_cargos.setItemText(4, _translate("Form", "Técnico de Luces"))
        self.combo_filtrar_cargos.setItemText(5, _translate("Form", "Operador de Sonido"))
        self.combo_filtrar_cargos.setItemText(6, _translate("Form", "RF"))
        self.combo_filtrar_cargos.setItemText(7, _translate("Form", "Técnico de Sonido"))
        self.combo_filtrar_cargos.setItemText(8, _translate("Form", "Operador de Video"))
        self.combo_filtrar_cargos.setItemText(9, _translate("Form", "Led"))
        self.combo_filtrar_cargos.setItemText(10, _translate("Form", "Técnico de Video"))
        self.combo_filtrar_cargos.setItemText(11, _translate("Form", "Rigger"))
        self.combo_filtrar_cargos.setItemText(12, _translate("Form", "Regidor"))
        self.combo_filtrar_cargos.setItemText(13, _translate("Form", "Contenidos"))
        self.combo_filtrar_cargos.setItemText(14, _translate("Form", "Deco"))
        self.dia_personal.setText(_translate("Form", "Día"))
        self.button_add_personal.setText(_translate("Form", "Añadir"))
        self.button_remove_personal.setText(_translate("Form", "Quitar"))
        self.buttonPersonalNext.setText(_translate("Form", "OK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pag_personal), _translate("Form", "Personal"))
        self.labelTitle5.setText(_translate("Form", "PROVEEDORES"))
        self.nombre_prov.setText(_translate("Form", "Nombre"))
        self.buttonBuscarProv.setText(_translate("Form", "Buscar"))
        self.filtrar_serv.setText(_translate("Form", "Filtrar Servicio"))
        self.combo_filtrar_serv.setItemText(0, _translate("Form", "All"))
        self.combo_filtrar_serv.setItemText(1, _translate("Form", "Trailer"))
        self.combo_filtrar_serv.setItemText(2, _translate("Form", "Camión"))
        self.combo_filtrar_serv.setItemText(3, _translate("Form", "Furgoneta"))
        self.combo_filtrar_serv.setItemText(4, _translate("Form", "Runner"))
        self.combo_filtrar_serv.setItemText(5, _translate("Form", "Carga/Descarga"))
        self.combo_filtrar_serv.setItemText(6, _translate("Form", "Rigging"))
        self.combo_filtrar_serv.setItemText(7, _translate("Form", "Deco"))
        self.combo_filtrar_serv.setItemText(8, _translate("Form", "Generadores"))
        self.combo_filtrar_serv.setItemText(9, _translate("Form", "Traducción"))
        self.combo_filtrar_serv.setItemText(10, _translate("Form", "Catering"))
        self.combo_filtrar_serv.setItemText(11, _translate("Form", "Iluminación"))
        self.combo_filtrar_serv.setItemText(12, _translate("Form", "Sonido"))
        self.combo_filtrar_serv.setItemText(13, _translate("Form", "Video"))
        self.combo_filtrar_serv.setItemText(14, _translate("Form", "Mobiliario"))
        self.combo_filtrar_serv.setItemText(15, _translate("Form", "Otros"))
        self.dia_prov.setText(_translate("Form", "Día"))
        self.button_add_prov.setText(_translate("Form", "Añadir"))
        self.button_remove_prov.setText(_translate("Form", "Quitar"))
        self.buttonProvOk.setText(_translate("Form", "OK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pag_proveedores), _translate("Form", "Proveedores"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = CrearEvento_Ui()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

