# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crearevento_widget_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class CrearEvento_Ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1338, 879)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("")
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(120, 30))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(40, 40))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.pag_datos = QtWidgets.QWidget()
        self.pag_datos.setObjectName("pag_datos")
        self.gridLayout = QtWidgets.QGridLayout(self.pag_datos)
        self.gridLayout.setObjectName("gridLayout")
        self.entry_notas = QtWidgets.QPlainTextEdit(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_notas.sizePolicy().hasHeightForWidth())
        self.entry_notas.setSizePolicy(sizePolicy)
        self.entry_notas.setMaximumSize(QtCore.QSize(16777215, 200))
        self.entry_notas.setObjectName("entry_notas")
        self.gridLayout.addWidget(self.entry_notas, 11, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonSelect = QtWidgets.QPushButton(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSelect.sizePolicy().hasHeightForWidth())
        self.buttonSelect.setSizePolicy(sizePolicy)
        self.buttonSelect.setMinimumSize(QtCore.QSize(0, 35))
        self.buttonSelect.setObjectName("buttonSelect")
        self.horizontalLayout.addWidget(self.buttonSelect)
        self.buttonAddCliente = QtWidgets.QToolButton(self.pag_datos)
        self.buttonAddCliente.setMinimumSize(QtCore.QSize(35, 35))
        self.buttonAddCliente.setObjectName("buttonAddCliente")
        self.horizontalLayout.addWidget(self.buttonAddCliente)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 14, 4, 1, 1)
        self.notas = QtWidgets.QLabel(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notas.sizePolicy().hasHeightForWidth())
        self.notas.setSizePolicy(sizePolicy)
        self.notas.setStyleSheet("")
        self.notas.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.notas.setObjectName("notas")
        self.gridLayout.addWidget(self.notas, 11, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout.addLayout(self.horizontalLayout_4, 15, 3, 1, 1)
        self.email_onsite = QtWidgets.QLabel(self.pag_datos)
        self.email_onsite.setObjectName("email_onsite")
        self.gridLayout.addWidget(self.email_onsite, 10, 1, 1, 1)
        self.entry_email_onsite = QtWidgets.QLineEdit(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_email_onsite.sizePolicy().hasHeightForWidth())
        self.entry_email_onsite.setSizePolicy(sizePolicy)
        self.entry_email_onsite.setText("")
        self.entry_email_onsite.setObjectName("entry_email_onsite")
        self.gridLayout.addWidget(self.entry_email_onsite, 10, 4, 1, 1)
        self.labelTitle = QtWidgets.QLabel(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle.sizePolicy().hasHeightForWidth())
        self.labelTitle.setSizePolicy(sizePolicy)
        self.labelTitle.setMinimumSize(QtCore.QSize(180, 0))
        self.labelTitle.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.gridLayout.addWidget(self.labelTitle, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.nombre = QtWidgets.QLabel(self.pag_datos)
        self.nombre.setObjectName("nombre")
        self.gridLayout.addWidget(self.nombre, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        self.id = QtWidgets.QLabel(self.pag_datos)
        self.id.setObjectName("id")
        self.gridLayout.addWidget(self.id, 3, 1, 1, 1)
        self.buttonDatosNext = QtWidgets.QPushButton(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDatosNext.sizePolicy().hasHeightForWidth())
        self.buttonDatosNext.setSizePolicy(sizePolicy)
        self.buttonDatosNext.setMinimumSize(QtCore.QSize(148, 35))
        self.buttonDatosNext.setObjectName("buttonDatosNext")
        self.gridLayout.addWidget(self.buttonDatosNext, 13, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 6, 8, 1, 1)
        self.entry_cliente = QtWidgets.QLineEdit(self.pag_datos)
        self.entry_cliente.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_cliente.sizePolicy().hasHeightForWidth())
        self.entry_cliente.setSizePolicy(sizePolicy)
        self.entry_cliente.setMinimumSize(QtCore.QSize(210, 0))
        self.entry_cliente.setReadOnly(True)
        self.entry_cliente.setObjectName("entry_cliente")
        self.gridLayout.addWidget(self.entry_cliente, 5, 4, 1, 1)
        self.entry_onsite = QtWidgets.QLineEdit(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_onsite.sizePolicy().hasHeightForWidth())
        self.entry_onsite.setSizePolicy(sizePolicy)
        self.entry_onsite.setText("")
        self.entry_onsite.setObjectName("entry_onsite")
        self.gridLayout.addWidget(self.entry_onsite, 8, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 2, 3, 1, 1)
        self.entry_id = QtWidgets.QLineEdit(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_id.sizePolicy().hasHeightForWidth())
        self.entry_id.setSizePolicy(sizePolicy)
        self.entry_id.setObjectName("entry_id")
        self.gridLayout.addWidget(self.entry_id, 3, 4, 1, 1)
        self.cliente = QtWidgets.QLabel(self.pag_datos)
        self.cliente.setObjectName("cliente")
        self.gridLayout.addWidget(self.cliente, 5, 1, 1, 1)
        self.recinto = QtWidgets.QLabel(self.pag_datos)
        self.recinto.setObjectName("recinto")
        self.gridLayout.addWidget(self.recinto, 6, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 6, 4, 1, 1)
        self.labelTitle2 = QtWidgets.QLabel(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle2.sizePolicy().hasHeightForWidth())
        self.labelTitle2.setSizePolicy(sizePolicy)
        self.labelTitle2.setMinimumSize(QtCore.QSize(180, 0))
        self.labelTitle2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelTitle2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle2.setObjectName("labelTitle2")
        self.gridLayout.addWidget(self.labelTitle2, 2, 2, 1, 1)
        self.buttonAddManager = QtWidgets.QPushButton(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAddManager.sizePolicy().hasHeightForWidth())
        self.buttonAddManager.setSizePolicy(sizePolicy)
        self.buttonAddManager.setMinimumSize(QtCore.QSize(35, 35))
        self.buttonAddManager.setMaximumSize(QtCore.QSize(30, 30))
        self.buttonAddManager.setObjectName("buttonAddManager")
        self.gridLayout.addWidget(self.buttonAddManager, 7, 5, 1, 1)
        self.manager = QtWidgets.QLabel(self.pag_datos)
        self.manager.setObjectName("manager")
        self.gridLayout.addWidget(self.manager, 7, 1, 1, 1)
        self.entry_nombre = QtWidgets.QLineEdit(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_nombre.sizePolicy().hasHeightForWidth())
        self.entry_nombre.setSizePolicy(sizePolicy)
        self.entry_nombre.setText("")
        self.entry_nombre.setObjectName("entry_nombre")
        self.gridLayout.addWidget(self.entry_nombre, 4, 4, 1, 1)
        self.combo_manager = QtWidgets.QComboBox(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_manager.sizePolicy().hasHeightForWidth())
        self.combo_manager.setSizePolicy(sizePolicy)
        self.combo_manager.setObjectName("combo_manager")
        self.gridLayout.addWidget(self.combo_manager, 7, 4, 1, 1)
        self.tfn_onsite = QtWidgets.QLabel(self.pag_datos)
        self.tfn_onsite.setObjectName("tfn_onsite")
        self.gridLayout.addWidget(self.tfn_onsite, 9, 1, 1, 1)
        self.onsite = QtWidgets.QLabel(self.pag_datos)
        self.onsite.setObjectName("onsite")
        self.gridLayout.addWidget(self.onsite, 8, 1, 1, 1)
        self.buttonAddRecinto = QtWidgets.QPushButton(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAddRecinto.sizePolicy().hasHeightForWidth())
        self.buttonAddRecinto.setSizePolicy(sizePolicy)
        self.buttonAddRecinto.setMinimumSize(QtCore.QSize(35, 35))
        self.buttonAddRecinto.setMaximumSize(QtCore.QSize(30, 30))
        self.buttonAddRecinto.setObjectName("buttonAddRecinto")
        self.gridLayout.addWidget(self.buttonAddRecinto, 6, 5, 1, 1)
        self.entry_tfn_onsite = QtWidgets.QLineEdit(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_tfn_onsite.sizePolicy().hasHeightForWidth())
        self.entry_tfn_onsite.setSizePolicy(sizePolicy)
        self.entry_tfn_onsite.setObjectName("entry_tfn_onsite")
        self.gridLayout.addWidget(self.entry_tfn_onsite, 9, 4, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.pag_datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMinimumSize(QtCore.QSize(180, 0))
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 6, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem5, 12, 4, 1, 1)
        self.tabWidget.addTab(self.pag_datos, "")
        self.pag_fechas = QtWidgets.QWidget()
        self.pag_fechas.setObjectName("pag_fechas")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.pag_fechas)
        self.gridLayout_5.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelHora = QtWidgets.QLabel(self.pag_fechas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHora.sizePolicy().hasHeightForWidth())
        self.labelHora.setSizePolicy(sizePolicy)
        self.labelHora.setMinimumSize(QtCore.QSize(120, 30))
        self.labelHora.setObjectName("labelHora")
        self.verticalLayout.addWidget(self.labelHora)
        self.time = QtWidgets.QTimeEdit(self.pag_fechas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time.sizePolicy().hasHeightForWidth())
        self.time.setSizePolicy(sizePolicy)
        self.time.setMinimumSize(QtCore.QSize(120, 30))
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.verticalLayout.addWidget(self.time)
        self.labelTarea = QtWidgets.QLabel(self.pag_fechas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTarea.sizePolicy().hasHeightForWidth())
        self.labelTarea.setSizePolicy(sizePolicy)
        self.labelTarea.setObjectName("labelTarea")
        self.verticalLayout.addWidget(self.labelTarea)
        self.combo_tarea = QtWidgets.QComboBox(self.pag_fechas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_tarea.sizePolicy().hasHeightForWidth())
        self.combo_tarea.setSizePolicy(sizePolicy)
        self.combo_tarea.setMinimumSize(QtCore.QSize(120, 30))
        self.combo_tarea.setObjectName("combo_tarea")
        self.combo_tarea.addItem("")
        self.combo_tarea.setItemText(0, "")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.combo_tarea.addItem("")
        self.verticalLayout.addWidget(self.combo_tarea)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.buttonAddDate = QtWidgets.QPushButton(self.pag_fechas)
        self.buttonAddDate.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAddDate.sizePolicy().hasHeightForWidth())
        self.buttonAddDate.setSizePolicy(sizePolicy)
        self.buttonAddDate.setMinimumSize(QtCore.QSize(130, 30))
        self.buttonAddDate.setObjectName("buttonAddDate")
        self.verticalLayout.addWidget(self.buttonAddDate)
        self.buttonModificar = QtWidgets.QPushButton(self.pag_fechas)
        self.buttonModificar.setMinimumSize(QtCore.QSize(130, 0))
        self.buttonModificar.setObjectName("buttonModificar")
        self.verticalLayout.addWidget(self.buttonModificar)
        self.buttonDelDate = QtWidgets.QPushButton(self.pag_fechas)
        self.buttonDelDate.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDelDate.sizePolicy().hasHeightForWidth())
        self.buttonDelDate.setSizePolicy(sizePolicy)
        self.buttonDelDate.setMinimumSize(QtCore.QSize(130, 30))
        self.buttonDelDate.setObjectName("buttonDelDate")
        self.verticalLayout.addWidget(self.buttonDelDate)
        self.buttonFechaNext = QtWidgets.QPushButton(self.pag_fechas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonFechaNext.sizePolicy().hasHeightForWidth())
        self.buttonFechaNext.setSizePolicy(sizePolicy)
        self.buttonFechaNext.setMinimumSize(QtCore.QSize(130, 30))
        self.buttonFechaNext.setObjectName("buttonFechaNext")
        self.verticalLayout.addWidget(self.buttonFechaNext)
        self.gridLayout_5.addLayout(self.verticalLayout, 2, 2, 1, 1)
        self.fechas_table = QtWidgets.QTableWidget(self.pag_fechas)
        self.fechas_table.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.fechas_table.sizePolicy().hasHeightForWidth())
        self.fechas_table.setSizePolicy(sizePolicy)
        self.fechas_table.setMinimumSize(QtCore.QSize(500, 424))
        self.fechas_table.setSizeIncrement(QtCore.QSize(1, 1))
        self.fechas_table.setBaseSize(QtCore.QSize(0, 0))
        self.fechas_table.setStyleSheet("")
        self.fechas_table.setObjectName("fechas_table")
        self.fechas_table.setColumnCount(4)
        self.fechas_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fechas_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fechas_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fechas_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fechas_table.setHorizontalHeaderItem(3, item)
        self.gridLayout_5.addWidget(self.fechas_table, 2, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_5.addItem(spacerItem7, 1, 2, 1, 1)
        self.labelTitle3 = QtWidgets.QLabel(self.pag_fechas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle3.sizePolicy().hasHeightForWidth())
        self.labelTitle3.setSizePolicy(sizePolicy)
        self.labelTitle3.setStyleSheet("")
        self.labelTitle3.setObjectName("labelTitle3")
        self.gridLayout_5.addWidget(self.labelTitle3, 0, 0, 1, 1)
        self.calendar = QtWidgets.QCalendarWidget(self.pag_fechas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.calendar.sizePolicy().hasHeightForWidth())
        self.calendar.setSizePolicy(sizePolicy)
        self.calendar.setMinimumSize(QtCore.QSize(500, 400))
        self.calendar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.calendar.setSizeIncrement(QtCore.QSize(1, 1))
        self.calendar.setBaseSize(QtCore.QSize(1, 1))
        self.calendar.setStyleSheet("")
        self.calendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendar.setNavigationBarVisible(True)
        self.calendar.setObjectName("calendar")
        self.gridLayout_5.addWidget(self.calendar, 2, 0, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem8, 3, 2, 1, 1)
        self.tabWidget.addTab(self.pag_fechas, "")
        self.pag_personal = QtWidgets.QWidget()
        self.pag_personal.setObjectName("pag_personal")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pag_personal)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.labelTitle4 = QtWidgets.QLabel(self.pag_personal)
        self.labelTitle4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelTitle4.setObjectName("labelTitle4")
        self.horizontalLayout_25.addWidget(self.labelTitle4)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem9)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.nombre_personal = QtWidgets.QLabel(self.pag_personal)
        self.nombre_personal.setObjectName("nombre_personal")
        self.horizontalLayout_24.addWidget(self.nombre_personal)
        self.entry_nombre_personal = QtWidgets.QLineEdit(self.pag_personal)
        self.entry_nombre_personal.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_nombre_personal.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.entry_nombre_personal.setObjectName("entry_nombre_personal")
        self.horizontalLayout_24.addWidget(self.entry_nombre_personal)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_24)
        self.buttonBuscarPers = QtWidgets.QPushButton(self.pag_personal)
        self.buttonBuscarPers.setMinimumSize(QtCore.QSize(65, 30))
        self.buttonBuscarPers.setObjectName("buttonBuscarPers")
        self.horizontalLayout_25.addWidget(self.buttonBuscarPers)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem10)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.filtrar_cargos = QtWidgets.QLabel(self.pag_personal)
        self.filtrar_cargos.setObjectName("filtrar_cargos")
        self.horizontalLayout_19.addWidget(self.filtrar_cargos)
        self.combo_filtrar_cargos = QtWidgets.QComboBox(self.pag_personal)
        self.combo_filtrar_cargos.setMinimumSize(QtCore.QSize(145, 0))
        self.combo_filtrar_cargos.setObjectName("combo_filtrar_cargos")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.combo_filtrar_cargos.addItem("")
        self.horizontalLayout_19.addWidget(self.combo_filtrar_cargos)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_19)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.dia_personal = QtWidgets.QLabel(self.pag_personal)
        self.dia_personal.setObjectName("dia_personal")
        self.horizontalLayout_10.addWidget(self.dia_personal)
        self.combo_dia_personal = QtWidgets.QComboBox(self.pag_personal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_dia_personal.sizePolicy().hasHeightForWidth())
        self.combo_dia_personal.setSizePolicy(sizePolicy)
        self.combo_dia_personal.setMinimumSize(QtCore.QSize(145, 0))
        self.combo_dia_personal.setObjectName("combo_dia_personal")
        self.horizontalLayout_10.addWidget(self.combo_dia_personal)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_25)
        self.personal_table = QtWidgets.QTableWidget(self.pag_personal)
        self.personal_table.setObjectName("personal_table")
        self.personal_table.setColumnCount(0)
        self.personal_table.setRowCount(0)
        self.personal_table.horizontalHeader().setDefaultSectionSize(184)
        self.verticalLayout_3.addWidget(self.personal_table)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_add_personal = QtWidgets.QPushButton(self.pag_personal)
        self.button_add_personal.setMinimumSize(QtCore.QSize(65, 30))
        self.button_add_personal.setObjectName("button_add_personal")
        self.horizontalLayout_3.addWidget(self.button_add_personal)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.button_remove_personal = QtWidgets.QPushButton(self.pag_personal)
        self.button_remove_personal.setMinimumSize(QtCore.QSize(65, 30))
        self.button_remove_personal.setObjectName("button_remove_personal")
        self.horizontalLayout_3.addWidget(self.button_remove_personal)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.personal_added = QtWidgets.QTableWidget(self.pag_personal)
        self.personal_added.setObjectName("personal_added")
        self.personal_added.setColumnCount(0)
        self.personal_added.setRowCount(0)
        self.personal_added.horizontalHeader().setDefaultSectionSize(158)
        self.personal_added.horizontalHeader().setMinimumSectionSize(1)
        self.verticalLayout_5.addWidget(self.personal_added)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.buttonPersonalNext = QtWidgets.QPushButton(self.pag_personal)
        self.buttonPersonalNext.setMinimumSize(QtCore.QSize(65, 30))
        self.buttonPersonalNext.setObjectName("buttonPersonalNext")
        self.horizontalLayout_5.addWidget(self.buttonPersonalNext)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        self.tabWidget.addTab(self.pag_personal, "")
        self.pag_transportes = QtWidgets.QWidget()
        self.pag_transportes.setObjectName("pag_transportes")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.pag_transportes)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.labelSubtitle5 = QtWidgets.QLabel(self.pag_transportes)
        self.labelSubtitle5.setStyleSheet("")
        self.labelSubtitle5.setObjectName("labelSubtitle5")
        self.verticalLayout_10.addWidget(self.labelSubtitle5)
        spacerItem14 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem14)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelSubtitle1 = QtWidgets.QLabel(self.pag_transportes)
        self.labelSubtitle1.setMinimumSize(QtCore.QSize(0, 25))
        self.labelSubtitle1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSubtitle1.setObjectName("labelSubtitle1")
        self.verticalLayout_2.addWidget(self.labelSubtitle1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem15)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelEmpresa = QtWidgets.QLabel(self.pag_transportes)
        self.labelEmpresa.setMinimumSize(QtCore.QSize(140, 0))
        self.labelEmpresa.setObjectName("labelEmpresa")
        self.horizontalLayout_2.addWidget(self.labelEmpresa)
        self.comboEmpresa = QtWidgets.QComboBox(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboEmpresa.sizePolicy().hasHeightForWidth())
        self.comboEmpresa.setSizePolicy(sizePolicy)
        self.comboEmpresa.setMinimumSize(QtCore.QSize(173, 25))
        self.comboEmpresa.setObjectName("comboEmpresa")
        self.horizontalLayout_2.addWidget(self.comboEmpresa)
        self.buttonAddEmpresa = QtWidgets.QPushButton(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAddEmpresa.sizePolicy().hasHeightForWidth())
        self.buttonAddEmpresa.setSizePolicy(sizePolicy)
        self.buttonAddEmpresa.setObjectName("buttonAddEmpresa")
        self.horizontalLayout_2.addWidget(self.buttonAddEmpresa)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelConductor = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelConductor.sizePolicy().hasHeightForWidth())
        self.labelConductor.setSizePolicy(sizePolicy)
        self.labelConductor.setMinimumSize(QtCore.QSize(140, 0))
        self.labelConductor.setObjectName("labelConductor")
        self.horizontalLayout_8.addWidget(self.labelConductor)
        self.inputConductor = QtWidgets.QLineEdit(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputConductor.sizePolicy().hasHeightForWidth())
        self.inputConductor.setSizePolicy(sizePolicy)
        self.inputConductor.setMinimumSize(QtCore.QSize(270, 0))
        self.inputConductor.setObjectName("inputConductor")
        self.horizontalLayout_8.addWidget(self.inputConductor)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.labelTfnConductor = QtWidgets.QLabel(self.pag_transportes)
        self.labelTfnConductor.setMinimumSize(QtCore.QSize(140, 0))
        self.labelTfnConductor.setObjectName("labelTfnConductor")
        self.horizontalLayout_9.addWidget(self.labelTfnConductor)
        self.inputTfnConductor = QtWidgets.QLineEdit(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputTfnConductor.sizePolicy().hasHeightForWidth())
        self.inputTfnConductor.setSizePolicy(sizePolicy)
        self.inputTfnConductor.setMinimumSize(QtCore.QSize(270, 0))
        self.inputTfnConductor.setObjectName("inputTfnConductor")
        self.horizontalLayout_9.addWidget(self.inputTfnConductor)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.labelEmailConductor = QtWidgets.QLabel(self.pag_transportes)
        self.labelEmailConductor.setMinimumSize(QtCore.QSize(140, 0))
        self.labelEmailConductor.setObjectName("labelEmailConductor")
        self.horizontalLayout_11.addWidget(self.labelEmailConductor)
        self.inputEmailConductor = QtWidgets.QLineEdit(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputEmailConductor.sizePolicy().hasHeightForWidth())
        self.inputEmailConductor.setSizePolicy(sizePolicy)
        self.inputEmailConductor.setMinimumSize(QtCore.QSize(270, 0))
        self.inputEmailConductor.setObjectName("inputEmailConductor")
        self.horizontalLayout_11.addWidget(self.inputEmailConductor)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.labelTipo = QtWidgets.QLabel(self.pag_transportes)
        self.labelTipo.setMinimumSize(QtCore.QSize(140, 0))
        self.labelTipo.setObjectName("labelTipo")
        self.horizontalLayout_12.addWidget(self.labelTipo)
        self.inputTipo = QtWidgets.QLineEdit(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputTipo.sizePolicy().hasHeightForWidth())
        self.inputTipo.setSizePolicy(sizePolicy)
        self.inputTipo.setMinimumSize(QtCore.QSize(270, 0))
        self.inputTipo.setObjectName("inputTipo")
        self.horizontalLayout_12.addWidget(self.inputTipo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.pag_transportes)
        self.label_8.setMinimumSize(QtCore.QSize(140, 0))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_13.addWidget(self.label_8)
        self.inputMatricula = QtWidgets.QLineEdit(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputMatricula.sizePolicy().hasHeightForWidth())
        self.inputMatricula.setSizePolicy(sizePolicy)
        self.inputMatricula.setMinimumSize(QtCore.QSize(270, 0))
        self.inputMatricula.setObjectName("inputMatricula")
        self.horizontalLayout_13.addWidget(self.inputMatricula)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.labelNotas = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelNotas.sizePolicy().hasHeightForWidth())
        self.labelNotas.setSizePolicy(sizePolicy)
        self.labelNotas.setMinimumSize(QtCore.QSize(140, 0))
        self.labelNotas.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelNotas.setObjectName("labelNotas")
        self.horizontalLayout_14.addWidget(self.labelNotas)
        self.inputNotas = QtWidgets.QPlainTextEdit(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNotas.sizePolicy().hasHeightForWidth())
        self.inputNotas.setSizePolicy(sizePolicy)
        self.inputNotas.setMinimumSize(QtCore.QSize(270, 0))
        self.inputNotas.setObjectName("inputNotas")
        self.horizontalLayout_14.addWidget(self.inputNotas)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem16)
        self.horizontalLayout_44.addLayout(self.verticalLayout_2)
        spacerItem17 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem17)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelSubtitle2 = QtWidgets.QLabel(self.pag_transportes)
        self.labelSubtitle2.setMinimumSize(QtCore.QSize(0, 25))
        self.labelSubtitle2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSubtitle2.setObjectName("labelSubtitle2")
        self.verticalLayout_4.addWidget(self.labelSubtitle2)
        spacerItem18 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem18)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.buttonEventoR = QtWidgets.QPushButton(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonEventoR.sizePolicy().hasHeightForWidth())
        self.buttonEventoR.setSizePolicy(sizePolicy)
        self.buttonEventoR.setObjectName("buttonEventoR")
        self.horizontalLayout_41.addWidget(self.buttonEventoR)
        self.buttonAlmacenR = QtWidgets.QPushButton(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAlmacenR.sizePolicy().hasHeightForWidth())
        self.buttonAlmacenR.setSizePolicy(sizePolicy)
        self.buttonAlmacenR.setObjectName("buttonAlmacenR")
        self.horizontalLayout_41.addWidget(self.buttonAlmacenR)
        self.buttonOtroR = QtWidgets.QPushButton(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOtroR.sizePolicy().hasHeightForWidth())
        self.buttonOtroR.setSizePolicy(sizePolicy)
        self.buttonOtroR.setObjectName("buttonOtroR")
        self.horizontalLayout_41.addWidget(self.buttonOtroR)
        self.verticalLayout_4.addLayout(self.horizontalLayout_41)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem19)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.labelRecintoR = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRecintoR.sizePolicy().hasHeightForWidth())
        self.labelRecintoR.setSizePolicy(sizePolicy)
        self.labelRecintoR.setMinimumSize(QtCore.QSize(100, 0))
        self.labelRecintoR.setObjectName("labelRecintoR")
        self.horizontalLayout_15.addWidget(self.labelRecintoR)
        self.inputRecintoR = QtWidgets.QLineEdit(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputRecintoR.sizePolicy().hasHeightForWidth())
        self.inputRecintoR.setSizePolicy(sizePolicy)
        self.inputRecintoR.setMinimumSize(QtCore.QSize(250, 0))
        self.inputRecintoR.setObjectName("inputRecintoR")
        self.horizontalLayout_15.addWidget(self.inputRecintoR)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.labelPaisR = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPaisR.sizePolicy().hasHeightForWidth())
        self.labelPaisR.setSizePolicy(sizePolicy)
        self.labelPaisR.setMinimumSize(QtCore.QSize(100, 0))
        self.labelPaisR.setObjectName("labelPaisR")
        self.horizontalLayout_16.addWidget(self.labelPaisR)
        self.comboPaisR = QtWidgets.QComboBox(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboPaisR.sizePolicy().hasHeightForWidth())
        self.comboPaisR.setSizePolicy(sizePolicy)
        self.comboPaisR.setMinimumSize(QtCore.QSize(250, 25))
        self.comboPaisR.setObjectName("comboPaisR")
        self.horizontalLayout_16.addWidget(self.comboPaisR)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.labelProvinciaR = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelProvinciaR.sizePolicy().hasHeightForWidth())
        self.labelProvinciaR.setSizePolicy(sizePolicy)
        self.labelProvinciaR.setMinimumSize(QtCore.QSize(100, 0))
        self.labelProvinciaR.setObjectName("labelProvinciaR")
        self.horizontalLayout_17.addWidget(self.labelProvinciaR)
        self.comboProvinciaR = QtWidgets.QComboBox(self.pag_transportes)
        self.comboProvinciaR.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboProvinciaR.sizePolicy().hasHeightForWidth())
        self.comboProvinciaR.setSizePolicy(sizePolicy)
        self.comboProvinciaR.setMinimumSize(QtCore.QSize(250, 25))
        self.comboProvinciaR.setObjectName("comboProvinciaR")
        self.horizontalLayout_17.addWidget(self.comboProvinciaR)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.labelLocalidadR = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLocalidadR.sizePolicy().hasHeightForWidth())
        self.labelLocalidadR.setSizePolicy(sizePolicy)
        self.labelLocalidadR.setMinimumSize(QtCore.QSize(100, 0))
        self.labelLocalidadR.setObjectName("labelLocalidadR")
        self.horizontalLayout_20.addWidget(self.labelLocalidadR)
        self.inputLocalidadR = QtWidgets.QLineEdit(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputLocalidadR.sizePolicy().hasHeightForWidth())
        self.inputLocalidadR.setSizePolicy(sizePolicy)
        self.inputLocalidadR.setMinimumSize(QtCore.QSize(250, 0))
        self.inputLocalidadR.setObjectName("inputLocalidadR")
        self.horizontalLayout_20.addWidget(self.inputLocalidadR)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.labelDireccionR = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDireccionR.sizePolicy().hasHeightForWidth())
        self.labelDireccionR.setSizePolicy(sizePolicy)
        self.labelDireccionR.setMinimumSize(QtCore.QSize(100, 0))
        self.labelDireccionR.setObjectName("labelDireccionR")
        self.horizontalLayout_22.addWidget(self.labelDireccionR)
        self.inputDireccionR = QtWidgets.QLineEdit(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputDireccionR.sizePolicy().hasHeightForWidth())
        self.inputDireccionR.setSizePolicy(sizePolicy)
        self.inputDireccionR.setMinimumSize(QtCore.QSize(250, 0))
        self.inputDireccionR.setObjectName("inputDireccionR")
        self.horizontalLayout_22.addWidget(self.inputDireccionR)
        self.verticalLayout_4.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.labelIndicacionesR = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelIndicacionesR.sizePolicy().hasHeightForWidth())
        self.labelIndicacionesR.setSizePolicy(sizePolicy)
        self.labelIndicacionesR.setMinimumSize(QtCore.QSize(100, 0))
        self.labelIndicacionesR.setObjectName("labelIndicacionesR")
        self.horizontalLayout_39.addWidget(self.labelIndicacionesR)
        self.inputIndicacionesR = QtWidgets.QLineEdit(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputIndicacionesR.sizePolicy().hasHeightForWidth())
        self.inputIndicacionesR.setSizePolicy(sizePolicy)
        self.inputIndicacionesR.setMinimumSize(QtCore.QSize(250, 0))
        self.inputIndicacionesR.setObjectName("inputIndicacionesR")
        self.horizontalLayout_39.addWidget(self.inputIndicacionesR)
        self.verticalLayout_4.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.labelCoordenadasR = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCoordenadasR.sizePolicy().hasHeightForWidth())
        self.labelCoordenadasR.setSizePolicy(sizePolicy)
        self.labelCoordenadasR.setMinimumSize(QtCore.QSize(100, 0))
        self.labelCoordenadasR.setObjectName("labelCoordenadasR")
        self.horizontalLayout_37.addWidget(self.labelCoordenadasR)
        self.inputCoordenadasR = QtWidgets.QLineEdit(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputCoordenadasR.sizePolicy().hasHeightForWidth())
        self.inputCoordenadasR.setSizePolicy(sizePolicy)
        self.inputCoordenadasR.setMinimumSize(QtCore.QSize(200, 0))
        self.inputCoordenadasR.setObjectName("inputCoordenadasR")
        self.horizontalLayout_37.addWidget(self.inputCoordenadasR)
        self.buttonCopyR = QtWidgets.QPushButton(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCopyR.sizePolicy().hasHeightForWidth())
        self.buttonCopyR.setSizePolicy(sizePolicy)
        self.buttonCopyR.setMinimumSize(QtCore.QSize(45, 20))
        self.buttonCopyR.setMaximumSize(QtCore.QSize(35, 25))
        self.buttonCopyR.setObjectName("buttonCopyR")
        self.horizontalLayout_37.addWidget(self.buttonCopyR)
        self.verticalLayout_4.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.laelFechaR = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.laelFechaR.sizePolicy().hasHeightForWidth())
        self.laelFechaR.setSizePolicy(sizePolicy)
        self.laelFechaR.setMinimumSize(QtCore.QSize(100, 0))
        self.laelFechaR.setObjectName("laelFechaR")
        self.horizontalLayout_23.addWidget(self.laelFechaR)
        self.comboFechaR = QtWidgets.QComboBox(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboFechaR.sizePolicy().hasHeightForWidth())
        self.comboFechaR.setSizePolicy(sizePolicy)
        self.comboFechaR.setMinimumSize(QtCore.QSize(250, 25))
        self.comboFechaR.setObjectName("comboFechaR")
        self.horizontalLayout_23.addWidget(self.comboFechaR)
        self.verticalLayout_4.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.labelHoraR = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHoraR.sizePolicy().hasHeightForWidth())
        self.labelHoraR.setSizePolicy(sizePolicy)
        self.labelHoraR.setMinimumSize(QtCore.QSize(100, 0))
        self.labelHoraR.setObjectName("labelHoraR")
        self.horizontalLayout_28.addWidget(self.labelHoraR)
        self.horaR = QtWidgets.QTimeEdit(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horaR.sizePolicy().hasHeightForWidth())
        self.horaR.setSizePolicy(sizePolicy)
        self.horaR.setMinimumSize(QtCore.QSize(250, 0))
        self.horaR.setAlignment(QtCore.Qt.AlignCenter)
        self.horaR.setObjectName("horaR")
        self.horizontalLayout_28.addWidget(self.horaR)
        self.verticalLayout_4.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_43.addLayout(self.verticalLayout_4)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem20)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelSubtitle3 = QtWidgets.QLabel(self.pag_transportes)
        self.labelSubtitle3.setMinimumSize(QtCore.QSize(0, 25))
        self.labelSubtitle3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSubtitle3.setObjectName("labelSubtitle3")
        self.verticalLayout_8.addWidget(self.labelSubtitle3)
        spacerItem21 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem21)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.buttonEventoE = QtWidgets.QPushButton(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonEventoE.sizePolicy().hasHeightForWidth())
        self.buttonEventoE.setSizePolicy(sizePolicy)
        self.buttonEventoE.setObjectName("buttonEventoE")
        self.horizontalLayout_42.addWidget(self.buttonEventoE)
        self.buttonAlmacenE = QtWidgets.QPushButton(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAlmacenE.sizePolicy().hasHeightForWidth())
        self.buttonAlmacenE.setSizePolicy(sizePolicy)
        self.buttonAlmacenE.setObjectName("buttonAlmacenE")
        self.horizontalLayout_42.addWidget(self.buttonAlmacenE)
        self.buttonOtroE = QtWidgets.QPushButton(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOtroE.sizePolicy().hasHeightForWidth())
        self.buttonOtroE.setSizePolicy(sizePolicy)
        self.buttonOtroE.setObjectName("buttonOtroE")
        self.horizontalLayout_42.addWidget(self.buttonOtroE)
        self.verticalLayout_8.addLayout(self.horizontalLayout_42)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem22)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.labelRecintoE = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRecintoE.sizePolicy().hasHeightForWidth())
        self.labelRecintoE.setSizePolicy(sizePolicy)
        self.labelRecintoE.setMinimumSize(QtCore.QSize(100, 0))
        self.labelRecintoE.setObjectName("labelRecintoE")
        self.horizontalLayout_29.addWidget(self.labelRecintoE)
        self.inputRecintoE = QtWidgets.QLineEdit(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputRecintoE.sizePolicy().hasHeightForWidth())
        self.inputRecintoE.setSizePolicy(sizePolicy)
        self.inputRecintoE.setMinimumSize(QtCore.QSize(250, 0))
        self.inputRecintoE.setObjectName("inputRecintoE")
        self.horizontalLayout_29.addWidget(self.inputRecintoE)
        self.verticalLayout_8.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.labelPaisE = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPaisE.sizePolicy().hasHeightForWidth())
        self.labelPaisE.setSizePolicy(sizePolicy)
        self.labelPaisE.setMinimumSize(QtCore.QSize(100, 0))
        self.labelPaisE.setObjectName("labelPaisE")
        self.horizontalLayout_30.addWidget(self.labelPaisE)
        self.comboPaisE = QtWidgets.QComboBox(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboPaisE.sizePolicy().hasHeightForWidth())
        self.comboPaisE.setSizePolicy(sizePolicy)
        self.comboPaisE.setMinimumSize(QtCore.QSize(250, 25))
        self.comboPaisE.setObjectName("comboPaisE")
        self.horizontalLayout_30.addWidget(self.comboPaisE)
        self.verticalLayout_8.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.labelProvinciaE = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelProvinciaE.sizePolicy().hasHeightForWidth())
        self.labelProvinciaE.setSizePolicy(sizePolicy)
        self.labelProvinciaE.setMinimumSize(QtCore.QSize(100, 0))
        self.labelProvinciaE.setObjectName("labelProvinciaE")
        self.horizontalLayout_31.addWidget(self.labelProvinciaE)
        self.comboProvinciaE = QtWidgets.QComboBox(self.pag_transportes)
        self.comboProvinciaE.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboProvinciaE.sizePolicy().hasHeightForWidth())
        self.comboProvinciaE.setSizePolicy(sizePolicy)
        self.comboProvinciaE.setMinimumSize(QtCore.QSize(250, 25))
        self.comboProvinciaE.setObjectName("comboProvinciaE")
        self.horizontalLayout_31.addWidget(self.comboProvinciaE)
        self.verticalLayout_8.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.labelLocalidadE = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLocalidadE.sizePolicy().hasHeightForWidth())
        self.labelLocalidadE.setSizePolicy(sizePolicy)
        self.labelLocalidadE.setMinimumSize(QtCore.QSize(100, 0))
        self.labelLocalidadE.setObjectName("labelLocalidadE")
        self.horizontalLayout_32.addWidget(self.labelLocalidadE)
        self.inputLocalidadE = QtWidgets.QLineEdit(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputLocalidadE.sizePolicy().hasHeightForWidth())
        self.inputLocalidadE.setSizePolicy(sizePolicy)
        self.inputLocalidadE.setMinimumSize(QtCore.QSize(250, 0))
        self.inputLocalidadE.setObjectName("inputLocalidadE")
        self.horizontalLayout_32.addWidget(self.inputLocalidadE)
        self.verticalLayout_8.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.labelDireccionE = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDireccionE.sizePolicy().hasHeightForWidth())
        self.labelDireccionE.setSizePolicy(sizePolicy)
        self.labelDireccionE.setMinimumSize(QtCore.QSize(100, 0))
        self.labelDireccionE.setObjectName("labelDireccionE")
        self.horizontalLayout_33.addWidget(self.labelDireccionE)
        self.inputDireccionE = QtWidgets.QLineEdit(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputDireccionE.sizePolicy().hasHeightForWidth())
        self.inputDireccionE.setSizePolicy(sizePolicy)
        self.inputDireccionE.setMinimumSize(QtCore.QSize(250, 0))
        self.inputDireccionE.setObjectName("inputDireccionE")
        self.horizontalLayout_33.addWidget(self.inputDireccionE)
        self.verticalLayout_8.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.labelIndicacionesE = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelIndicacionesE.sizePolicy().hasHeightForWidth())
        self.labelIndicacionesE.setSizePolicy(sizePolicy)
        self.labelIndicacionesE.setMinimumSize(QtCore.QSize(100, 0))
        self.labelIndicacionesE.setObjectName("labelIndicacionesE")
        self.horizontalLayout_40.addWidget(self.labelIndicacionesE)
        self.inputIndicacionesE = QtWidgets.QLineEdit(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputIndicacionesE.sizePolicy().hasHeightForWidth())
        self.inputIndicacionesE.setSizePolicy(sizePolicy)
        self.inputIndicacionesE.setMinimumSize(QtCore.QSize(250, 0))
        self.inputIndicacionesE.setObjectName("inputIndicacionesE")
        self.horizontalLayout_40.addWidget(self.inputIndicacionesE)
        self.verticalLayout_8.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.labelCoordenadasE = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCoordenadasE.sizePolicy().hasHeightForWidth())
        self.labelCoordenadasE.setSizePolicy(sizePolicy)
        self.labelCoordenadasE.setMinimumSize(QtCore.QSize(100, 0))
        self.labelCoordenadasE.setObjectName("labelCoordenadasE")
        self.horizontalLayout_38.addWidget(self.labelCoordenadasE)
        self.inputCoordenadasE = QtWidgets.QLineEdit(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputCoordenadasE.sizePolicy().hasHeightForWidth())
        self.inputCoordenadasE.setSizePolicy(sizePolicy)
        self.inputCoordenadasE.setMinimumSize(QtCore.QSize(200, 0))
        self.inputCoordenadasE.setObjectName("inputCoordenadasE")
        self.horizontalLayout_38.addWidget(self.inputCoordenadasE)
        self.buttonCopyE = QtWidgets.QPushButton(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCopyE.sizePolicy().hasHeightForWidth())
        self.buttonCopyE.setSizePolicy(sizePolicy)
        self.buttonCopyE.setMinimumSize(QtCore.QSize(45, 20))
        self.buttonCopyE.setMaximumSize(QtCore.QSize(35, 25))
        self.buttonCopyE.setObjectName("buttonCopyE")
        self.horizontalLayout_38.addWidget(self.buttonCopyE)
        self.verticalLayout_8.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.labelFechaE = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFechaE.sizePolicy().hasHeightForWidth())
        self.labelFechaE.setSizePolicy(sizePolicy)
        self.labelFechaE.setMinimumSize(QtCore.QSize(100, 0))
        self.labelFechaE.setObjectName("labelFechaE")
        self.horizontalLayout_34.addWidget(self.labelFechaE)
        self.comboFechaE = QtWidgets.QComboBox(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboFechaE.sizePolicy().hasHeightForWidth())
        self.comboFechaE.setSizePolicy(sizePolicy)
        self.comboFechaE.setMinimumSize(QtCore.QSize(250, 25))
        self.comboFechaE.setObjectName("comboFechaE")
        self.horizontalLayout_34.addWidget(self.comboFechaE)
        self.verticalLayout_8.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.labelHoraE = QtWidgets.QLabel(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHoraE.sizePolicy().hasHeightForWidth())
        self.labelHoraE.setSizePolicy(sizePolicy)
        self.labelHoraE.setMinimumSize(QtCore.QSize(100, 0))
        self.labelHoraE.setObjectName("labelHoraE")
        self.horizontalLayout_35.addWidget(self.labelHoraE)
        self.horaE = QtWidgets.QTimeEdit(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horaE.sizePolicy().hasHeightForWidth())
        self.horaE.setSizePolicy(sizePolicy)
        self.horaE.setMinimumSize(QtCore.QSize(250, 0))
        self.horaE.setAlignment(QtCore.Qt.AlignCenter)
        self.horaE.setObjectName("horaE")
        self.horizontalLayout_35.addWidget(self.horaE)
        self.verticalLayout_8.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_43.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_43)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_9.addItem(spacerItem23)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.buttonAddTrans = QtWidgets.QPushButton(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAddTrans.sizePolicy().hasHeightForWidth())
        self.buttonAddTrans.setSizePolicy(sizePolicy)
        self.buttonAddTrans.setMinimumSize(QtCore.QSize(225, 30))
        self.buttonAddTrans.setObjectName("buttonAddTrans")
        self.horizontalLayout_36.addWidget(self.buttonAddTrans)
        self.buttonDelTrans = QtWidgets.QPushButton(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDelTrans.sizePolicy().hasHeightForWidth())
        self.buttonDelTrans.setSizePolicy(sizePolicy)
        self.buttonDelTrans.setMinimumSize(QtCore.QSize(225, 30))
        self.buttonDelTrans.setObjectName("buttonDelTrans")
        self.horizontalLayout_36.addWidget(self.buttonDelTrans)
        self.buttonNext = QtWidgets.QPushButton(self.pag_transportes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNext.sizePolicy().hasHeightForWidth())
        self.buttonNext.setSizePolicy(sizePolicy)
        self.buttonNext.setMinimumSize(QtCore.QSize(225, 30))
        self.buttonNext.setObjectName("buttonNext")
        self.horizontalLayout_36.addWidget(self.buttonNext)
        self.verticalLayout_9.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_44.addLayout(self.verticalLayout_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_44)
        spacerItem24 = QtWidgets.QSpacerItem(20, 57, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem24)
        self.labelSubtitle4 = QtWidgets.QLabel(self.pag_transportes)
        self.labelSubtitle4.setObjectName("labelSubtitle4")
        self.verticalLayout_10.addWidget(self.labelSubtitle4)
        self.tableTransportes = QtWidgets.QTableWidget(self.pag_transportes)
        self.tableTransportes.setObjectName("tableTransportes")
        self.tableTransportes.setColumnCount(0)
        self.tableTransportes.setRowCount(0)
        self.verticalLayout_10.addWidget(self.tableTransportes)
        self.tabWidget.addTab(self.pag_transportes, "")
        self.pag_proveedores = QtWidgets.QWidget()
        self.pag_proveedores.setObjectName("pag_proveedores")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.pag_proveedores)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.labelTitle5 = QtWidgets.QLabel(self.pag_proveedores)
        self.labelTitle5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelTitle5.setObjectName("labelTitle5")
        self.horizontalLayout_26.addWidget(self.labelTitle5)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem25)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.nombre_prov = QtWidgets.QLabel(self.pag_proveedores)
        self.nombre_prov.setObjectName("nombre_prov")
        self.horizontalLayout_27.addWidget(self.nombre_prov)
        self.entry_nombre_prov = QtWidgets.QLineEdit(self.pag_proveedores)
        self.entry_nombre_prov.setMinimumSize(QtCore.QSize(180, 0))
        self.entry_nombre_prov.setObjectName("entry_nombre_prov")
        self.horizontalLayout_27.addWidget(self.entry_nombre_prov)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_27)
        self.buttonBuscarProv = QtWidgets.QPushButton(self.pag_proveedores)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBuscarProv.sizePolicy().hasHeightForWidth())
        self.buttonBuscarProv.setSizePolicy(sizePolicy)
        self.buttonBuscarProv.setMinimumSize(QtCore.QSize(65, 30))
        self.buttonBuscarProv.setObjectName("buttonBuscarProv")
        self.horizontalLayout_26.addWidget(self.buttonBuscarProv)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem26)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.filtrar_serv = QtWidgets.QLabel(self.pag_proveedores)
        self.filtrar_serv.setObjectName("filtrar_serv")
        self.horizontalLayout_21.addWidget(self.filtrar_serv)
        self.combo_filtrar_serv = QtWidgets.QComboBox(self.pag_proveedores)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_filtrar_serv.sizePolicy().hasHeightForWidth())
        self.combo_filtrar_serv.setSizePolicy(sizePolicy)
        self.combo_filtrar_serv.setMinimumSize(QtCore.QSize(145, 0))
        self.combo_filtrar_serv.setObjectName("combo_filtrar_serv")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.combo_filtrar_serv.addItem("")
        self.horizontalLayout_21.addWidget(self.combo_filtrar_serv)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_21)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem27)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.dia_prov = QtWidgets.QLabel(self.pag_proveedores)
        self.dia_prov.setObjectName("dia_prov")
        self.horizontalLayout_18.addWidget(self.dia_prov)
        self.combo_dia_prov = QtWidgets.QComboBox(self.pag_proveedores)
        self.combo_dia_prov.setMinimumSize(QtCore.QSize(145, 0))
        self.combo_dia_prov.setObjectName("combo_dia_prov")
        self.horizontalLayout_18.addWidget(self.combo_dia_prov)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_18)
        self.verticalLayout_7.addLayout(self.horizontalLayout_26)
        self.prov_table = QtWidgets.QTableWidget(self.pag_proveedores)
        self.prov_table.setObjectName("prov_table")
        self.prov_table.setColumnCount(0)
        self.prov_table.setRowCount(0)
        self.verticalLayout_7.addWidget(self.prov_table)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.button_add_prov = QtWidgets.QPushButton(self.pag_proveedores)
        self.button_add_prov.setMinimumSize(QtCore.QSize(65, 30))
        self.button_add_prov.setObjectName("button_add_prov")
        self.horizontalLayout_6.addWidget(self.button_add_prov)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem28)
        self.button_remove_prov = QtWidgets.QPushButton(self.pag_proveedores)
        self.button_remove_prov.setMinimumSize(QtCore.QSize(65, 30))
        self.button_remove_prov.setObjectName("button_remove_prov")
        self.horizontalLayout_6.addWidget(self.button_remove_prov)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.prov_added = QtWidgets.QTableWidget(self.pag_proveedores)
        self.prov_added.setObjectName("prov_added")
        self.prov_added.setColumnCount(0)
        self.prov_added.setRowCount(0)
        self.verticalLayout_6.addWidget(self.prov_added)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.buttonProvOk = QtWidgets.QPushButton(self.pag_proveedores)
        self.buttonProvOk.setMinimumSize(QtCore.QSize(65, 30))
        self.buttonProvOk.setObjectName("buttonProvOk")
        self.horizontalLayout_7.addWidget(self.buttonProvOk)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem29)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.pag_proveedores, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 1, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.entry_id, self.entry_nombre)
        Form.setTabOrder(self.entry_nombre, self.comboBox_2)
        Form.setTabOrder(self.comboBox_2, self.comboBox)
        Form.setTabOrder(self.comboBox, self.combo_manager)
        Form.setTabOrder(self.combo_manager, self.entry_onsite)
        Form.setTabOrder(self.entry_onsite, self.entry_tfn_onsite)
        Form.setTabOrder(self.entry_tfn_onsite, self.entry_email_onsite)
        Form.setTabOrder(self.entry_email_onsite, self.entry_notas)
        Form.setTabOrder(self.entry_notas, self.buttonAddRecinto)
        Form.setTabOrder(self.buttonAddRecinto, self.buttonAddManager)
        Form.setTabOrder(self.buttonAddManager, self.time)
        Form.setTabOrder(self.time, self.combo_tarea)
        Form.setTabOrder(self.combo_tarea, self.calendar)
        Form.setTabOrder(self.calendar, self.buttonAddDate)
        Form.setTabOrder(self.buttonAddDate, self.buttonDelDate)
        Form.setTabOrder(self.buttonDelDate, self.buttonFechaNext)
        Form.setTabOrder(self.buttonFechaNext, self.fechas_table)
        Form.setTabOrder(self.fechas_table, self.entry_nombre_personal)
        Form.setTabOrder(self.entry_nombre_personal, self.buttonBuscarPers)
        Form.setTabOrder(self.buttonBuscarPers, self.combo_filtrar_cargos)
        Form.setTabOrder(self.combo_filtrar_cargos, self.combo_dia_personal)
        Form.setTabOrder(self.combo_dia_personal, self.personal_table)
        Form.setTabOrder(self.personal_table, self.button_add_personal)
        Form.setTabOrder(self.button_add_personal, self.button_remove_personal)
        Form.setTabOrder(self.button_remove_personal, self.personal_added)
        Form.setTabOrder(self.personal_added, self.buttonPersonalNext)
        Form.setTabOrder(self.buttonPersonalNext, self.entry_nombre_prov)
        Form.setTabOrder(self.entry_nombre_prov, self.buttonBuscarProv)
        Form.setTabOrder(self.buttonBuscarProv, self.combo_filtrar_serv)
        Form.setTabOrder(self.combo_filtrar_serv, self.combo_dia_prov)
        Form.setTabOrder(self.combo_dia_prov, self.prov_table)
        Form.setTabOrder(self.prov_table, self.button_add_prov)
        Form.setTabOrder(self.button_add_prov, self.button_remove_prov)
        Form.setTabOrder(self.button_remove_prov, self.prov_added)
        Form.setTabOrder(self.prov_added, self.buttonProvOk)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.buttonSelect.setText(_translate("Form", "Seleccionar"))
        self.buttonAddCliente.setText(_translate("Form", "+"))
        self.notas.setText(_translate("Form", "Notas"))
        self.email_onsite.setText(_translate("Form", "Email On Site"))
        self.labelTitle.setText(_translate("Form", "Crear Evento"))
        self.nombre.setText(_translate("Form", "Nombre"))
        self.id.setText(_translate("Form", "ID Evento"))
        self.buttonDatosNext.setText(_translate("Form", "Guardar"))
        self.cliente.setText(_translate("Form", "Cliente"))
        self.recinto.setText(_translate("Form", "Recinto"))
        self.labelTitle2.setText(_translate("Form", "DATOS"))
        self.buttonAddManager.setText(_translate("Form", "+"))
        self.manager.setText(_translate("Form", "Project Manager"))
        self.tfn_onsite.setText(_translate("Form", "Teléfono On Site"))
        self.onsite.setText(_translate("Form", "Contacto On Site"))
        self.buttonAddRecinto.setText(_translate("Form", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pag_datos), _translate("Form", "Datos del evento"))
        self.labelHora.setText(_translate("Form", "Hora prevista"))
        self.time.setDisplayFormat(_translate("Form", "HH:mm"))
        self.labelTarea.setText(_translate("Form", "Tarea"))
        self.combo_tarea.setItemText(1, _translate("Form", "Carga"))
        self.combo_tarea.setItemText(2, _translate("Form", "Descarga"))
        self.combo_tarea.setItemText(3, _translate("Form", "Montaje"))
        self.combo_tarea.setItemText(4, _translate("Form", "Pruebas"))
        self.combo_tarea.setItemText(5, _translate("Form", "Evento"))
        self.combo_tarea.setItemText(6, _translate("Form", "Desmontaje"))
        self.combo_tarea.setItemText(7, _translate("Form", "Produccion"))
        self.combo_tarea.setItemText(8, _translate("Form", "Viaje"))
        self.combo_tarea.setItemText(9, _translate("Form", "Almacén"))
        self.buttonAddDate.setText(_translate("Form", "Añadir fecha"))
        self.buttonModificar.setToolTip(_translate("Form", "Selecciona parametros y fila y pulse aquí"))
        self.buttonModificar.setText(_translate("Form", "Modificar fecha"))
        self.buttonDelDate.setText(_translate("Form", "Eliminar fecha"))
        self.buttonFechaNext.setText(_translate("Form", "Guardar"))
        item = self.fechas_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Fecha"))
        item = self.fechas_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Hora"))
        item = self.fechas_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Tarea"))
        item = self.fechas_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Id Fecha"))
        self.labelTitle3.setText(_translate("Form", "Fechas del Evento"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pag_fechas), _translate("Form", "Fechas del evento"))
        self.labelTitle4.setText(_translate("Form", "PERSONAL"))
        self.nombre_personal.setText(_translate("Form", "Nombre"))
        self.buttonBuscarPers.setText(_translate("Form", "Buscar"))
        self.filtrar_cargos.setText(_translate("Form", "Filtrar Cargos"))
        self.combo_filtrar_cargos.setItemText(0, _translate("Form", "All"))
        self.combo_filtrar_cargos.setItemText(1, _translate("Form", "Crew Chief"))
        self.combo_filtrar_cargos.setItemText(2, _translate("Form", "Operador de Luces"))
        self.combo_filtrar_cargos.setItemText(3, _translate("Form", "Dimmers"))
        self.combo_filtrar_cargos.setItemText(4, _translate("Form", "Técnico de Luces"))
        self.combo_filtrar_cargos.setItemText(5, _translate("Form", "Operador de Sonido"))
        self.combo_filtrar_cargos.setItemText(6, _translate("Form", "RF"))
        self.combo_filtrar_cargos.setItemText(7, _translate("Form", "Técnico de Sonido"))
        self.combo_filtrar_cargos.setItemText(8, _translate("Form", "Operador de Video"))
        self.combo_filtrar_cargos.setItemText(9, _translate("Form", "Led"))
        self.combo_filtrar_cargos.setItemText(10, _translate("Form", "Técnico de Video"))
        self.combo_filtrar_cargos.setItemText(11, _translate("Form", "Rigger"))
        self.combo_filtrar_cargos.setItemText(12, _translate("Form", "Regidor"))
        self.combo_filtrar_cargos.setItemText(13, _translate("Form", "Contenidos"))
        self.combo_filtrar_cargos.setItemText(14, _translate("Form", "Deco"))
        self.dia_personal.setText(_translate("Form", "Día"))
        self.button_add_personal.setText(_translate("Form", "Añadir"))
        self.button_remove_personal.setText(_translate("Form", "Quitar"))
        self.buttonPersonalNext.setText(_translate("Form", "OK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pag_personal), _translate("Form", "Personal"))
        self.labelSubtitle5.setText(_translate("Form", "TRANSPORTES"))
        self.labelSubtitle1.setText(_translate("Form", "Datos"))
        self.labelEmpresa.setText(_translate("Form", "Empresa"))
        self.buttonAddEmpresa.setText(_translate("Form", "Nueva"))
        self.labelConductor.setText(_translate("Form", "Conductor"))
        self.labelTfnConductor.setText(_translate("Form", "Teléfono conductor"))
        self.labelEmailConductor.setText(_translate("Form", "Email conductor"))
        self.labelTipo.setText(_translate("Form", "Tipo de vehículo"))
        self.label_8.setText(_translate("Form", "Matrícula"))
        self.labelNotas.setText(_translate("Form", "Notas"))
        self.labelSubtitle2.setText(_translate("Form", "Recogida"))
        self.buttonEventoR.setText(_translate("Form", "Evento"))
        self.buttonAlmacenR.setText(_translate("Form", "Almacén"))
        self.buttonOtroR.setText(_translate("Form", "Otro recinto"))
        self.labelRecintoR.setText(_translate("Form", "Recinto"))
        self.labelPaisR.setText(_translate("Form", "País"))
        self.labelProvinciaR.setText(_translate("Form", "Provincia"))
        self.labelLocalidadR.setText(_translate("Form", "Localidad"))
        self.labelDireccionR.setText(_translate("Form", "Dirección"))
        self.labelIndicacionesR.setText(_translate("Form", "Indicaciones"))
        self.labelCoordenadasR.setText(_translate("Form", "Coordenadas"))
        self.buttonCopyR.setText(_translate("Form", "Copy"))
        self.laelFechaR.setText(_translate("Form", "Fecha"))
        self.labelHoraR.setText(_translate("Form", "Hora"))
        self.labelSubtitle3.setText(_translate("Form", "Entrega"))
        self.buttonEventoE.setText(_translate("Form", "Evento"))
        self.buttonAlmacenE.setText(_translate("Form", "Almacén"))
        self.buttonOtroE.setText(_translate("Form", "Otro recinto"))
        self.labelRecintoE.setText(_translate("Form", "Recinto"))
        self.labelPaisE.setText(_translate("Form", "País"))
        self.labelProvinciaE.setText(_translate("Form", "Provincia"))
        self.labelLocalidadE.setText(_translate("Form", "Localidad"))
        self.labelDireccionE.setText(_translate("Form", "Dirección"))
        self.labelIndicacionesE.setText(_translate("Form", "Indicaciones"))
        self.labelCoordenadasE.setText(_translate("Form", "Coordenadas"))
        self.buttonCopyE.setText(_translate("Form", "Copy"))
        self.labelFechaE.setText(_translate("Form", "Fecha"))
        self.labelHoraE.setText(_translate("Form", "Hora"))
        self.buttonAddTrans.setText(_translate("Form", "Añadir"))
        self.buttonDelTrans.setText(_translate("Form", "Eliminar"))
        self.buttonNext.setText(_translate("Form", "Siguiente"))
        self.labelSubtitle4.setText(_translate("Form", "Transportes programados"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pag_transportes), _translate("Form", "Transportes"))
        self.labelTitle5.setText(_translate("Form", "PROVEEDORES"))
        self.nombre_prov.setText(_translate("Form", "Nombre"))
        self.buttonBuscarProv.setText(_translate("Form", "Buscar"))
        self.filtrar_serv.setText(_translate("Form", "Filtrar Servicio"))
        self.combo_filtrar_serv.setItemText(0, _translate("Form", "All"))
        self.combo_filtrar_serv.setItemText(1, _translate("Form", "Runner"))
        self.combo_filtrar_serv.setItemText(2, _translate("Form", "Carga/Descarga"))
        self.combo_filtrar_serv.setItemText(3, _translate("Form", "Rigging"))
        self.combo_filtrar_serv.setItemText(4, _translate("Form", "Deco"))
        self.combo_filtrar_serv.setItemText(5, _translate("Form", "Generadores"))
        self.combo_filtrar_serv.setItemText(6, _translate("Form", "Traducción"))
        self.combo_filtrar_serv.setItemText(7, _translate("Form", "Catering"))
        self.combo_filtrar_serv.setItemText(8, _translate("Form", "Iluminación"))
        self.combo_filtrar_serv.setItemText(9, _translate("Form", "Sonido"))
        self.combo_filtrar_serv.setItemText(10, _translate("Form", "Video"))
        self.combo_filtrar_serv.setItemText(11, _translate("Form", "Mobiliario"))
        self.combo_filtrar_serv.setItemText(12, _translate("Form", "Otros"))
        self.dia_prov.setText(_translate("Form", "Día"))
        self.button_add_prov.setText(_translate("Form", "Añadir"))
        self.button_remove_prov.setText(_translate("Form", "Quitar"))
        self.buttonProvOk.setText(_translate("Form", "OK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pag_proveedores), _translate("Form", "Proveedores"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = CrearEvento_Ui()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

