# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fichaevento_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class FichaEvento_Ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1185, 600)
        Form.setStyleSheet("")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelTitle = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle.sizePolicy().hasHeightForWidth())
        self.labelTitle.setSizePolicy(sizePolicy)
        self.labelTitle.setMinimumSize(QtCore.QSize(0, 0))
        self.labelTitle.setStyleSheet("")
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout_3.addWidget(self.labelTitle)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout.setObjectName("formLayout")
        self.labelId = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelId.sizePolicy().hasHeightForWidth())
        self.labelId.setSizePolicy(sizePolicy)
        self.labelId.setMinimumSize(QtCore.QSize(125, 0))
        self.labelId.setObjectName("labelId")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelId)
        self.inputId = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputId.sizePolicy().hasHeightForWidth())
        self.inputId.setSizePolicy(sizePolicy)
        self.inputId.setMinimumSize(QtCore.QSize(200, 0))
        self.inputId.setReadOnly(True)
        self.inputId.setObjectName("inputId")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inputId)
        self.labelNombre = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelNombre.sizePolicy().hasHeightForWidth())
        self.labelNombre.setSizePolicy(sizePolicy)
        self.labelNombre.setMinimumSize(QtCore.QSize(125, 0))
        self.labelNombre.setObjectName("labelNombre")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelNombre)
        self.inputNombre = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNombre.sizePolicy().hasHeightForWidth())
        self.inputNombre.setSizePolicy(sizePolicy)
        self.inputNombre.setMinimumSize(QtCore.QSize(200, 0))
        self.inputNombre.setReadOnly(True)
        self.inputNombre.setObjectName("inputNombre")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inputNombre)
        self.labelCliente = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCliente.sizePolicy().hasHeightForWidth())
        self.labelCliente.setSizePolicy(sizePolicy)
        self.labelCliente.setMinimumSize(QtCore.QSize(125, 0))
        self.labelCliente.setObjectName("labelCliente")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelCliente)
        self.inputCliente = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputCliente.sizePolicy().hasHeightForWidth())
        self.inputCliente.setSizePolicy(sizePolicy)
        self.inputCliente.setMinimumSize(QtCore.QSize(200, 0))
        self.inputCliente.setReadOnly(True)
        self.inputCliente.setObjectName("inputCliente")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inputCliente)
        self.labelContacto = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelContacto.sizePolicy().hasHeightForWidth())
        self.labelContacto.setSizePolicy(sizePolicy)
        self.labelContacto.setMinimumSize(QtCore.QSize(125, 0))
        self.labelContacto.setObjectName("labelContacto")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelContacto)
        self.inputContacto = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputContacto.sizePolicy().hasHeightForWidth())
        self.inputContacto.setSizePolicy(sizePolicy)
        self.inputContacto.setMinimumSize(QtCore.QSize(200, 0))
        self.inputContacto.setReadOnly(True)
        self.inputContacto.setObjectName("inputContacto")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.inputContacto)
        self.labelTelefono = QtWidgets.QLabel(Form)
        self.labelTelefono.setMinimumSize(QtCore.QSize(125, 0))
        self.labelTelefono.setObjectName("labelTelefono")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelTelefono)
        self.inputTelefono = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputTelefono.sizePolicy().hasHeightForWidth())
        self.inputTelefono.setSizePolicy(sizePolicy)
        self.inputTelefono.setMinimumSize(QtCore.QSize(200, 0))
        self.inputTelefono.setReadOnly(True)
        self.inputTelefono.setObjectName("inputTelefono")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.inputTelefono)
        self.labelEmail = QtWidgets.QLabel(Form)
        self.labelEmail.setMinimumSize(QtCore.QSize(125, 0))
        self.labelEmail.setObjectName("labelEmail")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelEmail)
        self.inputEmail = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputEmail.sizePolicy().hasHeightForWidth())
        self.inputEmail.setSizePolicy(sizePolicy)
        self.inputEmail.setMinimumSize(QtCore.QSize(200, 0))
        self.inputEmail.setReadOnly(True)
        self.inputEmail.setObjectName("inputEmail")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.inputEmail)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_3.setObjectName("formLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelRecinto = QtWidgets.QLabel(Form)
        self.labelRecinto.setMinimumSize(QtCore.QSize(110, 0))
        self.labelRecinto.setObjectName("labelRecinto")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelRecinto)
        self.inputRecinto = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputRecinto.sizePolicy().hasHeightForWidth())
        self.inputRecinto.setSizePolicy(sizePolicy)
        self.inputRecinto.setMinimumSize(QtCore.QSize(250, 0))
        self.inputRecinto.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.inputRecinto.setReadOnly(True)
        self.inputRecinto.setObjectName("inputRecinto")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inputRecinto)
        self.labelManager = QtWidgets.QLabel(Form)
        self.labelManager.setMinimumSize(QtCore.QSize(110, 0))
        self.labelManager.setObjectName("labelManager")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelManager)
        self.inputManager = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputManager.sizePolicy().hasHeightForWidth())
        self.inputManager.setSizePolicy(sizePolicy)
        self.inputManager.setMinimumSize(QtCore.QSize(250, 0))
        self.inputManager.setStyleSheet("")
        self.inputManager.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.inputManager.setReadOnly(True)
        self.inputManager.setObjectName("inputManager")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inputManager)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.formLayout_2)
        self.labelNotas = QtWidgets.QLabel(Form)
        self.labelNotas.setMinimumSize(QtCore.QSize(110, 0))
        self.labelNotas.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelNotas.setObjectName("labelNotas")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelNotas)
        self.inputNotas = QtWidgets.QPlainTextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNotas.sizePolicy().hasHeightForWidth())
        self.inputNotas.setSizePolicy(sizePolicy)
        self.inputNotas.setMinimumSize(QtCore.QSize(250, 0))
        self.inputNotas.setReadOnly(True)
        self.inputNotas.setObjectName("inputNotas")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inputNotas)
        self.horizontalLayout.addLayout(self.formLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.tableFechas = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableFechas.sizePolicy().hasHeightForWidth())
        self.tableFechas.setSizePolicy(sizePolicy)
        self.tableFechas.setStyleSheet("")
        self.tableFechas.setObjectName("tableFechas")
        self.tableFechas.setColumnCount(3)
        self.tableFechas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechas.setHorizontalHeaderItem(2, item)
        self.horizontalLayout.addWidget(self.tableFechas)
        spacerItem2 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.buttonEditar = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonEditar.sizePolicy().hasHeightForWidth())
        self.buttonEditar.setSizePolicy(sizePolicy)
        self.buttonEditar.setMinimumSize(QtCore.QSize(80, 40))
        self.buttonEditar.setObjectName("buttonEditar")
        self.horizontalLayout.addWidget(self.buttonEditar)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelSubtitle1 = QtWidgets.QLabel(Form)
        self.labelSubtitle1.setStyleSheet("")
        self.labelSubtitle1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelSubtitle1.setObjectName("labelSubtitle1")
        self.verticalLayout.addWidget(self.labelSubtitle1)
        self.tablePersonal = QtWidgets.QTableWidget(Form)
        self.tablePersonal.setStyleSheet("")
        self.tablePersonal.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tablePersonal.setObjectName("tablePersonal")
        self.tablePersonal.setColumnCount(6)
        self.tablePersonal.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablePersonal.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePersonal.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePersonal.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePersonal.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePersonal.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePersonal.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.tablePersonal)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelSubtitle2 = QtWidgets.QLabel(Form)
        self.labelSubtitle2.setStyleSheet("")
        self.labelSubtitle2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelSubtitle2.setObjectName("labelSubtitle2")
        self.verticalLayout_2.addWidget(self.labelSubtitle2)
        self.tableProveedores = QtWidgets.QTableWidget(Form)
        self.tableProveedores.setStyleSheet("")
        self.tableProveedores.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableProveedores.setObjectName("tableProveedores")
        self.tableProveedores.setColumnCount(4)
        self.tableProveedores.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableProveedores.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProveedores.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProveedores.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProveedores.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.tableProveedores)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelTitle.setText(_translate("Form", "Ficha de evento"))
        self.labelId.setText(_translate("Form", "ID_Evento"))
        self.labelNombre.setText(_translate("Form", "Nombre"))
        self.labelCliente.setText(_translate("Form", "Cliente"))
        self.labelContacto.setText(_translate("Form", "Contacto"))
        self.labelTelefono.setText(_translate("Form", "Teléfono onsite"))
        self.labelEmail.setText(_translate("Form", "Email onsite"))
        self.labelRecinto.setText(_translate("Form", "Recinto"))
        self.labelManager.setText(_translate("Form", "Manager"))
        self.labelNotas.setText(_translate("Form", "Notas"))
        item = self.tableFechas.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Fecha"))
        item = self.tableFechas.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Hora"))
        item = self.tableFechas.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Tarea"))
        self.buttonEditar.setText(_translate("Form", "Editar"))
        self.labelSubtitle1.setText(_translate("Form", "Personal"))
        item = self.tablePersonal.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Fecha"))
        item = self.tablePersonal.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Hora"))
        item = self.tablePersonal.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Cargo"))
        item = self.tablePersonal.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Nombre"))
        item = self.tablePersonal.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Apellidos"))
        item = self.tablePersonal.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Teléfono"))
        self.labelSubtitle2.setText(_translate("Form", "Proveedores"))
        item = self.tableProveedores.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Empresa"))
        item = self.tableProveedores.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Contacto"))
        item = self.tableProveedores.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Teléfono"))
        item = self.tableProveedores.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Notas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = FichaEvento_Ui()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

