# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fichapersonal_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class FichaPersonal_Ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1052, 833)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem, 4, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.foto = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foto.sizePolicy().hasHeightForWidth())
        self.foto.setSizePolicy(sizePolicy)
        self.foto.setMinimumSize(QtCore.QSize(189, 254))
        self.foto.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.foto.setAlignment(QtCore.Qt.AlignCenter)
        self.foto.setObjectName("foto")
        self.gridLayout.addWidget(self.foto, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 7, 1, 1)
        self.buttonDocumentos = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDocumentos.sizePolicy().hasHeightForWidth())
        self.buttonDocumentos.setSizePolicy(sizePolicy)
        self.buttonDocumentos.setMinimumSize(QtCore.QSize(150, 30))
        self.buttonDocumentos.setObjectName("buttonDocumentos")
        self.gridLayout.addWidget(self.buttonDocumentos, 6, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 55, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem3, 8, 5, 1, 1)
        self.buttonGuardar = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonGuardar.sizePolicy().hasHeightForWidth())
        self.buttonGuardar.setSizePolicy(sizePolicy)
        self.buttonGuardar.setMinimumSize(QtCore.QSize(150, 30))
        self.buttonGuardar.setObjectName("buttonGuardar")
        self.gridLayout.addWidget(self.buttonGuardar, 5, 5, 1, 1)
        self.buttonCerrar = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCerrar.sizePolicy().hasHeightForWidth())
        self.buttonCerrar.setSizePolicy(sizePolicy)
        self.buttonCerrar.setMinimumSize(QtCore.QSize(150, 30))
        self.buttonCerrar.setObjectName("buttonCerrar")
        self.gridLayout.addWidget(self.buttonCerrar, 7, 5, 1, 1)
        self.labelTitle = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle.sizePolicy().hasHeightForWidth())
        self.labelTitle.setSizePolicy(sizePolicy)
        self.labelTitle.setMinimumSize(QtCore.QSize(160, 30))
        self.labelTitle.setObjectName("labelTitle")
        self.gridLayout.addWidget(self.labelTitle, 0, 1, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelNotas = QtWidgets.QLabel(Form)
        self.labelNotas.setStyleSheet("")
        self.labelNotas.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelNotas.setObjectName("labelNotas")
        self.verticalLayout_2.addWidget(self.labelNotas)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        self.inputNotas = QtWidgets.QPlainTextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNotas.sizePolicy().hasHeightForWidth())
        self.inputNotas.setSizePolicy(sizePolicy)
        self.inputNotas.setMinimumSize(QtCore.QSize(320, 0))
        self.inputNotas.setObjectName("inputNotas")
        self.horizontalLayout_10.addWidget(self.inputNotas)
        self.gridLayout.addLayout(self.horizontalLayout_10, 2, 1, 1, 2)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(300, 0))
        self.widget.setStyleSheet("QWidget{\n"
"background-color: rgba(255, 255, 255, 0);}\n"
"QLineEdit {background-color:rgba(255,255,255,200);}")
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 4, 4, 3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelNombre = QtWidgets.QLabel(Form)
        self.labelNombre.setObjectName("labelNombre")
        self.horizontalLayout_4.addWidget(self.labelNombre)
        self.inputNombre = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNombre.sizePolicy().hasHeightForWidth())
        self.inputNombre.setSizePolicy(sizePolicy)
        self.inputNombre.setMinimumSize(QtCore.QSize(380, 0))
        self.inputNombre.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.inputNombre.setObjectName("inputNombre")
        self.horizontalLayout_4.addWidget(self.inputNombre)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelApellidos = QtWidgets.QLabel(Form)
        self.labelApellidos.setObjectName("labelApellidos")
        self.horizontalLayout_5.addWidget(self.labelApellidos)
        self.inputApellidos = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputApellidos.sizePolicy().hasHeightForWidth())
        self.inputApellidos.setSizePolicy(sizePolicy)
        self.inputApellidos.setMinimumSize(QtCore.QSize(380, 0))
        self.inputApellidos.setObjectName("inputApellidos")
        self.horizontalLayout_5.addWidget(self.inputApellidos)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.labelDni = QtWidgets.QLabel(Form)
        self.labelDni.setObjectName("labelDni")
        self.horizontalLayout_9.addWidget(self.labelDni)
        self.inputDni = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputDni.sizePolicy().hasHeightForWidth())
        self.inputDni.setSizePolicy(sizePolicy)
        self.inputDni.setMinimumSize(QtCore.QSize(380, 0))
        self.inputDni.setObjectName("inputDni")
        self.horizontalLayout_9.addWidget(self.inputDni)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelTelefono = QtWidgets.QLabel(Form)
        self.labelTelefono.setObjectName("labelTelefono")
        self.horizontalLayout_8.addWidget(self.labelTelefono)
        self.inputTelefono = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputTelefono.sizePolicy().hasHeightForWidth())
        self.inputTelefono.setSizePolicy(sizePolicy)
        self.inputTelefono.setMinimumSize(QtCore.QSize(380, 0))
        self.inputTelefono.setObjectName("inputTelefono")
        self.horizontalLayout_8.addWidget(self.inputTelefono)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelEmail = QtWidgets.QLabel(Form)
        self.labelEmail.setObjectName("labelEmail")
        self.horizontalLayout_7.addWidget(self.labelEmail)
        self.inputMail = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputMail.sizePolicy().hasHeightForWidth())
        self.inputMail.setSizePolicy(sizePolicy)
        self.inputMail.setMinimumSize(QtCore.QSize(380, 0))
        self.inputMail.setObjectName("inputMail")
        self.horizontalLayout_7.addWidget(self.inputMail)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.inputDireccion = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputDireccion.sizePolicy().hasHeightForWidth())
        self.inputDireccion.setSizePolicy(sizePolicy)
        self.inputDireccion.setMinimumSize(QtCore.QSize(380, 0))
        self.inputDireccion.setObjectName("inputDireccion")
        self.horizontalLayout_11.addWidget(self.inputDireccion)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.labelCp = QtWidgets.QLabel(Form)
        self.labelCp.setObjectName("labelCp")
        self.horizontalLayout_28.addWidget(self.labelCp)
        self.inputCp = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputCp.sizePolicy().hasHeightForWidth())
        self.inputCp.setSizePolicy(sizePolicy)
        self.inputCp.setMinimumSize(QtCore.QSize(380, 0))
        self.inputCp.setText("")
        self.inputCp.setObjectName("inputCp")
        self.horizontalLayout_28.addWidget(self.inputCp)
        self.verticalLayout_3.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.labelAutonomo_3 = QtWidgets.QLabel(Form)
        self.labelAutonomo_3.setObjectName("labelAutonomo_3")
        self.horizontalLayout_29.addWidget(self.labelAutonomo_3)
        self.inputCiudad = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputCiudad.sizePolicy().hasHeightForWidth())
        self.inputCiudad.setSizePolicy(sizePolicy)
        self.inputCiudad.setMinimumSize(QtCore.QSize(380, 0))
        self.inputCiudad.setText("")
        self.inputCiudad.setObjectName("inputCiudad")
        self.horizontalLayout_29.addWidget(self.inputCiudad)
        self.verticalLayout_3.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelAutonomo = QtWidgets.QLabel(Form)
        self.labelAutonomo.setObjectName("labelAutonomo")
        self.horizontalLayout_6.addWidget(self.labelAutonomo)
        self.inputAutonomo = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputAutonomo.sizePolicy().hasHeightForWidth())
        self.inputAutonomo.setSizePolicy(sizePolicy)
        self.inputAutonomo.setMinimumSize(QtCore.QSize(380, 0))
        self.inputAutonomo.setObjectName("inputAutonomo")
        self.horizontalLayout_6.addWidget(self.inputAutonomo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.labelIban = QtWidgets.QLabel(Form)
        self.labelIban.setObjectName("labelIban")
        self.horizontalLayout_12.addWidget(self.labelIban)
        self.inputIban = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputIban.sizePolicy().hasHeightForWidth())
        self.inputIban.setSizePolicy(sizePolicy)
        self.inputIban.setMinimumSize(QtCore.QSize(380, 0))
        self.inputIban.setObjectName("inputIban")
        self.horizontalLayout_12.addWidget(self.inputIban)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 2, 2, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.buttonPre = QtWidgets.QToolButton(Form)
        self.buttonPre.setObjectName("buttonPre")
        self.horizontalLayout.addWidget(self.buttonPre)
        self.labelMes = QtWidgets.QLabel(Form)
        self.labelMes.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.labelMes.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMes.setObjectName("labelMes")
        self.horizontalLayout.addWidget(self.labelMes)
        self.labelMes_2 = QtWidgets.QLabel(Form)
        self.labelMes_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.labelMes_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMes_2.setObjectName("labelMes_2")
        self.horizontalLayout.addWidget(self.labelMes_2)
        self.buttonNext = QtWidgets.QToolButton(Form)
        self.buttonNext.setObjectName("buttonNext")
        self.horizontalLayout.addWidget(self.buttonNext)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 6, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(99)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(26)
        self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonOcupar = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOcupar.sizePolicy().hasHeightForWidth())
        self.buttonOcupar.setSizePolicy(sizePolicy)
        self.buttonOcupar.setMinimumSize(QtCore.QSize(60, 30))
        self.buttonOcupar.setStyleSheet("background-color: rgba(255, 21, 0, 180);\n"
"")
        self.buttonOcupar.setObjectName("buttonOcupar")
        self.horizontalLayout_2.addWidget(self.buttonOcupar)
        self.buttonLiberar = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonLiberar.sizePolicy().hasHeightForWidth())
        self.buttonLiberar.setSizePolicy(sizePolicy)
        self.buttonLiberar.setMinimumSize(QtCore.QSize(60, 30))
        self.buttonLiberar.setStyleSheet("background-color: rgb(65, 255, 44);")
        self.buttonLiberar.setObjectName("buttonLiberar")
        self.horizontalLayout_2.addWidget(self.buttonLiberar)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_6, 3, 1, 6, 2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 5, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 5, 7, 1, 1)
        self.labelNotas.setBuddy(self.inputNotas)
        self.labelNombre.setBuddy(self.inputNombre)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.foto.setText(_translate("Form", "Foto"))
        self.buttonDocumentos.setText(_translate("Form", "Documentos"))
        self.buttonGuardar.setText(_translate("Form", "Guardar Cambios"))
        self.buttonCerrar.setText(_translate("Form", "Cerrar"))
        self.labelTitle.setText(_translate("Form", "Ficha Personal"))
        self.labelNotas.setText(_translate("Form", "Notas"))
        self.inputNotas.setPlainText(_translate("Form", "Inglés, catalán\n"
"MA, Avolites, ONYX\n"
"Luminex"))
        self.labelNombre.setText(_translate("Form", "Nombre"))
        self.inputNombre.setText(_translate("Form", "Alejandro"))
        self.labelApellidos.setText(_translate("Form", "Apellidos"))
        self.inputApellidos.setText(_translate("Form", "Pérez Pérez"))
        self.labelDni.setText(_translate("Form", "DNI"))
        self.inputDni.setText(_translate("Form", "67458932M"))
        self.labelTelefono.setText(_translate("Form", "Teléfono"))
        self.inputTelefono.setText(_translate("Form", "654321987"))
        self.labelEmail.setText(_translate("Form", "Email"))
        self.inputMail.setText(_translate("Form", "alejandro@example.es"))
        self.label_14.setText(_translate("Form", "Dirección"))
        self.inputDireccion.setText(_translate("Form", "carrer example nº3 08012 Barcelona"))
        self.labelCp.setText(_translate("Form", "C.P."))
        self.labelAutonomo_3.setText(_translate("Form", "Ciudad"))
        self.labelAutonomo.setText(_translate("Form", "Autónomo"))
        self.inputAutonomo.setText(_translate("Form", "Sí"))
        self.labelIban.setText(_translate("Form", "IBAN"))
        self.inputIban.setText(_translate("Form", "ES12 2345 2345 2345 2345"))
        self.buttonPre.setText(_translate("Form", "<"))
        self.labelMes.setText(_translate("Form", "Enero"))
        self.labelMes_2.setText(_translate("Form", "2021"))
        self.buttonNext.setText(_translate("Form", ">"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Lunes"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Martes"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Miércoles"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Jueves"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Viernes"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Sábado"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Domingo"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.buttonOcupar.setText(_translate("Form", "Ocupar"))
        self.buttonLiberar.setText(_translate("Form", "Liberar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = FichaPersonal_Ui()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

