# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fichaevento.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class FichaEvento_Ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1319, 845)
        self.tableFechas = QtWidgets.QTableWidget(Dialog)
        self.tableFechas.setGeometry(QtCore.QRect(730, 100, 381, 181))
        self.tableFechas.setObjectName("tableFechas")
        self.tableFechas.setColumnCount(3)
        self.tableFechas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFechas.setHorizontalHeaderItem(2, item)
        self.tablePersonal = QtWidgets.QTableWidget(Dialog)
        self.tablePersonal.setGeometry(QtCore.QRect(60, 320, 1221, 271))
        self.tablePersonal.setObjectName("tablePersonal")
        self.tablePersonal.setColumnCount(6)
        self.tablePersonal.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablePersonal.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePersonal.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePersonal.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePersonal.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePersonal.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePersonal.setHorizontalHeaderItem(5, item)
        self.tableProveedores = QtWidgets.QTableWidget(Dialog)
        self.tableProveedores.setGeometry(QtCore.QRect(60, 620, 1221, 181))
        self.tableProveedores.setObjectName("tableProveedores")
        self.tableProveedores.setColumnCount(4)
        self.tableProveedores.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableProveedores.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProveedores.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProveedores.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProveedores.setHorizontalHeaderItem(3, item)
        self.inputNombre = QtWidgets.QLineEdit(Dialog)
        self.inputNombre.setGeometry(QtCore.QRect(158, 130, 200, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNombre.sizePolicy().hasHeightForWidth())
        self.inputNombre.setSizePolicy(sizePolicy)
        self.inputNombre.setReadOnly(True)
        self.inputNombre.setObjectName("inputNombre")
        self.labelNombre = QtWidgets.QLabel(Dialog)
        self.labelNombre.setGeometry(QtCore.QRect(60, 130, 100, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelNombre.sizePolicy().hasHeightForWidth())
        self.labelNombre.setSizePolicy(sizePolicy)
        self.labelNombre.setObjectName("labelNombre")
        self.lablabelFicha = QtWidgets.QLabel(Dialog)
        self.lablabelFicha.setGeometry(QtCore.QRect(60, 30, 211, 41))
        self.lablabelFicha.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.lablabelFicha.setObjectName("lablabelFicha")
        self.labelPersonal = QtWidgets.QLabel(Dialog)
        self.labelPersonal.setGeometry(QtCore.QRect(40, 300, 100, 16))
        self.labelPersonal.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.labelPersonal.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPersonal.setObjectName("labelPersonal")
        self.labelProveedores = QtWidgets.QLabel(Dialog)
        self.labelProveedores.setGeometry(QtCore.QRect(60, 600, 100, 16))
        self.labelProveedores.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelProveedores.setAlignment(QtCore.Qt.AlignCenter)
        self.labelProveedores.setObjectName("labelProveedores")
        self.labelCliente = QtWidgets.QLabel(Dialog)
        self.labelCliente.setGeometry(QtCore.QRect(60, 159, 100, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCliente.sizePolicy().hasHeightForWidth())
        self.labelCliente.setSizePolicy(sizePolicy)
        self.labelCliente.setObjectName("labelCliente")
        self.labelContacto = QtWidgets.QLabel(Dialog)
        self.labelContacto.setGeometry(QtCore.QRect(60, 188, 100, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelContacto.sizePolicy().hasHeightForWidth())
        self.labelContacto.setSizePolicy(sizePolicy)
        self.labelContacto.setObjectName("labelContacto")
        self.labelTelefono = QtWidgets.QLabel(Dialog)
        self.labelTelefono.setGeometry(QtCore.QRect(60, 220, 100, 16))
        self.labelTelefono.setObjectName("labelTelefono")
        self.labelEmail = QtWidgets.QLabel(Dialog)
        self.labelEmail.setGeometry(QtCore.QRect(60, 250, 100, 16))
        self.labelEmail.setObjectName("labelEmail")
        self.labelRecinto = QtWidgets.QLabel(Dialog)
        self.labelRecinto.setGeometry(QtCore.QRect(390, 100, 100, 16))
        self.labelRecinto.setObjectName("labelRecinto")
        self.labelManager = QtWidgets.QLabel(Dialog)
        self.labelManager.setGeometry(QtCore.QRect(390, 130, 100, 16))
        self.labelManager.setObjectName("labelManager")
        self.labelNotas = QtWidgets.QLabel(Dialog)
        self.labelNotas.setGeometry(QtCore.QRect(390, 160, 100, 16))
        self.labelNotas.setObjectName("labelNotas")
        self.inputCliente = QtWidgets.QLineEdit(Dialog)
        self.inputCliente.setGeometry(QtCore.QRect(158, 159, 200, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputCliente.sizePolicy().hasHeightForWidth())
        self.inputCliente.setSizePolicy(sizePolicy)
        self.inputCliente.setReadOnly(True)
        self.inputCliente.setObjectName("inputCliente")
        self.inputContacto = QtWidgets.QLineEdit(Dialog)
        self.inputContacto.setGeometry(QtCore.QRect(158, 188, 200, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputContacto.sizePolicy().hasHeightForWidth())
        self.inputContacto.setSizePolicy(sizePolicy)
        self.inputContacto.setReadOnly(True)
        self.inputContacto.setObjectName("inputContacto")
        self.inputEmail = QtWidgets.QLineEdit(Dialog)
        self.inputEmail.setGeometry(QtCore.QRect(160, 250, 200, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputEmail.sizePolicy().hasHeightForWidth())
        self.inputEmail.setSizePolicy(sizePolicy)
        self.inputEmail.setReadOnly(True)
        self.inputEmail.setObjectName("inputEmail")
        self.inputRecinto = QtWidgets.QLineEdit(Dialog)
        self.inputRecinto.setGeometry(QtCore.QRect(490, 100, 200, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputRecinto.sizePolicy().hasHeightForWidth())
        self.inputRecinto.setSizePolicy(sizePolicy)
        self.inputRecinto.setReadOnly(True)
        self.inputRecinto.setObjectName("inputRecinto")
        self.inputTelefono = QtWidgets.QLineEdit(Dialog)
        self.inputTelefono.setGeometry(QtCore.QRect(160, 220, 200, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputTelefono.sizePolicy().hasHeightForWidth())
        self.inputTelefono.setSizePolicy(sizePolicy)
        self.inputTelefono.setReadOnly(True)
        self.inputTelefono.setObjectName("inputTelefono")
        self.inputManager = QtWidgets.QLineEdit(Dialog)
        self.inputManager.setGeometry(QtCore.QRect(490, 130, 200, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputManager.sizePolicy().hasHeightForWidth())
        self.inputManager.setSizePolicy(sizePolicy)
        self.inputManager.setReadOnly(True)
        self.inputManager.setObjectName("inputManager")
        self.inputNotas = QtWidgets.QPlainTextEdit(Dialog)
        self.inputNotas.setGeometry(QtCore.QRect(490, 160, 200, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNotas.sizePolicy().hasHeightForWidth())
        self.inputNotas.setSizePolicy(sizePolicy)
        self.inputNotas.setReadOnly(True)
        self.inputNotas.setObjectName("inputNotas")
        self.buttonEditar = QtWidgets.QPushButton(Dialog)
        self.buttonEditar.setGeometry(QtCore.QRect(1150, 230, 131, 51))
        self.buttonEditar.setObjectName("buttonEditar")
        self.inputId = QtWidgets.QLineEdit(Dialog)
        self.inputId.setGeometry(QtCore.QRect(158, 100, 200, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputId.sizePolicy().hasHeightForWidth())
        self.inputId.setSizePolicy(sizePolicy)
        self.inputId.setReadOnly(True)
        self.inputId.setObjectName("inputId")
        self.labelId = QtWidgets.QLabel(Dialog)
        self.labelId.setGeometry(QtCore.QRect(60, 100, 100, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelId.sizePolicy().hasHeightForWidth())
        self.labelId.setSizePolicy(sizePolicy)
        self.labelId.setObjectName("labelId")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.inputId, self.inputNombre)
        Dialog.setTabOrder(self.inputNombre, self.inputCliente)
        Dialog.setTabOrder(self.inputCliente, self.inputContacto)
        Dialog.setTabOrder(self.inputContacto, self.inputTelefono)
        Dialog.setTabOrder(self.inputTelefono, self.inputEmail)
        Dialog.setTabOrder(self.inputEmail, self.inputRecinto)
        Dialog.setTabOrder(self.inputRecinto, self.inputManager)
        Dialog.setTabOrder(self.inputManager, self.inputNotas)
        Dialog.setTabOrder(self.inputNotas, self.tableFechas)
        Dialog.setTabOrder(self.tableFechas, self.tablePersonal)
        Dialog.setTabOrder(self.tablePersonal, self.tableProveedores)
        Dialog.setTabOrder(self.tableProveedores, self.buttonEditar)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableFechas.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Fecha"))
        item = self.tableFechas.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Hora"))
        item = self.tableFechas.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Tarea"))
        item = self.tablePersonal.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Fecha"))
        item = self.tablePersonal.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Hora"))
        item = self.tablePersonal.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Cargo"))
        item = self.tablePersonal.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Nombre"))
        item = self.tablePersonal.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Apellidos"))
        item = self.tablePersonal.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Teléfono"))
        item = self.tableProveedores.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Empresa"))
        item = self.tableProveedores.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Contacto"))
        item = self.tableProveedores.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Teléfono"))
        item = self.tableProveedores.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Notas"))
        self.labelNombre.setText(_translate("Dialog", "Nombre"))
        self.lablabelFicha.setText(_translate("Dialog", "Ficha de evento"))
        self.labelPersonal.setText(_translate("Dialog", "Personal"))
        self.labelProveedores.setText(_translate("Dialog", "Proveedores"))
        self.labelCliente.setText(_translate("Dialog", "Cliente"))
        self.labelContacto.setText(_translate("Dialog", "Contacto"))
        self.labelTelefono.setText(_translate("Dialog", "Teléfono onsite"))
        self.labelEmail.setText(_translate("Dialog", "Email onsite"))
        self.labelRecinto.setText(_translate("Dialog", "Recinto"))
        self.labelManager.setText(_translate("Dialog", "Manager"))
        self.labelNotas.setText(_translate("Dialog", "Notas"))
        self.buttonEditar.setText(_translate("Dialog", "Editar"))
        self.labelId.setText(_translate("Dialog", "ID_Evento"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = FichaEvento_Ui()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

