# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fichapersonal.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class FichaPersonal_Ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1112, 865)
        Dialog.setStyleSheet("")
        self.foto = QtWidgets.QLabel(Dialog)
        self.foto.setGeometry(QtCore.QRect(30, 100, 191, 261))
        self.foto.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.foto.setAlignment(QtCore.Qt.AlignCenter)
        self.foto.setObjectName("foto")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 380, 701, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelNotas = QtWidgets.QLabel(self.layoutWidget)
        self.labelNotas.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelNotas.setObjectName("labelNotas")
        self.verticalLayout_2.addWidget(self.labelNotas)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        self.inputNotas = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.inputNotas.setMinimumSize(QtCore.QSize(320, 0))
        self.inputNotas.setObjectName("inputNotas")
        self.horizontalLayout_10.addWidget(self.inputNotas)
        self.labelFichapersonal = QtWidgets.QLabel(Dialog)
        self.labelFichapersonal.setGeometry(QtCore.QRect(40, 50, 171, 31))
        self.labelFichapersonal.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.labelFichapersonal.setObjectName("labelFichapersonal")
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 550, 701, 281))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonPre = QtWidgets.QToolButton(self.layoutWidget1)
        self.buttonPre.setObjectName("buttonPre")
        self.horizontalLayout.addWidget(self.buttonPre)
        self.labelMes = QtWidgets.QLabel(self.layoutWidget1)
        self.labelMes.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.labelMes.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMes.setObjectName("labelMes")
        self.horizontalLayout.addWidget(self.labelMes)
        self.labelMes_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.labelMes_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.labelMes_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMes_2.setObjectName("labelMes_2")
        self.horizontalLayout.addWidget(self.labelMes_2)
        self.buttonNext = QtWidgets.QToolButton(self.layoutWidget1)
        self.buttonNext.setObjectName("buttonNext")
        self.horizontalLayout.addWidget(self.buttonNext)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 6, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(99)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(26)
        self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonOcupar = QtWidgets.QToolButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOcupar.sizePolicy().hasHeightForWidth())
        self.buttonOcupar.setSizePolicy(sizePolicy)
        self.buttonOcupar.setStyleSheet("background-color: rgba(255, 21, 0, 180);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.buttonOcupar.setObjectName("buttonOcupar")
        self.horizontalLayout_2.addWidget(self.buttonOcupar)
        self.buttonLiberar = QtWidgets.QToolButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonLiberar.sizePolicy().hasHeightForWidth())
        self.buttonLiberar.setSizePolicy(sizePolicy)
        self.buttonLiberar.setStyleSheet("background-color: rgb(65, 255, 44);")
        self.buttonLiberar.setObjectName("buttonLiberar")
        self.horizontalLayout_2.addWidget(self.buttonLiberar)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(840, 630, 129, 141))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.buttonGuardar = QtWidgets.QPushButton(self.layoutWidget2)
        self.buttonGuardar.setObjectName("buttonGuardar")
        self.verticalLayout_4.addWidget(self.buttonGuardar)
        self.buttonDocumentos = QtWidgets.QPushButton(self.layoutWidget2)
        self.buttonDocumentos.setObjectName("buttonDocumentos")
        self.verticalLayout_4.addWidget(self.buttonDocumentos)
        self.buttonCerrar = QtWidgets.QPushButton(self.layoutWidget2)
        self.buttonCerrar.setObjectName("buttonCerrar")
        self.verticalLayout_4.addWidget(self.buttonCerrar)
        self.layoutWidget3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(230, 60, 507, 305))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelNombre = QtWidgets.QLabel(self.layoutWidget3)
        self.labelNombre.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelNombre.setObjectName("labelNombre")
        self.horizontalLayout_4.addWidget(self.labelNombre)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.inputNombre = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNombre.sizePolicy().hasHeightForWidth())
        self.inputNombre.setSizePolicy(sizePolicy)
        self.inputNombre.setMinimumSize(QtCore.QSize(380, 0))
        self.inputNombre.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.inputNombre.setObjectName("inputNombre")
        self.horizontalLayout_4.addWidget(self.inputNombre)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelApellidos = QtWidgets.QLabel(self.layoutWidget3)
        self.labelApellidos.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelApellidos.setObjectName("labelApellidos")
        self.horizontalLayout_5.addWidget(self.labelApellidos)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.inputApellidos = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputApellidos.sizePolicy().hasHeightForWidth())
        self.inputApellidos.setSizePolicy(sizePolicy)
        self.inputApellidos.setMinimumSize(QtCore.QSize(380, 0))
        self.inputApellidos.setObjectName("inputApellidos")
        self.horizontalLayout_5.addWidget(self.inputApellidos)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.labelDni = QtWidgets.QLabel(self.layoutWidget3)
        self.labelDni.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelDni.setObjectName("labelDni")
        self.horizontalLayout_9.addWidget(self.labelDni)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.inputDni = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputDni.sizePolicy().hasHeightForWidth())
        self.inputDni.setSizePolicy(sizePolicy)
        self.inputDni.setMinimumSize(QtCore.QSize(380, 0))
        self.inputDni.setObjectName("inputDni")
        self.horizontalLayout_9.addWidget(self.inputDni)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelTelefono = QtWidgets.QLabel(self.layoutWidget3)
        self.labelTelefono.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelTelefono.setObjectName("labelTelefono")
        self.horizontalLayout_8.addWidget(self.labelTelefono)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.inputTelefono = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputTelefono.sizePolicy().hasHeightForWidth())
        self.inputTelefono.setSizePolicy(sizePolicy)
        self.inputTelefono.setMinimumSize(QtCore.QSize(380, 0))
        self.inputTelefono.setObjectName("inputTelefono")
        self.horizontalLayout_8.addWidget(self.inputTelefono)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelEmail = QtWidgets.QLabel(self.layoutWidget3)
        self.labelEmail.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelEmail.setObjectName("labelEmail")
        self.horizontalLayout_7.addWidget(self.labelEmail)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.inputMail = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputMail.sizePolicy().hasHeightForWidth())
        self.inputMail.setSizePolicy(sizePolicy)
        self.inputMail.setMinimumSize(QtCore.QSize(380, 0))
        self.inputMail.setObjectName("inputMail")
        self.horizontalLayout_7.addWidget(self.inputMail)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_14.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.inputDireccion = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputDireccion.sizePolicy().hasHeightForWidth())
        self.inputDireccion.setSizePolicy(sizePolicy)
        self.inputDireccion.setMinimumSize(QtCore.QSize(380, 0))
        self.inputDireccion.setObjectName("inputDireccion")
        self.horizontalLayout_11.addWidget(self.inputDireccion)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.labelCp = QtWidgets.QLabel(self.layoutWidget3)
        self.labelCp.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelCp.setObjectName("labelCp")
        self.horizontalLayout_28.addWidget(self.labelCp)
        spacerItem10 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem10)
        self.inputCp = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputCp.sizePolicy().hasHeightForWidth())
        self.inputCp.setSizePolicy(sizePolicy)
        self.inputCp.setMinimumSize(QtCore.QSize(380, 0))
        self.inputCp.setText("")
        self.inputCp.setObjectName("inputCp")
        self.horizontalLayout_28.addWidget(self.inputCp)
        self.verticalLayout_3.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.labelAutonomo_3 = QtWidgets.QLabel(self.layoutWidget3)
        self.labelAutonomo_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelAutonomo_3.setObjectName("labelAutonomo_3")
        self.horizontalLayout_29.addWidget(self.labelAutonomo_3)
        spacerItem11 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem11)
        self.inputCiudad = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputCiudad.sizePolicy().hasHeightForWidth())
        self.inputCiudad.setSizePolicy(sizePolicy)
        self.inputCiudad.setMinimumSize(QtCore.QSize(380, 0))
        self.inputCiudad.setText("")
        self.inputCiudad.setObjectName("inputCiudad")
        self.horizontalLayout_29.addWidget(self.inputCiudad)
        self.verticalLayout_3.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelAutonomo = QtWidgets.QLabel(self.layoutWidget3)
        self.labelAutonomo.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelAutonomo.setObjectName("labelAutonomo")
        self.horizontalLayout_6.addWidget(self.labelAutonomo)
        spacerItem12 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.inputAutonomo = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputAutonomo.sizePolicy().hasHeightForWidth())
        self.inputAutonomo.setSizePolicy(sizePolicy)
        self.inputAutonomo.setMinimumSize(QtCore.QSize(380, 0))
        self.inputAutonomo.setObjectName("inputAutonomo")
        self.horizontalLayout_6.addWidget(self.inputAutonomo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.labelIban = QtWidgets.QLabel(self.layoutWidget3)
        self.labelIban.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelIban.setObjectName("labelIban")
        self.horizontalLayout_12.addWidget(self.labelIban)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem13)
        self.inputIban = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputIban.sizePolicy().hasHeightForWidth())
        self.inputIban.setSizePolicy(sizePolicy)
        self.inputIban.setMinimumSize(QtCore.QSize(380, 0))
        self.inputIban.setObjectName("inputIban")
        self.horizontalLayout_12.addWidget(self.inputIban)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(789, 59, 271, 531))
        self.widget.setObjectName("widget")
        self.labelNotas.setBuddy(self.inputNotas)
        self.labelNombre.setBuddy(self.inputNombre)

        self.retranslateUi(Dialog)
        self.buttonOcupar.clicked.connect(self.tableWidget.update)
        self.buttonLiberar.clicked.connect(self.tableWidget.update)
        self.buttonCerrar.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.foto.setText(_translate("Dialog", "Foto"))
        self.labelNotas.setText(_translate("Dialog", "Notas"))
        self.inputNotas.setPlainText(_translate("Dialog", "Inglés, catalán\n"
"MA, Avolites, ONYX\n"
"Luminex"))
        self.labelFichapersonal.setText(_translate("Dialog", "Ficha Personal"))
        self.buttonPre.setText(_translate("Dialog", "<"))
        self.labelMes.setText(_translate("Dialog", "Enero"))
        self.labelMes_2.setText(_translate("Dialog", "2021"))
        self.buttonNext.setText(_translate("Dialog", ">"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Lunes"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Martes"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Miércoles"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Jueves"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Viernes"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Sábado"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Domingo"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.buttonOcupar.setText(_translate("Dialog", "Ocupar"))
        self.buttonLiberar.setText(_translate("Dialog", "Liberar"))
        self.buttonGuardar.setText(_translate("Dialog", "Guardar Cambios"))
        self.buttonDocumentos.setText(_translate("Dialog", "Documentos"))
        self.buttonCerrar.setText(_translate("Dialog", "Cerrar"))
        self.labelNombre.setText(_translate("Dialog", "Nombre"))
        self.inputNombre.setText(_translate("Dialog", "Alejandro"))
        self.labelApellidos.setText(_translate("Dialog", "Apellidos"))
        self.inputApellidos.setText(_translate("Dialog", "Pérez Pérez"))
        self.labelDni.setText(_translate("Dialog", "DNI"))
        self.inputDni.setText(_translate("Dialog", "67458932M"))
        self.labelTelefono.setText(_translate("Dialog", "Teléfono"))
        self.inputTelefono.setText(_translate("Dialog", "654321987"))
        self.labelEmail.setText(_translate("Dialog", "Email"))
        self.inputMail.setText(_translate("Dialog", "alejandro@example.es"))
        self.label_14.setText(_translate("Dialog", "Dirección"))
        self.inputDireccion.setText(_translate("Dialog", "carrer example nº3 08012 Barcelona"))
        self.labelCp.setText(_translate("Dialog", "C.P."))
        self.labelAutonomo_3.setText(_translate("Dialog", "Ciudad"))
        self.labelAutonomo.setText(_translate("Dialog", "Autónomo"))
        self.inputAutonomo.setText(_translate("Dialog", "Sí"))
        self.labelIban.setText(_translate("Dialog", "IBAN"))
        self.inputIban.setText(_translate("Dialog", "ES12 2345 2345 2345 2345"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = FichaPersonal_Ui()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

