# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hojadebolos_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class HojaBolos_Ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(713, 528)
        self.comboAnyo = QtWidgets.QComboBox(Dialog)
        self.comboAnyo.setGeometry(QtCore.QRect(30, 100, 91, 22))
        self.comboAnyo.setObjectName("comboAnyo")
        self.labelAnyo = QtWidgets.QLabel(Dialog)
        self.labelAnyo.setGeometry(QtCore.QRect(30, 70, 180, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAnyo.sizePolicy().hasHeightForWidth())
        self.labelAnyo.setSizePolicy(sizePolicy)
        self.labelAnyo.setMinimumSize(QtCore.QSize(180, 30))
        self.labelAnyo.setObjectName("labelAnyo")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(30, 180, 141, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.labelMes = QtWidgets.QLabel(Dialog)
        self.labelMes.setGeometry(QtCore.QRect(30, 150, 180, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMes.sizePolicy().hasHeightForWidth())
        self.labelMes.setSizePolicy(sizePolicy)
        self.labelMes.setMinimumSize(QtCore.QSize(180, 30))
        self.labelMes.setObjectName("labelMes")
        self.tablePersonal = QtWidgets.QTableWidget(Dialog)
        self.tablePersonal.setGeometry(QtCore.QRect(250, 100, 440, 380))
        self.tablePersonal.setObjectName("tablePersonal")
        self.tablePersonal.setColumnCount(0)
        self.tablePersonal.setRowCount(0)
        self.labelPersonal = QtWidgets.QLabel(Dialog)
        self.labelPersonal.setGeometry(QtCore.QRect(250, 70, 180, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPersonal.sizePolicy().hasHeightForWidth())
        self.labelPersonal.setSizePolicy(sizePolicy)
        self.labelPersonal.setMinimumSize(QtCore.QSize(180, 30))
        self.labelPersonal.setObjectName("labelPersonal")
        self.buttoCrearIndi = QtWidgets.QPushButton(Dialog)
        self.buttoCrearIndi.setGeometry(QtCore.QRect(30, 350, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttoCrearIndi.sizePolicy().hasHeightForWidth())
        self.buttoCrearIndi.setSizePolicy(sizePolicy)
        self.buttoCrearIndi.setObjectName("buttoCrearIndi")
        self.labelTitle = QtWidgets.QLabel(Dialog)
        self.labelTitle.setGeometry(QtCore.QRect(30, 20, 180, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle.sizePolicy().hasHeightForWidth())
        self.labelTitle.setSizePolicy(sizePolicy)
        self.labelTitle.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.labelTitle.setObjectName("labelTitle")
        self.buttoCrearMulti = QtWidgets.QPushButton(Dialog)
        self.buttoCrearMulti.setGeometry(QtCore.QRect(30, 440, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttoCrearMulti.sizePolicy().hasHeightForWidth())
        self.buttoCrearMulti.setSizePolicy(sizePolicy)
        self.buttoCrearMulti.setObjectName("buttoCrearMulti")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 320, 180, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(180, 30))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 410, 180, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(180, 30))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelAnyo.setText(_translate("Dialog", "Año"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Enero"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Febrero"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Marzo"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "Abril"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "Mayo"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "Junio"))
        self.comboBox_2.setItemText(6, _translate("Dialog", "Julio"))
        self.comboBox_2.setItemText(7, _translate("Dialog", "Agosto"))
        self.comboBox_2.setItemText(8, _translate("Dialog", "Septiembre"))
        self.comboBox_2.setItemText(9, _translate("Dialog", "Octubre"))
        self.comboBox_2.setItemText(10, _translate("Dialog", "Noviembre"))
        self.comboBox_2.setItemText(11, _translate("Dialog", "Diciembre"))
        self.labelMes.setText(_translate("Dialog", "Mes"))
        self.tablePersonal.setSortingEnabled(True)
        self.labelPersonal.setText(_translate("Dialog", "Personal"))
        self.buttoCrearIndi.setText(_translate("Dialog", "Crear hoja"))
        self.labelTitle.setText(_translate("Dialog", "Hoja de bolos"))
        self.buttoCrearMulti.setText(_translate("Dialog", "Crear hojas"))
        self.label.setText(_translate("Dialog", "Crear hoja individual"))
        self.label_2.setText(_translate("Dialog", "Crear todas las hojas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = HojaBolos_Ui()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

