# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menuprincipal_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class MenuPrincipal_Ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1302, 666)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonPrev30 = QtWidgets.QToolButton(self.centralwidget)
        self.buttonPrev30.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 255, 255);")
        self.buttonPrev30.setObjectName("buttonPrev30")
        self.horizontalLayout.addWidget(self.buttonPrev30)
        self.buttonPrev7 = QtWidgets.QToolButton(self.centralwidget)
        self.buttonPrev7.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 255, 255);")
        self.buttonPrev7.setObjectName("buttonPrev7")
        self.horizontalLayout.addWidget(self.buttonPrev7)
        self.buttonPrev1 = QtWidgets.QToolButton(self.centralwidget)
        self.buttonPrev1.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 255, 255);")
        self.buttonPrev1.setObjectName("buttonPrev1")
        self.horizontalLayout.addWidget(self.buttonPrev1)
        self.labelVista = QtWidgets.QLabel(self.centralwidget)
        self.labelVista.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelVista.setObjectName("labelVista")
        self.horizontalLayout.addWidget(self.labelVista)
        self.buttonNext1 = QtWidgets.QToolButton(self.centralwidget)
        self.buttonNext1.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 255, 255);")
        self.buttonNext1.setObjectName("buttonNext1")
        self.horizontalLayout.addWidget(self.buttonNext1)
        self.buttonNext7 = QtWidgets.QToolButton(self.centralwidget)
        self.buttonNext7.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 255, 255);")
        self.buttonNext7.setObjectName("buttonNext7")
        self.horizontalLayout.addWidget(self.buttonNext7)
        self.buttonNext30 = QtWidgets.QToolButton(self.centralwidget)
        self.buttonNext30.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 255, 255);")
        self.buttonNext30.setObjectName("buttonNext30")
        self.horizontalLayout.addWidget(self.buttonNext30)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 0, 0))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 0, 0))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 0, 0))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.buttonSinConf = QtWidgets.QToolButton(self.centralwidget)
        self.buttonSinConf.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.buttonSinConf.setText("")
        self.buttonSinConf.setObjectName("buttonSinConf")
        self.horizontalLayout_2.addWidget(self.buttonSinConf)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.buttonPersonal = QtWidgets.QToolButton(self.centralwidget)
        self.buttonPersonal.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.buttonPersonal.setText("")
        self.buttonPersonal.setObjectName("buttonPersonal")
        self.horizontalLayout_2.addWidget(self.buttonPersonal)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.buttonProveedor = QtWidgets.QToolButton(self.centralwidget)
        self.buttonProveedor.setStyleSheet("background-color: rgb(0, 75, 255);")
        self.buttonProveedor.setText("")
        self.buttonProveedor.setObjectName("buttonProveedor")
        self.horizontalLayout_2.addWidget(self.buttonProveedor)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.buttonCerrado = QtWidgets.QToolButton(self.centralwidget)
        self.buttonCerrado.setStyleSheet("background-color: rgb(74, 222, 0);")
        self.buttonCerrado.setText("")
        self.buttonCerrado.setObjectName("buttonCerrado")
        self.horizontalLayout_2.addWidget(self.buttonCerrado)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1302, 26))
        self.menubar.setStyleSheet("selection-background-color: rgba(225, 225, 225, 150);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0149254 rgba(0, 170, 255, 178), stop:0.179104 rgba(0, 170, 255, 55), stop:0.343284 rgba(0, 170, 255, 156), stop:0.701493 rgba(0, 170, 255, 63), stop:0.840796 rgba(0, 170, 255, 179));")
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setStyleSheet("selection-background-color: rgba(225, 225, 225, 150);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0149254 rgba(0, 170, 255, 178), stop:0.179104 rgba(0, 170, 255, 55), stop:0.343284 rgba(0, 170, 255, 156), stop:0.701493 rgba(0, 170, 255, 63), stop:0.840796 rgba(0, 170, 255, 179));")
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuPersonal = QtWidgets.QMenu(self.menubar)
        self.menuPersonal.setStyleSheet("selection-background-color: rgba(225, 225, 225, 150);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0149254 rgba(0, 170, 255, 178), stop:0.179104 rgba(0, 170, 255, 55), stop:0.343284 rgba(0, 170, 255, 156), stop:0.701493 rgba(0, 170, 255, 63), stop:0.840796 rgba(0, 170, 255, 179));")
        self.menuPersonal.setObjectName("menuPersonal")
        self.menuEventos = QtWidgets.QMenu(self.menubar)
        self.menuEventos.setStyleSheet("selection-background-color: rgba(225, 225, 225, 150);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0149254 rgba(0, 170, 255, 178), stop:0.179104 rgba(0, 170, 255, 55), stop:0.343284 rgba(0, 170, 255, 156), stop:0.701493 rgba(0, 170, 255, 63), stop:0.840796 rgba(0, 170, 255, 179));")
        self.menuEventos.setObjectName("menuEventos")
        self.menuCrear_hojas = QtWidgets.QMenu(self.menubar)
        self.menuCrear_hojas.setStyleSheet("selection-background-color: rgba(225, 225, 225, 150);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0149254 rgba(0, 170, 255, 178), stop:0.179104 rgba(0, 170, 255, 55), stop:0.343284 rgba(0, 170, 255, 156), stop:0.701493 rgba(0, 170, 255, 63), stop:0.840796 rgba(0, 170, 255, 179));")
        self.menuCrear_hojas.setObjectName("menuCrear_hojas")
        self.menuProveedores = QtWidgets.QMenu(self.menubar)
        self.menuProveedores.setStyleSheet("selection-background-color: rgba(225, 225, 225, 150);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0149254 rgba(0, 170, 255, 178), stop:0.179104 rgba(0, 170, 255, 55), stop:0.343284 rgba(0, 170, 255, 156), stop:0.701493 rgba(0, 170, 255, 63), stop:0.840796 rgba(0, 170, 255, 179));")
        self.menuProveedores.setObjectName("menuProveedores")
        self.menuRecintos = QtWidgets.QMenu(self.menubar)
        self.menuRecintos.setStyleSheet("selection-background-color: rgba(225, 225, 225, 150);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0149254 rgba(0, 170, 255, 178), stop:0.179104 rgba(0, 170, 255, 55), stop:0.343284 rgba(0, 170, 255, 156), stop:0.701493 rgba(0, 170, 255, 63), stop:0.840796 rgba(0, 170, 255, 179));")
        self.menuRecintos.setObjectName("menuRecintos")
        MainWindow.setMenuBar(self.menubar)
        self.action_crear_hoja_de_ruta = QtWidgets.QAction(MainWindow)
        self.action_crear_hoja_de_ruta.setObjectName("action_crear_hoja_de_ruta")
        self.action_crear_hoja_de_bolos = QtWidgets.QAction(MainWindow)
        self.action_crear_hoja_de_bolos.setObjectName("action_crear_hoja_de_bolos")
        self.action_crear_hoja_de_almac_n = QtWidgets.QAction(MainWindow)
        self.action_crear_hoja_de_almac_n.setObjectName("action_crear_hoja_de_almac_n")
        self.action_guardar = QtWidgets.QAction(MainWindow)
        self.action_guardar.setObjectName("action_guardar")
        self.action_imprimir = QtWidgets.QAction(MainWindow)
        self.action_imprimir.setObjectName("action_imprimir")
        self.action_crear_hoja_de_transportes = QtWidgets.QAction(MainWindow)
        self.action_crear_hoja_de_transportes.setObjectName("action_crear_hoja_de_transportes")
        self.action_crear_evento = QtWidgets.QAction(MainWindow)
        self.action_crear_evento.setObjectName("action_crear_evento")
        self.action_consultar_evento = QtWidgets.QAction(MainWindow)
        self.action_consultar_evento.setObjectName("action_consultar_evento")
        self.action_alta_personal = QtWidgets.QAction(MainWindow)
        self.action_alta_personal.setObjectName("action_alta_personal")
        self.action_consultar_personal = QtWidgets.QAction(MainWindow)
        self.action_consultar_personal.setObjectName("action_consultar_personal")
        self.action_alta_proveedor = QtWidgets.QAction(MainWindow)
        self.action_alta_proveedor.setObjectName("action_alta_proveedor")
        self.action_consultar_proveedor = QtWidgets.QAction(MainWindow)
        self.action_consultar_proveedor.setObjectName("action_consultar_proveedor")
        self.action_alta_recinto = QtWidgets.QAction(MainWindow)
        self.action_alta_recinto.setObjectName("action_alta_recinto")
        self.action_consultar_recintos = QtWidgets.QAction(MainWindow)
        self.action_consultar_recintos.setObjectName("action_consultar_recintos")
        self.actionProject_Managers = QtWidgets.QAction(MainWindow)
        self.actionProject_Managers.setObjectName("actionProject_Managers")
        self.menuArchivo.addAction(self.action_guardar)
        self.menuArchivo.addAction(self.action_imprimir)
        self.menuPersonal.addAction(self.action_alta_personal)
        self.menuPersonal.addAction(self.action_consultar_personal)
        self.menuPersonal.addAction(self.actionProject_Managers)
        self.menuEventos.addAction(self.action_crear_evento)
        self.menuEventos.addAction(self.action_consultar_evento)
        self.menuCrear_hojas.addAction(self.action_crear_hoja_de_ruta)
        self.menuCrear_hojas.addAction(self.action_crear_hoja_de_bolos)
        self.menuCrear_hojas.addAction(self.action_crear_hoja_de_almac_n)
        self.menuCrear_hojas.addAction(self.action_crear_hoja_de_transportes)
        self.menuProveedores.addAction(self.action_alta_proveedor)
        self.menuProveedores.addAction(self.action_consultar_proveedor)
        self.menuRecintos.addAction(self.action_alta_recinto)
        self.menuRecintos.addAction(self.action_consultar_recintos)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEventos.menuAction())
        self.menubar.addAction(self.menuPersonal.menuAction())
        self.menubar.addAction(self.menuProveedores.menuAction())
        self.menubar.addAction(self.menuRecintos.menuAction())
        self.menubar.addAction(self.menuCrear_hojas.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonPrev30.setText(_translate("MainWindow", "<<<"))
        self.buttonPrev7.setText(_translate("MainWindow", "<< "))
        self.buttonPrev1.setText(_translate("MainWindow", " < "))
        self.labelVista.setText(_translate("MainWindow", "Vista Semanal"))
        self.buttonNext1.setText(_translate("MainWindow", " > "))
        self.buttonNext7.setText(_translate("MainWindow", " >>"))
        self.buttonNext30.setText(_translate("MainWindow", ">>>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Lunes"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Martes"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Miércoles"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Jueves"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Viernes"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Sábado"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Domingo"))
        self.label.setText(_translate("MainWindow", "Sin\n"
"confirmar"))
        self.label_2.setText(_translate("MainWindow", "Falta\n"
"personal"))
        self.label_3.setText(_translate("MainWindow", "Falta\n"
"proveedor"))
        self.label_4.setText(_translate("MainWindow", "Cerrado"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuPersonal.setTitle(_translate("MainWindow", "Personal"))
        self.menuEventos.setTitle(_translate("MainWindow", "Eventos"))
        self.menuCrear_hojas.setTitle(_translate("MainWindow", "Crear hojas"))
        self.menuProveedores.setTitle(_translate("MainWindow", "Proveedores"))
        self.menuRecintos.setTitle(_translate("MainWindow", "Recintos"))
        self.action_crear_hoja_de_ruta.setText(_translate("MainWindow", "Crear hoja de ruta"))
        self.action_crear_hoja_de_bolos.setText(_translate("MainWindow", "Crear hoja de bolos"))
        self.action_crear_hoja_de_almac_n.setText(_translate("MainWindow", "Crear hoja de almacén"))
        self.action_guardar.setText(_translate("MainWindow", "Guardar"))
        self.action_imprimir.setText(_translate("MainWindow", "Imprimir"))
        self.action_crear_hoja_de_transportes.setText(_translate("MainWindow", "Crear hoja de transportes"))
        self.action_crear_evento.setText(_translate("MainWindow", "Crear Evento"))
        self.action_consultar_evento.setText(_translate("MainWindow", "Consultar Evento"))
        self.action_alta_personal.setText(_translate("MainWindow", "Alta BBDD"))
        self.action_consultar_personal.setText(_translate("MainWindow", "Consultar BBDD"))
        self.action_alta_proveedor.setText(_translate("MainWindow", "Alta BBDD"))
        self.action_consultar_proveedor.setText(_translate("MainWindow", "Consultar BBDD"))
        self.action_alta_recinto.setText(_translate("MainWindow", "Alta BBDD"))
        self.action_consultar_recintos.setText(_translate("MainWindow", "Consultar BBDD"))
        self.actionProject_Managers.setText(_translate("MainWindow", "Project Managers"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = MenuPrincipal_Ui()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

