# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menuprincipal_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class MenuPrincipal_Ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 569)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(202, 202, 202);\n"
"background-color: rgb(227, 227, 227);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1281, 491))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toolButton_3 = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout.addWidget(self.toolButton_3)
        self.toolButton_2 = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout.addWidget(self.toolButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.tableWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 26))
        self.menubar.setStyleSheet("selection-background-color: rgba(225, 225, 225, 150);\n"
"background-color: rgba(185, 0, 0, 180);")
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setStyleSheet("selection-background-color: rgba(200, 200, 200, 125);\n"
"selection-color: rgb(0, 0, 0);\n"
"background-color: rgb(185, 0, 0,180);\n"
"")
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuPersonal = QtWidgets.QMenu(self.menubar)
        self.menuPersonal.setStyleSheet("selection-background-color: rgba(200, 200, 200, 125);\n"
"selection-color: rgb(0, 0, 0);\n"
"background-color: rgb(185, 0, 0,180);\n"
"")
        self.menuPersonal.setObjectName("menuPersonal")
        self.menuEventos = QtWidgets.QMenu(self.menubar)
        self.menuEventos.setStyleSheet("selection-background-color: rgba(200, 200, 200, 125);\n"
"selection-color: rgb(0, 0, 0);\n"
"background-color: rgb(185, 0, 0,180);\n"
"")
        self.menuEventos.setObjectName("menuEventos")
        self.menuCrear_hojas = QtWidgets.QMenu(self.menubar)
        self.menuCrear_hojas.setStyleSheet("selection-background-color: rgba(200, 200, 200, 125);\n"
"selection-color: rgb(0, 0, 0);\n"
"background-color: rgb(185, 0, 0,180);\n"
"")
        self.menuCrear_hojas.setObjectName("menuCrear_hojas")
        self.menuProveedores = QtWidgets.QMenu(self.menubar)
        self.menuProveedores.setStyleSheet("selection-background-color: rgba(200, 200, 200, 125);\n"
"selection-color: rgb(0, 0, 0);\n"
"background-color: rgb(185, 0, 0,180);\n"
"")
        self.menuProveedores.setObjectName("menuProveedores")
        self.menuRecintos = QtWidgets.QMenu(self.menubar)
        self.menuRecintos.setStyleSheet("selection-background-color: rgba(200, 200, 200, 125);\n"
"selection-color: rgb(0, 0, 0);\n"
"background-color: rgb(185, 0, 0,180);\n"
"")
        self.menuRecintos.setObjectName("menuRecintos")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_crear_hoja_de_ruta = QtWidgets.QAction(MainWindow)
        self.action_crear_hoja_de_ruta.setObjectName("action_crear_hoja_de_ruta")
        self.action_crear_hoja_de_bolos = QtWidgets.QAction(MainWindow)
        self.action_crear_hoja_de_bolos.setObjectName("action_crear_hoja_de_bolos")
        self.action_crear_hoja_de_almac_n = QtWidgets.QAction(MainWindow)
        self.action_crear_hoja_de_almac_n.setObjectName("action_crear_hoja_de_almac_n")
        self.action_guardar = QtWidgets.QAction(MainWindow)
        self.action_guardar.setObjectName("action_guardar")
        self.action_imprimir = QtWidgets.QAction(MainWindow)
        self.action_imprimir.setObjectName("action_imprimir")
        self.action_crear_hoja_de_transportes = QtWidgets.QAction(MainWindow)
        self.action_crear_hoja_de_transportes.setObjectName("action_crear_hoja_de_transportes")
        self.action_crear_evento = QtWidgets.QAction(MainWindow)
        self.action_crear_evento.setObjectName("action_crear_evento")
        self.action_consultar_evento = QtWidgets.QAction(MainWindow)
        self.action_consultar_evento.setObjectName("action_consultar_evento")
        self.action_alta_personal = QtWidgets.QAction(MainWindow)
        self.action_alta_personal.setObjectName("action_alta_personal")
        self.action_consultar_personal = QtWidgets.QAction(MainWindow)
        self.action_consultar_personal.setObjectName("action_consultar_personal")
        self.action_alta_proveedor = QtWidgets.QAction(MainWindow)
        self.action_alta_proveedor.setObjectName("action_alta_proveedor")
        self.action_consultar_proveedor = QtWidgets.QAction(MainWindow)
        self.action_consultar_proveedor.setObjectName("action_consultar_proveedor")
        self.action_alta_recinto = QtWidgets.QAction(MainWindow)
        self.action_alta_recinto.setObjectName("action_alta_recinto")
        self.action_consultar_recintos = QtWidgets.QAction(MainWindow)
        self.action_consultar_recintos.setObjectName("action_consultar_recintos")
        self.actionProject_Managers = QtWidgets.QAction(MainWindow)
        self.actionProject_Managers.setObjectName("actionProject_Managers")
        self.menuArchivo.addAction(self.action_guardar)
        self.menuArchivo.addAction(self.action_imprimir)
        self.menuPersonal.addAction(self.action_alta_personal)
        self.menuPersonal.addAction(self.action_consultar_personal)
        self.menuPersonal.addAction(self.actionProject_Managers)
        self.menuEventos.addAction(self.action_crear_evento)
        self.menuEventos.addAction(self.action_consultar_evento)
        self.menuCrear_hojas.addAction(self.action_crear_hoja_de_ruta)
        self.menuCrear_hojas.addAction(self.action_crear_hoja_de_bolos)
        self.menuCrear_hojas.addAction(self.action_crear_hoja_de_almac_n)
        self.menuCrear_hojas.addAction(self.action_crear_hoja_de_transportes)
        self.menuProveedores.addAction(self.action_alta_proveedor)
        self.menuProveedores.addAction(self.action_consultar_proveedor)
        self.menuRecintos.addAction(self.action_alta_recinto)
        self.menuRecintos.addAction(self.action_consultar_recintos)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEventos.menuAction())
        self.menubar.addAction(self.menuPersonal.menuAction())
        self.menubar.addAction(self.menuProveedores.menuAction())
        self.menubar.addAction(self.menuRecintos.menuAction())
        self.menubar.addAction(self.menuCrear_hojas.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton_3.setText(_translate("MainWindow", "<"))
        self.toolButton_2.setText(_translate("MainWindow", ">"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Lunes"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Martes"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Miércoles"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Jueves"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Viernes"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Sábado"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Domingo"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuPersonal.setTitle(_translate("MainWindow", "Personal"))
        self.menuEventos.setTitle(_translate("MainWindow", "Eventos"))
        self.menuCrear_hojas.setTitle(_translate("MainWindow", "Crear hojas"))
        self.menuProveedores.setTitle(_translate("MainWindow", "Proveedores"))
        self.menuRecintos.setTitle(_translate("MainWindow", "Recintos"))
        self.action_crear_hoja_de_ruta.setText(_translate("MainWindow", "Crear hoja de ruta"))
        self.action_crear_hoja_de_bolos.setText(_translate("MainWindow", "Crear hoja de bolos"))
        self.action_crear_hoja_de_almac_n.setText(_translate("MainWindow", "Crear hoja de almacén"))
        self.action_guardar.setText(_translate("MainWindow", "Guardar"))
        self.action_imprimir.setText(_translate("MainWindow", "Imprimir"))
        self.action_crear_hoja_de_transportes.setText(_translate("MainWindow", "Crear hoja de transportes"))
        self.action_crear_evento.setText(_translate("MainWindow", "Crear Evento"))
        self.action_consultar_evento.setText(_translate("MainWindow", "Consultar Evento"))
        self.action_alta_personal.setText(_translate("MainWindow", "Alta BBDD"))
        self.action_consultar_personal.setText(_translate("MainWindow", "Consultar BBDD"))
        self.action_alta_proveedor.setText(_translate("MainWindow", "Alta BBDD"))
        self.action_consultar_proveedor.setText(_translate("MainWindow", "Consultar BBDD"))
        self.action_alta_recinto.setText(_translate("MainWindow", "Alta BBDD"))
        self.action_consultar_recintos.setText(_translate("MainWindow", "Consultar BBDD"))
        self.actionProject_Managers.setText(_translate("MainWindow", "Project Managers"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = MenuPrincipal_Ui()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

