# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'personalevento_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class PersonalEvento_Ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(368, 455)
        self.labelProject = QtWidgets.QLabel(Dialog)
        self.labelProject.setGeometry(QtCore.QRect(40, 30, 181, 31))
        self.labelProject.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.labelProject.setObjectName("labelProject")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 80, 317, 310))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelCargo = QtWidgets.QLabel(self.layoutWidget)
        self.labelCargo.setObjectName("labelCargo")
        self.gridLayout.addWidget(self.labelCargo, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        self.inputSuplem = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputSuplem.setObjectName("inputSuplem")
        self.gridLayout.addWidget(self.inputSuplem, 5, 1, 1, 1)
        self.labelSuplem = QtWidgets.QLabel(self.layoutWidget)
        self.labelSuplem.setObjectName("labelSuplem")
        self.gridLayout.addWidget(self.labelSuplem, 5, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 5, 2, 1, 1)
        self.inputFecha = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputFecha.setEnabled(False)
        self.inputFecha.setObjectName("inputFecha")
        self.gridLayout.addWidget(self.inputFecha, 4, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 2, 1, 1)
        self.labelFecha = QtWidgets.QLabel(self.layoutWidget)
        self.labelFecha.setObjectName("labelFecha")
        self.gridLayout.addWidget(self.labelFecha, 4, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 4, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 3, 1, 1, 1)
        self.labelApellidos = QtWidgets.QLabel(self.layoutWidget)
        self.labelApellidos.setObjectName("labelApellidos")
        self.gridLayout.addWidget(self.labelApellidos, 2, 0, 1, 1)
        self.inputApellidos = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputApellidos.setEnabled(False)
        self.inputApellidos.setObjectName("inputApellidos")
        self.gridLayout.addWidget(self.inputApellidos, 2, 1, 1, 1)
        self.labelNombre = QtWidgets.QLabel(self.layoutWidget)
        self.labelNombre.setObjectName("labelNombre")
        self.gridLayout.addWidget(self.labelNombre, 1, 0, 1, 1)
        self.inputNombre = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputNombre.setEnabled(False)
        self.inputNombre.setObjectName("inputNombre")
        self.gridLayout.addWidget(self.inputNombre, 1, 1, 1, 1)
        self.inputCodigo = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputCodigo.setEnabled(False)
        self.inputCodigo.setObjectName("inputCodigo")
        self.gridLayout.addWidget(self.inputCodigo, 0, 1, 1, 1)
        self.labelCodigo = QtWidgets.QLabel(self.layoutWidget)
        self.labelCodigo.setObjectName("labelCodigo")
        self.gridLayout.addWidget(self.labelCodigo, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(33, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 6, 2, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 410, 241, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonGuardar = QtWidgets.QPushButton(self.layoutWidget1)
        self.buttonGuardar.setObjectName("buttonGuardar")
        self.horizontalLayout.addWidget(self.buttonGuardar)
        self.buttonCancelar = QtWidgets.QPushButton(self.layoutWidget1)
        self.buttonCancelar.setObjectName("buttonCancelar")
        self.horizontalLayout.addWidget(self.buttonCancelar)
        
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.inputFecha, self.inputSuplem)
        Dialog.setTabOrder(self.inputSuplem, self.buttonGuardar)
        Dialog.setTabOrder(self.buttonGuardar, self.buttonCancelar)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelProject.setText(_translate("Dialog", "Personal del evento"))
        self.labelCargo.setText(_translate("Dialog", "Cargo"))
        self.labelSuplem.setText(_translate("Dialog", "Suplemento"))
        self.labelFecha.setText(_translate("Dialog", "Fecha"))
        self.labelApellidos.setText(_translate("Dialog", "Apellidos"))
        self.labelNombre.setText(_translate("Dialog", "Nombre"))
        self.labelCodigo.setText(_translate("Dialog", "Código"))
        self.buttonGuardar.setText(_translate("Dialog", "Aceptar"))
        self.buttonCancelar.setText(_translate("Dialog", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = PersonalEvento_Ui()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

