# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recintos_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Recintos_Ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1408, 550)
        self.tableRecintos = QtWidgets.QTableWidget(Dialog)
        self.tableRecintos.setGeometry(QtCore.QRect(40, 90, 1001, 391))
        self.tableRecintos.setObjectName("tableRecintos")
        self.tableRecintos.setColumnCount(9)
        self.tableRecintos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(8, item)
        self.labelProject = QtWidgets.QLabel(Dialog)
        self.labelProject.setGeometry(QtCore.QRect(40, 30, 181, 31))
        self.labelProject.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.labelProject.setObjectName("labelProject")
        self.buttonAnadir = QtWidgets.QPushButton(Dialog)
        self.buttonAnadir.setGeometry(QtCore.QRect(1180, 430, 93, 28))
        self.buttonAnadir.setObjectName("buttonAnadir")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(1070, 90, 317, 306))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 3, 1, 1)
        self.inputContacto = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputContacto.setObjectName("inputContacto")
        self.gridLayout.addWidget(self.inputContacto, 3, 2, 1, 1)
        self.labelTelefono = QtWidgets.QLabel(self.layoutWidget)
        self.labelTelefono.setObjectName("labelTelefono")
        self.gridLayout.addWidget(self.labelTelefono, 4, 0, 1, 1)
        self.inputTelefono = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputTelefono.setObjectName("inputTelefono")
        self.gridLayout.addWidget(self.inputTelefono, 4, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(13, 101, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 7, 1, 2, 1)
        self.labelContacto = QtWidgets.QLabel(self.layoutWidget)
        self.labelContacto.setObjectName("labelContacto")
        self.gridLayout.addWidget(self.labelContacto, 3, 0, 1, 1)
        self.labelNotas = QtWidgets.QLabel(self.layoutWidget)
        self.labelNotas.setObjectName("labelNotas")
        self.gridLayout.addWidget(self.labelNotas, 7, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 3, 1, 1)
        self.inputCiudad = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputCiudad.setObjectName("inputCiudad")
        self.gridLayout.addWidget(self.inputCiudad, 2, 2, 1, 1)
        self.labelDireccion = QtWidgets.QLabel(self.layoutWidget)
        self.labelDireccion.setObjectName("labelDireccion")
        self.gridLayout.addWidget(self.labelDireccion, 1, 0, 1, 2)
        self.inputNombre = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputNombre.setObjectName("inputNombre")
        self.gridLayout.addWidget(self.inputNombre, 0, 2, 1, 1)
        self.inputDireccion = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputDireccion.setObjectName("inputDireccion")
        self.gridLayout.addWidget(self.inputDireccion, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 3, 1, 1)
        self.labelCiudad = QtWidgets.QLabel(self.layoutWidget)
        self.labelCiudad.setObjectName("labelCiudad")
        self.gridLayout.addWidget(self.labelCiudad, 2, 0, 1, 2)
        self.labelNombre = QtWidgets.QLabel(self.layoutWidget)
        self.labelNombre.setObjectName("labelNombre")
        self.gridLayout.addWidget(self.labelNombre, 0, 0, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(33, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 6, 3, 1, 1)
        self.inputWeb = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputWeb.setObjectName("inputWeb")
        self.gridLayout.addWidget(self.inputWeb, 6, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 8, 0, 1, 1)
        self.inputEmail = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputEmail.setObjectName("inputEmail")
        self.gridLayout.addWidget(self.inputEmail, 5, 2, 1, 1)
        self.labelEmail = QtWidgets.QLabel(self.layoutWidget)
        self.labelEmail.setObjectName("labelEmail")
        self.gridLayout.addWidget(self.labelEmail, 5, 0, 1, 1)
        self.labelWeb = QtWidgets.QLabel(self.layoutWidget)
        self.labelWeb.setObjectName("labelWeb")
        self.gridLayout.addWidget(self.labelWeb, 6, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 5, 3, 1, 1)
        self.inputNotas = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.inputNotas.setPlainText("")
        self.inputNotas.setObjectName("inputNotas")
        self.gridLayout.addWidget(self.inputNotas, 7, 2, 2, 2)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 490, 241, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonGuardar = QtWidgets.QPushButton(self.layoutWidget1)
        self.buttonGuardar.setObjectName("buttonGuardar")
        self.horizontalLayout.addWidget(self.buttonGuardar)
        self.buttonEliminar = QtWidgets.QPushButton(self.layoutWidget1)
        self.buttonEliminar.setObjectName("buttonEliminar")
        self.horizontalLayout.addWidget(self.buttonEliminar)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.inputNombre, self.inputDireccion)
        Dialog.setTabOrder(self.inputDireccion, self.inputCiudad)
        Dialog.setTabOrder(self.inputCiudad, self.inputContacto)
        Dialog.setTabOrder(self.inputContacto, self.inputTelefono)
        Dialog.setTabOrder(self.inputTelefono, self.inputEmail)
        Dialog.setTabOrder(self.inputEmail, self.inputWeb)
        Dialog.setTabOrder(self.inputWeb, self.inputNotas)
        Dialog.setTabOrder(self.inputNotas, self.buttonAnadir)
        Dialog.setTabOrder(self.buttonAnadir, self.tableRecintos)
        Dialog.setTabOrder(self.tableRecintos, self.buttonGuardar)
        Dialog.setTabOrder(self.buttonGuardar, self.buttonEliminar)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableRecintos.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID Recinto"))
        item = self.tableRecintos.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nombre"))
        item = self.tableRecintos.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Dirección"))
        item = self.tableRecintos.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Ciudad"))
        item = self.tableRecintos.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Contacto"))
        item = self.tableRecintos.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Teléfono"))
        item = self.tableRecintos.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Email"))
        item = self.tableRecintos.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Web"))
        item = self.tableRecintos.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Notas"))
        self.labelProject.setText(_translate("Dialog", "Recintos"))
        self.buttonAnadir.setText(_translate("Dialog", "Añadir"))
        self.labelTelefono.setText(_translate("Dialog", "Teléfono"))
        self.labelContacto.setText(_translate("Dialog", "Contacto"))
        self.labelNotas.setText(_translate("Dialog", "Notas"))
        self.labelDireccion.setText(_translate("Dialog", "Dirección"))
        self.labelCiudad.setText(_translate("Dialog", "Ciudad"))
        self.labelNombre.setText(_translate("Dialog", "Nombre"))
        self.labelEmail.setText(_translate("Dialog", "Email"))
        self.labelWeb.setText(_translate("Dialog", "Web"))
        self.buttonGuardar.setText(_translate("Dialog", "Guardar cambios"))
        self.buttonEliminar.setText(_translate("Dialog", "Eliminar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Recintos_Ui()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

