# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recintos_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Recintos_Ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1201, 753)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelTitle = QtWidgets.QLabel(Form)
        self.labelTitle.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout_2.addWidget(self.labelTitle)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableRecintos = QtWidgets.QTableWidget(Form)
        self.tableRecintos.setObjectName("tableRecintos")
        self.tableRecintos.setColumnCount(13)
        self.tableRecintos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecintos.setHorizontalHeaderItem(12, item)
        self.horizontalLayout_3.addWidget(self.tableRecintos)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelWeb = QtWidgets.QLabel(Form)
        self.labelWeb.setObjectName("labelWeb")
        self.gridLayout.addWidget(self.labelWeb, 10, 0, 1, 1)
        self.labelTelefono = QtWidgets.QLabel(Form)
        self.labelTelefono.setObjectName("labelTelefono")
        self.gridLayout.addWidget(self.labelTelefono, 8, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 9, 3, 1, 1)
        self.labelCiudad = QtWidgets.QLabel(Form)
        self.labelCiudad.setObjectName("labelCiudad")
        self.gridLayout.addWidget(self.labelCiudad, 3, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 3, 1, 1)
        self.inputEmail = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputEmail.sizePolicy().hasHeightForWidth())
        self.inputEmail.setSizePolicy(sizePolicy)
        self.inputEmail.setMinimumSize(QtCore.QSize(400, 0))
        self.inputEmail.setObjectName("inputEmail")
        self.gridLayout.addWidget(self.inputEmail, 9, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(33, 19, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 10, 3, 1, 1)
        self.labelEmail = QtWidgets.QLabel(Form)
        self.labelEmail.setObjectName("labelEmail")
        self.gridLayout.addWidget(self.labelEmail, 9, 0, 1, 1)
        self.inputNotas = QtWidgets.QPlainTextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNotas.sizePolicy().hasHeightForWidth())
        self.inputNotas.setSizePolicy(sizePolicy)
        self.inputNotas.setMinimumSize(QtCore.QSize(400, 0))
        self.inputNotas.setPlainText("")
        self.inputNotas.setObjectName("inputNotas")
        self.gridLayout.addWidget(self.inputNotas, 11, 2, 2, 2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 8, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 14, 2, 1, 1)
        self.inputCiudad = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputCiudad.sizePolicy().hasHeightForWidth())
        self.inputCiudad.setSizePolicy(sizePolicy)
        self.inputCiudad.setMinimumSize(QtCore.QSize(400, 0))
        self.inputCiudad.setObjectName("inputCiudad")
        self.gridLayout.addWidget(self.inputCiudad, 3, 2, 1, 1)
        self.inputWeb = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputWeb.sizePolicy().hasHeightForWidth())
        self.inputWeb.setSizePolicy(sizePolicy)
        self.inputWeb.setMinimumSize(QtCore.QSize(400, 0))
        self.inputWeb.setObjectName("inputWeb")
        self.gridLayout.addWidget(self.inputWeb, 10, 2, 1, 1)
        self.inputTelefono = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputTelefono.sizePolicy().hasHeightForWidth())
        self.inputTelefono.setSizePolicy(sizePolicy)
        self.inputTelefono.setMinimumSize(QtCore.QSize(400, 0))
        self.inputTelefono.setObjectName("inputTelefono")
        self.gridLayout.addWidget(self.inputTelefono, 8, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(13, 101, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 11, 1, 2, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 1, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 7, 3, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem11, 12, 0, 1, 1)
        self.labelNotas = QtWidgets.QLabel(Form)
        self.labelNotas.setObjectName("labelNotas")
        self.gridLayout.addWidget(self.labelNotas, 11, 0, 1, 1)
        self.labelNombre = QtWidgets.QLabel(Form)
        self.labelNombre.setObjectName("labelNombre")
        self.gridLayout.addWidget(self.labelNombre, 0, 0, 1, 2)
        self.inputNombre = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNombre.sizePolicy().hasHeightForWidth())
        self.inputNombre.setSizePolicy(sizePolicy)
        self.inputNombre.setMinimumSize(QtCore.QSize(400, 0))
        self.inputNombre.setObjectName("inputNombre")
        self.gridLayout.addWidget(self.inputNombre, 0, 2, 1, 1)
        self.labelContacto = QtWidgets.QLabel(Form)
        self.labelContacto.setObjectName("labelContacto")
        self.gridLayout.addWidget(self.labelContacto, 7, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem12)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.buttonAnadir = QtWidgets.QPushButton(Form)
        self.buttonAnadir.setObjectName("buttonAnadir")
        self.horizontalLayout_2.addWidget(self.buttonAnadir)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 13, 2, 1, 1)
        self.inputContacto = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputContacto.sizePolicy().hasHeightForWidth())
        self.inputContacto.setSizePolicy(sizePolicy)
        self.inputContacto.setMinimumSize(QtCore.QSize(400, 0))
        self.inputContacto.setObjectName("inputContacto")
        self.gridLayout.addWidget(self.inputContacto, 7, 2, 1, 1)
        self.labelDireccion = QtWidgets.QLabel(Form)
        self.labelDireccion.setObjectName("labelDireccion")
        self.gridLayout.addWidget(self.labelDireccion, 4, 0, 1, 1)
        self.labelPais = QtWidgets.QLabel(Form)
        self.labelPais.setObjectName("labelPais")
        self.gridLayout.addWidget(self.labelPais, 1, 0, 1, 1)
        self.comboPais = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboPais.sizePolicy().hasHeightForWidth())
        self.comboPais.setSizePolicy(sizePolicy)
        self.comboPais.setMinimumSize(QtCore.QSize(400, 25))
        self.comboPais.setObjectName("comboPais")
        self.gridLayout.addWidget(self.comboPais, 1, 2, 1, 1)
        self.inputDireccion = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputDireccion.sizePolicy().hasHeightForWidth())
        self.inputDireccion.setSizePolicy(sizePolicy)
        self.inputDireccion.setMinimumSize(QtCore.QSize(400, 0))
        self.inputDireccion.setObjectName("inputDireccion")
        self.gridLayout.addWidget(self.inputDireccion, 4, 2, 1, 1)
        self.labelIndicaciones = QtWidgets.QLabel(Form)
        self.labelIndicaciones.setObjectName("labelIndicaciones")
        self.gridLayout.addWidget(self.labelIndicaciones, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.comboProvincia = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboProvincia.sizePolicy().hasHeightForWidth())
        self.comboProvincia.setSizePolicy(sizePolicy)
        self.comboProvincia.setMinimumSize(QtCore.QSize(400, 25))
        self.comboProvincia.setObjectName("comboProvincia")
        self.gridLayout.addWidget(self.comboProvincia, 2, 2, 1, 1)
        self.labelCoordenadas = QtWidgets.QLabel(Form)
        self.labelCoordenadas.setObjectName("labelCoordenadas")
        self.gridLayout.addWidget(self.labelCoordenadas, 6, 0, 1, 1)
        self.inputIndicaciones = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputIndicaciones.sizePolicy().hasHeightForWidth())
        self.inputIndicaciones.setSizePolicy(sizePolicy)
        self.inputIndicaciones.setMinimumSize(QtCore.QSize(400, 0))
        self.inputIndicaciones.setObjectName("inputIndicaciones")
        self.gridLayout.addWidget(self.inputIndicaciones, 5, 2, 1, 1)
        self.inputCoordenadas = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputCoordenadas.sizePolicy().hasHeightForWidth())
        self.inputCoordenadas.setSizePolicy(sizePolicy)
        self.inputCoordenadas.setMinimumSize(QtCore.QSize(400, 0))
        self.inputCoordenadas.setObjectName("inputCoordenadas")
        self.gridLayout.addWidget(self.inputCoordenadas, 6, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonGuardar = QtWidgets.QPushButton(Form)
        self.buttonGuardar.setObjectName("buttonGuardar")
        self.horizontalLayout.addWidget(self.buttonGuardar)
        self.buttonEliminar = QtWidgets.QPushButton(Form)
        self.buttonEliminar.setObjectName("buttonEliminar")
        self.horizontalLayout.addWidget(self.buttonEliminar)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.inputNombre, self.comboPais)
        Form.setTabOrder(self.comboPais, self.comboProvincia)
        Form.setTabOrder(self.comboProvincia, self.inputCiudad)
        Form.setTabOrder(self.inputCiudad, self.inputDireccion)
        Form.setTabOrder(self.inputDireccion, self.inputIndicaciones)
        Form.setTabOrder(self.inputIndicaciones, self.inputCoordenadas)
        Form.setTabOrder(self.inputCoordenadas, self.inputContacto)
        Form.setTabOrder(self.inputContacto, self.inputTelefono)
        Form.setTabOrder(self.inputTelefono, self.inputEmail)
        Form.setTabOrder(self.inputEmail, self.inputWeb)
        Form.setTabOrder(self.inputWeb, self.inputNotas)
        Form.setTabOrder(self.inputNotas, self.buttonAnadir)
        Form.setTabOrder(self.buttonAnadir, self.buttonGuardar)
        Form.setTabOrder(self.buttonGuardar, self.buttonEliminar)
        Form.setTabOrder(self.buttonEliminar, self.tableRecintos)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelTitle.setText(_translate("Form", "Recintos"))
        item = self.tableRecintos.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID Recinto"))
        item = self.tableRecintos.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nombre"))
        item = self.tableRecintos.horizontalHeaderItem(2)
        item.setText(_translate("Form", "País"))
        item = self.tableRecintos.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Provincia"))
        item = self.tableRecintos.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Ciudad"))
        item = self.tableRecintos.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Dirección"))
        item = self.tableRecintos.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Indicaciones"))
        item = self.tableRecintos.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Coordenadas"))
        item = self.tableRecintos.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Contacto"))
        item = self.tableRecintos.horizontalHeaderItem(9)
        item.setText(_translate("Form", "Teléfono"))
        item = self.tableRecintos.horizontalHeaderItem(10)
        item.setText(_translate("Form", "Email"))
        item = self.tableRecintos.horizontalHeaderItem(11)
        item.setText(_translate("Form", "Web"))
        item = self.tableRecintos.horizontalHeaderItem(12)
        item.setText(_translate("Form", "Notas"))
        self.labelWeb.setText(_translate("Form", "Web"))
        self.labelTelefono.setText(_translate("Form", "Teléfono"))
        self.labelCiudad.setText(_translate("Form", "Localidad"))
        self.labelEmail.setText(_translate("Form", "Email"))
        self.labelNotas.setText(_translate("Form", "Notas"))
        self.labelNombre.setText(_translate("Form", "Nombre"))
        self.labelContacto.setText(_translate("Form", "Contacto"))
        self.buttonAnadir.setText(_translate("Form", "Añadir"))
        self.labelDireccion.setText(_translate("Form", "Dirección"))
        self.labelPais.setText(_translate("Form", "Pais"))
        self.labelIndicaciones.setText(_translate("Form", "Indicaciones"))
        self.label.setText(_translate("Form", "Provincia"))
        self.labelCoordenadas.setText(_translate("Form", "Coordenadas"))
        self.buttonGuardar.setText(_translate("Form", "Guardar cambios"))
        self.buttonEliminar.setText(_translate("Form", "Eliminar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Recintos_Ui()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

