# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectcliente.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class SelectCliente_Ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1316, 753)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle.sizePolicy().hasHeightForWidth())
        self.labelTitle.setSizePolicy(sizePolicy)
        self.labelTitle.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(180, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableClientes = QtWidgets.QTableWidget(Form)
        self.tableClientes.setObjectName("tableClientes")
        self.tableClientes.setColumnCount(14)
        self.tableClientes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientes.setHorizontalHeaderItem(13, item)
        self.verticalLayout.addWidget(self.tableClientes)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonSeleccionar = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSeleccionar.sizePolicy().hasHeightForWidth())
        self.buttonSeleccionar.setSizePolicy(sizePolicy)
        self.buttonSeleccionar.setMinimumSize(QtCore.QSize(100, 35))
        self.buttonSeleccionar.setObjectName("buttonSeleccionar")
        self.horizontalLayout.addWidget(self.buttonSeleccionar)
        self.buttonAdd = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAdd.sizePolicy().hasHeightForWidth())
        self.buttonAdd.setSizePolicy(sizePolicy)
        self.buttonAdd.setMinimumSize(QtCore.QSize(100, 35))
        self.buttonAdd.setObjectName("buttonAdd")
        self.horizontalLayout.addWidget(self.buttonAdd)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.buttonSeleccionar, self.tableClientes)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Clientes"))
        self.labelTitle.setText(_translate("Form", "Seleccionar Cliente"))
        self.label.setText(_translate("Form", "Filtrar por nombre"))
        item = self.tableClientes.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Id Cliente"))
        item = self.tableClientes.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nombre"))
        item = self.tableClientes.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Pais"))
        item = self.tableClientes.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Provincia"))
        item = self.tableClientes.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Localidad"))
        item = self.tableClientes.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Dirección"))
        item = self.tableClientes.horizontalHeaderItem(6)
        item.setText(_translate("Form", "CIF"))
        item = self.tableClientes.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Teléfono"))
        item = self.tableClientes.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Email"))
        item = self.tableClientes.horizontalHeaderItem(9)
        item.setText(_translate("Form", "Web"))
        item = self.tableClientes.horizontalHeaderItem(10)
        item.setText(_translate("Form", "Contacto"))
        item = self.tableClientes.horizontalHeaderItem(11)
        item.setText(_translate("Form", "Tfn Contacto"))
        item = self.tableClientes.horizontalHeaderItem(12)
        item.setText(_translate("Form", "Email Contacto"))
        item = self.tableClientes.horizontalHeaderItem(13)
        item.setText(_translate("Form", "Notas"))
        self.buttonSeleccionar.setText(_translate("Form", "Seleccionar"))
        self.buttonAdd.setText(_translate("Form", "Añadir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = SelectCliente_Ui()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

