# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'personalevento_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(456, 624)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelProject = QtWidgets.QLabel(Dialog)
        self.labelProject.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.labelProject.setObjectName("labelProject")
        self.horizontalLayout_3.addWidget(self.labelProject)
        self.inputEvento = QtWidgets.QLineEdit(Dialog)
        self.inputEvento.setEnabled(False)
        self.inputEvento.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.inputEvento.setText("")
        self.inputEvento.setObjectName("inputEvento")
        self.horizontalLayout_3.addWidget(self.inputEvento)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelCodigo = QtWidgets.QLabel(Dialog)
        self.labelCodigo.setMinimumSize(QtCore.QSize(100, 0))
        self.labelCodigo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCodigo.setObjectName("labelCodigo")
        self.horizontalLayout_2.addWidget(self.labelCodigo)
        self.inputCodigo = QtWidgets.QLineEdit(Dialog)
        self.inputCodigo.setEnabled(False)
        self.inputCodigo.setMinimumSize(QtCore.QSize(192, 0))
        self.inputCodigo.setObjectName("inputCodigo")
        self.horizontalLayout_2.addWidget(self.inputCodigo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelNombre = QtWidgets.QLabel(Dialog)
        self.labelNombre.setMinimumSize(QtCore.QSize(100, 0))
        self.labelNombre.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelNombre.setObjectName("labelNombre")
        self.horizontalLayout_4.addWidget(self.labelNombre)
        self.inputNombre = QtWidgets.QLineEdit(Dialog)
        self.inputNombre.setEnabled(False)
        self.inputNombre.setMinimumSize(QtCore.QSize(192, 0))
        self.inputNombre.setObjectName("inputNombre")
        self.horizontalLayout_4.addWidget(self.inputNombre)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelApellidos = QtWidgets.QLabel(Dialog)
        self.labelApellidos.setMinimumSize(QtCore.QSize(100, 0))
        self.labelApellidos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelApellidos.setObjectName("labelApellidos")
        self.horizontalLayout_5.addWidget(self.labelApellidos)
        self.inputApellidos = QtWidgets.QLineEdit(Dialog)
        self.inputApellidos.setEnabled(False)
        self.inputApellidos.setMinimumSize(QtCore.QSize(192, 0))
        self.inputApellidos.setObjectName("inputApellidos")
        self.horizontalLayout_5.addWidget(self.inputApellidos)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelCargo = QtWidgets.QLabel(Dialog)
        self.labelCargo.setMinimumSize(QtCore.QSize(100, 0))
        self.labelCargo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCargo.setObjectName("labelCargo")
        self.horizontalLayout_6.addWidget(self.labelCargo)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setMinimumSize(QtCore.QSize(192, 0))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_6.addWidget(self.comboBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelFecha = QtWidgets.QLabel(Dialog)
        self.labelFecha.setMinimumSize(QtCore.QSize(100, 0))
        self.labelFecha.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFecha.setObjectName("labelFecha")
        self.horizontalLayout_7.addWidget(self.labelFecha)
        self.inputFecha = QtWidgets.QLineEdit(Dialog)
        self.inputFecha.setEnabled(False)
        self.inputFecha.setMinimumSize(QtCore.QSize(192, 0))
        self.inputFecha.setObjectName("inputFecha")
        self.horizontalLayout_7.addWidget(self.inputFecha)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelSuplem = QtWidgets.QLabel(Dialog)
        self.labelSuplem.setMinimumSize(QtCore.QSize(100, 0))
        self.labelSuplem.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSuplem.setObjectName("labelSuplem")
        self.horizontalLayout_8.addWidget(self.labelSuplem)
        self.inputSuplem = QtWidgets.QLineEdit(Dialog)
        self.inputSuplem.setMinimumSize(QtCore.QSize(192, 0))
        self.inputSuplem.setObjectName("inputSuplem")
        self.horizontalLayout_8.addWidget(self.inputSuplem)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonGuardar = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonGuardar.sizePolicy().hasHeightForWidth())
        self.buttonGuardar.setSizePolicy(sizePolicy)
        self.buttonGuardar.setObjectName("buttonGuardar")
        self.horizontalLayout.addWidget(self.buttonGuardar)
        self.buttonCancelar = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCancelar.sizePolicy().hasHeightForWidth())
        self.buttonCancelar.setSizePolicy(sizePolicy)
        self.buttonCancelar.setObjectName("buttonCancelar")
        self.horizontalLayout.addWidget(self.buttonCancelar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem8)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.inputFecha, self.inputSuplem)
        Dialog.setTabOrder(self.inputSuplem, self.buttonGuardar)
        Dialog.setTabOrder(self.buttonGuardar, self.buttonCancelar)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelProject.setText(_translate("Dialog", "Personal del evento"))
        self.labelCodigo.setText(_translate("Dialog", "Código"))
        self.labelNombre.setText(_translate("Dialog", "Nombre"))
        self.labelApellidos.setText(_translate("Dialog", "Apellidos"))
        self.labelCargo.setText(_translate("Dialog", "Cargo"))
        self.labelFecha.setText(_translate("Dialog", "Fecha"))
        self.labelSuplem.setText(_translate("Dialog", "Suplemento"))
        self.buttonGuardar.setText(_translate("Dialog", "Aceptar"))
        self.buttonCancelar.setText(_translate("Dialog", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

