# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projectmanagers_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class ProjectManagers_Ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1201, 753)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle.sizePolicy().hasHeightForWidth())
        self.labelTitle.setSizePolicy(sizePolicy)
        self.labelTitle.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableManagers = QtWidgets.QTableWidget(Form)
        self.tableManagers.setObjectName("tableManagers")
        self.tableManagers.setColumnCount(6)
        self.tableManagers.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableManagers.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableManagers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableManagers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableManagers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableManagers.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableManagers.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableManagers.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableManagers.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableManagers.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableManagers.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableManagers.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableManagers.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableManagers.setItem(0, 5, item)
        self.horizontalLayout_2.addWidget(self.tableManagers)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem2, 7, 2, 1, 1)
        self.labelDni = QtWidgets.QLabel(Form)
        self.labelDni.setObjectName("labelDni")
        self.gridLayout.addWidget(self.labelDni, 3, 0, 1, 1)
        self.labelNombre = QtWidgets.QLabel(Form)
        self.labelNombre.setObjectName("labelNombre")
        self.gridLayout.addWidget(self.labelNombre, 0, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 3, 1, 1)
        self.labelTelefono = QtWidgets.QLabel(Form)
        self.labelTelefono.setObjectName("labelTelefono")
        self.gridLayout.addWidget(self.labelTelefono, 2, 0, 1, 2)
        self.inputTelefono = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputTelefono.sizePolicy().hasHeightForWidth())
        self.inputTelefono.setSizePolicy(sizePolicy)
        self.inputTelefono.setObjectName("inputTelefono")
        self.gridLayout.addWidget(self.inputTelefono, 2, 2, 1, 1)
        self.labelApellidos = QtWidgets.QLabel(Form)
        self.labelApellidos.setObjectName("labelApellidos")
        self.gridLayout.addWidget(self.labelApellidos, 1, 0, 1, 2)
        self.inputApellidos = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputApellidos.sizePolicy().hasHeightForWidth())
        self.inputApellidos.setSizePolicy(sizePolicy)
        self.inputApellidos.setObjectName("inputApellidos")
        self.gridLayout.addWidget(self.inputApellidos, 1, 2, 1, 1)
        self.inputNombre = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNombre.sizePolicy().hasHeightForWidth())
        self.inputNombre.setSizePolicy(sizePolicy)
        self.inputNombre.setObjectName("inputNombre")
        self.gridLayout.addWidget(self.inputNombre, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 3, 3, 1, 1)
        self.inputDni = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputDni.sizePolicy().hasHeightForWidth())
        self.inputDni.setSizePolicy(sizePolicy)
        self.inputDni.setObjectName("inputDni")
        self.gridLayout.addWidget(self.inputDni, 3, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 4, 3, 1, 1)
        self.labelNotas = QtWidgets.QLabel(Form)
        self.labelNotas.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelNotas.setObjectName("labelNotas")
        self.gridLayout.addWidget(self.labelNotas, 5, 0, 1, 1)
        self.labelEmail = QtWidgets.QLabel(Form)
        self.labelEmail.setObjectName("labelEmail")
        self.gridLayout.addWidget(self.labelEmail, 4, 0, 1, 1)
        self.inputNotas = QtWidgets.QPlainTextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNotas.sizePolicy().hasHeightForWidth())
        self.inputNotas.setSizePolicy(sizePolicy)
        self.inputNotas.setObjectName("inputNotas")
        self.gridLayout.addWidget(self.inputNotas, 5, 2, 2, 2)
        self.inputEmail = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputEmail.sizePolicy().hasHeightForWidth())
        self.inputEmail.setSizePolicy(sizePolicy)
        self.inputEmail.setObjectName("inputEmail")
        self.gridLayout.addWidget(self.inputEmail, 4, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.buttonAnadir = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAnadir.sizePolicy().hasHeightForWidth())
        self.buttonAnadir.setSizePolicy(sizePolicy)
        self.buttonAnadir.setObjectName("buttonAnadir")
        self.horizontalLayout.addWidget(self.buttonAnadir)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.gridLayout.addLayout(self.horizontalLayout, 8, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 9, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonGuardar = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonGuardar.sizePolicy().hasHeightForWidth())
        self.buttonGuardar.setSizePolicy(sizePolicy)
        self.buttonGuardar.setObjectName("buttonGuardar")
        self.horizontalLayout_3.addWidget(self.buttonGuardar)
        self.buttonEliminar = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonEliminar.sizePolicy().hasHeightForWidth())
        self.buttonEliminar.setSizePolicy(sizePolicy)
        self.buttonEliminar.setObjectName("buttonEliminar")
        self.horizontalLayout_3.addWidget(self.buttonEliminar)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.inputNombre, self.inputApellidos)
        Form.setTabOrder(self.inputApellidos, self.inputTelefono)
        Form.setTabOrder(self.inputTelefono, self.inputDni)
        Form.setTabOrder(self.inputDni, self.inputEmail)
        Form.setTabOrder(self.inputEmail, self.inputNotas)
        Form.setTabOrder(self.inputNotas, self.buttonAnadir)
        Form.setTabOrder(self.buttonAnadir, self.buttonGuardar)
        Form.setTabOrder(self.buttonGuardar, self.buttonEliminar)
        Form.setTabOrder(self.buttonEliminar, self.tableManagers)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelTitle.setText(_translate("Form", "Project Managers"))
        item = self.tableManagers.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableManagers.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Nombre"))
        item = self.tableManagers.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Apellidos"))
        item = self.tableManagers.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Teléfono"))
        item = self.tableManagers.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Email"))
        item = self.tableManagers.horizontalHeaderItem(4)
        item.setText(_translate("Form", "DNI"))
        item = self.tableManagers.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Notas"))
        __sortingEnabled = self.tableManagers.isSortingEnabled()
        self.tableManagers.setSortingEnabled(False)
        item = self.tableManagers.item(0, 0)
        item.setText(_translate("Form", "Xavi"))
        item = self.tableManagers.item(0, 1)
        item.setText(_translate("Form", "Pamies Gual"))
        item = self.tableManagers.item(0, 2)
        item.setText(_translate("Form", "654783928"))
        item = self.tableManagers.item(0, 3)
        item.setText(_translate("Form", "xavi@example.es"))
        item = self.tableManagers.item(0, 4)
        item.setText(_translate("Form", "76548932M"))
        item = self.tableManagers.item(0, 5)
        item.setText(_translate("Form", "Inglés"))
        self.tableManagers.setSortingEnabled(__sortingEnabled)
        self.labelDni.setText(_translate("Form", "DNI"))
        self.labelNombre.setText(_translate("Form", "Nombre"))
        self.labelTelefono.setText(_translate("Form", "Teléfono"))
        self.labelApellidos.setText(_translate("Form", "Apellidos"))
        self.labelNotas.setText(_translate("Form", "Notas"))
        self.labelEmail.setText(_translate("Form", "Email"))
        self.inputNotas.setPlainText(_translate("Form", "gargamel"))
        self.buttonAnadir.setText(_translate("Form", "Añadir"))
        self.buttonGuardar.setText(_translate("Form", "Guardar cambios"))
        self.buttonEliminar.setText(_translate("Form", "Eliminar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = ProjectManagers_Ui()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

