# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proveedorevento_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class ProveedorEvento_Ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(443, 624)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelProject = QtWidgets.QLabel(Dialog)
        self.labelProject.setMinimumSize(QtCore.QSize(220, 0))
        self.labelProject.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.labelProject.setObjectName("labelProject")
        self.horizontalLayout_2.addWidget(self.labelProject)
        self.inputEvento = QtWidgets.QLineEdit(Dialog)
        self.inputEvento.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputEvento.sizePolicy().hasHeightForWidth())
        self.inputEvento.setSizePolicy(sizePolicy)
        self.inputEvento.setMinimumSize(QtCore.QSize(192, 0))
        self.inputEvento.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.inputEvento.setText("")
        self.inputEvento.setObjectName("inputEvento")
        self.horizontalLayout_2.addWidget(self.inputEvento)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelCodigo = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCodigo.sizePolicy().hasHeightForWidth())
        self.labelCodigo.setSizePolicy(sizePolicy)
        self.labelCodigo.setMinimumSize(QtCore.QSize(100, 0))
        self.labelCodigo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.labelCodigo.setObjectName("labelCodigo")
        self.horizontalLayout_3.addWidget(self.labelCodigo)
        self.inputCodigo = QtWidgets.QLineEdit(Dialog)
        self.inputCodigo.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputCodigo.sizePolicy().hasHeightForWidth())
        self.inputCodigo.setSizePolicy(sizePolicy)
        self.inputCodigo.setMinimumSize(QtCore.QSize(192, 0))
        self.inputCodigo.setObjectName("inputCodigo")
        self.horizontalLayout_3.addWidget(self.inputCodigo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelNombre = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelNombre.sizePolicy().hasHeightForWidth())
        self.labelNombre.setSizePolicy(sizePolicy)
        self.labelNombre.setMinimumSize(QtCore.QSize(100, 0))
        self.labelNombre.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.labelNombre.setObjectName("labelNombre")
        self.horizontalLayout_4.addWidget(self.labelNombre)
        self.inputEmpresa = QtWidgets.QLineEdit(Dialog)
        self.inputEmpresa.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputEmpresa.sizePolicy().hasHeightForWidth())
        self.inputEmpresa.setSizePolicy(sizePolicy)
        self.inputEmpresa.setMinimumSize(QtCore.QSize(192, 0))
        self.inputEmpresa.setObjectName("inputEmpresa")
        self.horizontalLayout_4.addWidget(self.inputEmpresa)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelCargo = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCargo.sizePolicy().hasHeightForWidth())
        self.labelCargo.setSizePolicy(sizePolicy)
        self.labelCargo.setMinimumSize(QtCore.QSize(100, 0))
        self.labelCargo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.labelCargo.setObjectName("labelCargo")
        self.horizontalLayout_5.addWidget(self.labelCargo)
        self.comboServicio = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboServicio.sizePolicy().hasHeightForWidth())
        self.comboServicio.setSizePolicy(sizePolicy)
        self.comboServicio.setMinimumSize(QtCore.QSize(192, 0))
        self.comboServicio.setObjectName("comboServicio")
        self.horizontalLayout_5.addWidget(self.comboServicio)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelFecha = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFecha.sizePolicy().hasHeightForWidth())
        self.labelFecha.setSizePolicy(sizePolicy)
        self.labelFecha.setMinimumSize(QtCore.QSize(100, 0))
        self.labelFecha.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.labelFecha.setObjectName("labelFecha")
        self.horizontalLayout_6.addWidget(self.labelFecha)
        self.inputFecha = QtWidgets.QLineEdit(Dialog)
        self.inputFecha.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputFecha.sizePolicy().hasHeightForWidth())
        self.inputFecha.setSizePolicy(sizePolicy)
        self.inputFecha.setMinimumSize(QtCore.QSize(192, 0))
        self.inputFecha.setObjectName("inputFecha")
        self.horizontalLayout_6.addWidget(self.inputFecha)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelHora = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHora.sizePolicy().hasHeightForWidth())
        self.labelHora.setSizePolicy(sizePolicy)
        self.labelHora.setMinimumSize(QtCore.QSize(100, 0))
        self.labelHora.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.labelHora.setObjectName("labelHora")
        self.horizontalLayout_7.addWidget(self.labelHora)
        self.hora = QtWidgets.QTimeEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hora.sizePolicy().hasHeightForWidth())
        self.hora.setSizePolicy(sizePolicy)
        self.hora.setAlignment(QtCore.Qt.AlignCenter)
        self.hora.setObjectName("hora")
        self.horizontalLayout_7.addWidget(self.hora)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelContacto = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelContacto.sizePolicy().hasHeightForWidth())
        self.labelContacto.setSizePolicy(sizePolicy)
        self.labelContacto.setMinimumSize(QtCore.QSize(100, 0))
        self.labelContacto.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.labelContacto.setObjectName("labelContacto")
        self.horizontalLayout_8.addWidget(self.labelContacto)
        self.inputContacto = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputContacto.sizePolicy().hasHeightForWidth())
        self.inputContacto.setSizePolicy(sizePolicy)
        self.inputContacto.setMinimumSize(QtCore.QSize(192, 0))
        self.inputContacto.setObjectName("inputContacto")
        self.horizontalLayout_8.addWidget(self.inputContacto)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.labelTelefono = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTelefono.sizePolicy().hasHeightForWidth())
        self.labelTelefono.setSizePolicy(sizePolicy)
        self.labelTelefono.setMinimumSize(QtCore.QSize(100, 0))
        self.labelTelefono.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.labelTelefono.setObjectName("labelTelefono")
        self.horizontalLayout_9.addWidget(self.labelTelefono)
        self.inputTelefono = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputTelefono.sizePolicy().hasHeightForWidth())
        self.inputTelefono.setSizePolicy(sizePolicy)
        self.inputTelefono.setMinimumSize(QtCore.QSize(192, 0))
        self.inputTelefono.setObjectName("inputTelefono")
        self.horizontalLayout_9.addWidget(self.inputTelefono)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelEmail = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEmail.sizePolicy().hasHeightForWidth())
        self.labelEmail.setSizePolicy(sizePolicy)
        self.labelEmail.setMinimumSize(QtCore.QSize(100, 0))
        self.labelEmail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.labelEmail.setObjectName("labelEmail")
        self.horizontalLayout_10.addWidget(self.labelEmail)
        self.inputEmail = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputEmail.sizePolicy().hasHeightForWidth())
        self.inputEmail.setSizePolicy(sizePolicy)
        self.inputEmail.setMinimumSize(QtCore.QSize(192, 0))
        self.inputEmail.setObjectName("inputEmail")
        self.horizontalLayout_10.addWidget(self.inputEmail)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelNotas = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelNotas.sizePolicy().hasHeightForWidth())
        self.labelNotas.setSizePolicy(sizePolicy)
        self.labelNotas.setMinimumSize(QtCore.QSize(100, 0))
        self.labelNotas.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.labelNotas.setObjectName("labelNotas")
        self.verticalLayout.addWidget(self.labelNotas)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.inputNotas = QtWidgets.QPlainTextEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNotas.sizePolicy().hasHeightForWidth())
        self.inputNotas.setSizePolicy(sizePolicy)
        self.inputNotas.setMinimumSize(QtCore.QSize(192, 150))
        self.inputNotas.setMaximumSize(QtCore.QSize(170, 200))
        self.inputNotas.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inputNotas.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.inputNotas.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.inputNotas.setCursorWidth(0)
        self.inputNotas.setObjectName("inputNotas")
        self.horizontalLayout_11.addWidget(self.inputNotas)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem11)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonGuardar = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonGuardar.sizePolicy().hasHeightForWidth())
        self.buttonGuardar.setSizePolicy(sizePolicy)
        self.buttonGuardar.setObjectName("buttonGuardar")
        self.horizontalLayout.addWidget(self.buttonGuardar)
        self.buttonCancelar = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCancelar.sizePolicy().hasHeightForWidth())
        self.buttonCancelar.setSizePolicy(sizePolicy)
        self.buttonCancelar.setObjectName("buttonCancelar")
        self.horizontalLayout.addWidget(self.buttonCancelar)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem12)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.comboServicio, self.hora)
        Dialog.setTabOrder(self.hora, self.inputContacto)
        Dialog.setTabOrder(self.inputContacto, self.inputTelefono)
        Dialog.setTabOrder(self.inputTelefono, self.inputEmail)
        Dialog.setTabOrder(self.inputEmail, self.inputNotas)
        Dialog.setTabOrder(self.inputNotas, self.inputEvento)
        Dialog.setTabOrder(self.inputEvento, self.inputCodigo)
        Dialog.setTabOrder(self.inputCodigo, self.inputEmpresa)
        Dialog.setTabOrder(self.inputEmpresa, self.inputFecha)
        Dialog.setTabOrder(self.inputFecha, self.buttonGuardar)
        Dialog.setTabOrder(self.buttonGuardar, self.buttonCancelar)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelProject.setText(_translate("Dialog", "Proveedor del evento"))
        self.labelCodigo.setText(_translate("Dialog", "Código"))
        self.labelNombre.setText(_translate("Dialog", "Empresa"))
        self.labelCargo.setText(_translate("Dialog", "Servicio"))
        self.labelFecha.setText(_translate("Dialog", "Fecha"))
        self.labelHora.setText(_translate("Dialog", "Hora"))
        self.labelContacto.setText(_translate("Dialog", "Contacto\n"
"On-site"))
        self.labelTelefono.setText(_translate("Dialog", "Teléfono\n"
"On-site"))
        self.labelEmail.setText(_translate("Dialog", "Email\n"
"On-site"))
        self.labelNotas.setText(_translate("Dialog", "Notas"))
        self.buttonGuardar.setText(_translate("Dialog", "Aceptar"))
        self.buttonCancelar.setText(_translate("Dialog", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = ProveedorEvento_Ui()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

